fix: make sure to render unique transitions to not break the UI
dfinity/nns-dapp pull request #1157
Opened 2022-07-22 08:02 UTC by mstrasinskis

# Motivation

Switch to unique transitions to not break the UI. E.g. could be the case when user send ICP from `main` to `main` account (by address). In that case, no transactions are displayed, and even the back button is broken.

## Before
<img width="1343" alt="Screenshot 2022-07-22 at 10 37 29" src="https://user-images.githubusercontent.com/98811342/180391745-65b68339-4b9e-4793-a863-755c27a18420.png">
<img width="987" alt="Screenshot 2022-07-22 at 10 47 26" src="https://user-images.githubusercontent.com/98811342/180391769-927224c2-42bf-4d58-a77c-9029d7651ce4.png">

## After
<img width="1339" alt="Screenshot 2022-07-22 at 10 43 59" src="https://user-images.githubusercontent.com/98811342/180391827-d8c7955d-aaf1-42b1-bc20-9fc8d7323dcd.png">

# Changes

- apply `uniqueObjects` to the fetched transactions

# Tests

- `Wallet` test updated

2022-07-22 08:28 UTC, peterpeterparker commented
Isn't it correct two display the two transactions?

1. One displayed as minus operation minus the transaction fee
2. The other as a plus movement

If this is correct, then I would say that the bug is maybe in the key used in cmp `TransactionList` for the svelte each (`transaction.timestamp.timestamp_nanos`)

2022-07-22 08:43 UTC, peterpeterparker requested changes
Just blocking it because @lmuntaner has accepted it while I tend to think it should not be merged, see my question.

But I can be fully wrong, code is fine, more a feature related question.

2022-07-25 08:17 UTC, mstrasinskis commented
> Isn't it correct two display the two transactions?
> 
>     1. One displayed as minus operation minus the transaction fee ("Sent ICP -10.0001")
> 
>     2. The other as a plus movement ("Received ICP +10.0000")
> 
> 
> Or there are no transaction fee if same account?
> 
> If this is correct, then I would say that the bug is maybe in the key used in cmp `TransactionList` for the svelte each (`transaction.timestamp.timestamp_nanos`)

Updated according to your suggestion. From UX perspective, if find it better:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98811342/180730977-fe57288f-e7b7-4996-b008-67a103e3647e.png">

2022-07-25 09:42 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/transactions.utils.ts
> +  const useFee =
there isn't a fee in case of same receiver and sender?

2022-07-25 09:43 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/transactions.utils.ts
> +    const { transaction: nextTransaction } = resultTransactions[i + 1];
isn't this a bit optimistic? isn't there a more accurate information / id to link both?

2022-07-25 15:08 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/transactions.utils.ts
> +    const { transaction: nextTransaction } = resultTransactions[i + 1];
as discussed this is a bit optimitic but it's not like we have other choices since it's the data we get.
we will add some comments and after the pr is merge continue to inspect with other teams to check backend data

2022-07-25 15:08 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/transactions.utils.ts
> +  const useFee =
as discussed maybe a comment

2022-07-25 15:09 UTC, peterpeterparker approved these changes
As discussed, maybe a bit more comments and let's go with it, not like we have much choice with the data we have.

Thanks!

2022-07-27 07:54 UTC, merged