Fix: Max button in sale participation
dfinity/nns-dapp pull request #1297
Opened 2022-09-01 12:23 UTC by lmuntaner

# Motivation

Max button in sale participation didn't consider the remaining amount of the project.

# Changes

* Add maxAmount parameter to TransactionModal.
* Use new maxAmount when calculating the max of the transaction amount.
* Rename and refactor maxICP to use e8s to maxE8sToNumber
* New icp util minE8s that returns the minimum of two bigint, ignoring undefined.
* New project util to expose the remaining amount of a project projectRemainingAmount

# Tests

* New tests for project util projectRemainingAmount
* New tests for new icp utils minE8s
* Fix broken test after refactor.

2022-09-01 12:41 UTC, mstrasinskis requested changes
LGTM, only one question.

2022-09-01 12:41 UTC, mstrasinskis commented on frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
> +      (maxAmount ?? BigInt(0)) + $mainTransactionFeeStoreAsIcp.toE8s()
Not sure, could you please recheck that this value should include `$mainTransactionFeeStoreAsIcp.toE8s()`?
Probably:
```ts
e8s: minE8s(
      selectedAccount?.balance.toE8s() - $mainTransactionFeeStoreAsIcp.toE8s(),
      maxAmount ?? BigInt(0)
```

2022-09-01 12:46 UTC, lmuntaner commented on frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
> +      (maxAmount ?? BigInt(0)) + $mainTransactionFeeStoreAsIcp.toE8s()
The fee is already "removed" inside `maxE8sToNumber`.

Maybe not the best helper ever I'd say...

To be honest, it does just a subtraction and conversion to a number by dividing by E8S_PER_ICP

Maybe we don't want to hide that. What do you think?

2022-09-01 13:07 UTC, mstrasinskis commented on frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
> +      (maxAmount ?? BigInt(0)) + $mainTransactionFeeStoreAsIcp.toE8s()
Ah, right, the fee was already substracted. I agree, looks like `maxE8sToNumber` does more than e.g. it's sibling util `minE8s`. Would be nice either rename it or don't use fee there.

2022-09-02 05:34 UTC, lmuntaner commented on frontend/src/lib/modals/accounts/NewTransaction/TransactionForm.svelte
> +      (maxAmount ?? BigInt(0)) + $mainTransactionFeeStoreAsIcp.toE8s()
Changed to the following util:

```
/**
 * Calculates the maximum amount for a transaction.
 *
 * @param balanceE8s The balance of the account in E8S.
 * @param fee The fee of the transaction in E8S.
 * @param maxAmount The maximum amount of the transaction not counting the fees.
 * @returns
 */
export const getMaxTransactionAmount = ({
  balance = BigInt(0),
  fee = BigInt(0),
  maxAmount,
}: {
  balance?: bigint;
  fee?: bigint;
  maxAmount?: bigint;
}): number => {
  if (maxAmount === undefined) {
    return Math.max(Number(balance - fee), 0) / E8S_PER_ICP;
  }
  return Math.min(Number(maxAmount), Number(balance - fee)) / E8S_PER_ICP;
};
```

Let me know what you think

2022-09-02 05:35 UTC, lmuntaner commented
@mstrasinskis ready for another review

2022-09-02 06:03 UTC, mstrasinskis approved these changes
LGTM, thank you. 2 minor suggestions.

2022-09-02 06:03 UTC, mstrasinskis commented on frontend/src/lib/utils/icp.utils.ts
> +  return Math.min(Number(maxAmount), Number(balance - fee)) / E8S_PER_ICP;
```suggestion
  return Math.min(Number(maxAmount), Math.max(Number(balance - fee), 0)) / E8S_PER_ICP;
```

2022-09-02 08:06 UTC, lmuntaner commented on frontend/src/lib/utils/icp.utils.ts
> +  balance?: bigint;
This is a common pattern we use. Instead of handling the `undefined` outside the function, we handle it inside.

For example:
```
export const isAccountHardwareWallet = (
  account: Account | undefined
): boolean => account?.type === "hardwareWallet";

export const getAccountFromStore = ({
  identifier,
  accountsStore: { main, subAccounts, hardwareWallets },
}: {
  identifier: string | undefined;
  accountsStore: AccountsStore;
}): Account | undefined => {
```

This avoids repeating the same code of checking `undefined` outside the function.

Not that I am a big fan of this pattern. But I am a big fan of consistency.

2022-09-02 08:07 UTC, lmuntaner commented on frontend/src/lib/utils/icp.utils.ts
> +  return Math.min(Number(maxAmount), Number(balance - fee)) / E8S_PER_ICP;
Good point!

2022-09-02 08:07 UTC, lmuntaner commented on frontend/src/lib/utils/icp.utils.ts
> +  return Math.min(Number(maxAmount), Number(balance - fee)) / E8S_PER_ICP;
I will also add a test for this.

2022-09-02 08:10 UTC, lmuntaner commented on frontend/src/lib/utils/icp.utils.ts
> +  return Math.min(Number(maxAmount), Number(balance - fee)) / E8S_PER_ICP;
done

2022-09-02 08:28 UTC, merged