Gix 984 disburse sns neuron
dfinity/nns-dapp pull request #1340
Opened 2022-09-16 10:44 UTC by mstrasinskis

# Motivation

Provide `disburse` sns neuron functionality. Simplified `nns` version logic (uses `main` account only, disburses all available amount)
Jira: https://dfinity.atlassian.net/browse/GIX-984

- [x] Requires [ic-js PR](https://github.com/dfinity/ic-js/pull/187)

# Changes

- sns api `disburse()`
- sns service `disburse()`
- move disburse logic from `ConfirmDisburseNeuron` to `DisburseNnsNeuronModal`
- add modal param to `DisburseButton` to display nns and nns versions
- add `DisburseButton` to `SnsNeuronMetaInfoCard`
- fee param to `TransactionInfo`
- new sns util `hasPermissions`, `isDissolved`

# Tests

- DisburseButton.spec sns modal support
- ConfirmDisburseNeuron.spec
- DisburseSnsNeuronModal.spec
- sns-neuron.utils.spec: `hasPermissions`, `isDissolved`
- 

# Screenshots

<img width="958" alt="image" src="https://user-images.githubusercontent.com/98811342/192809482-7de4e313-6d8c-4acc-bf49-54d9da4751d7.png">

2022-09-26 13:09 UTC, lmuntaner requested changes
Looking good! A few changes.

Btw, the screenshot shows ICP, is it because you couldn't check yet with an SNS neuron?

2022-09-26 13:09 UTC, lmuntaner commented on frontend/src/tests/lib/components/neuron-detail/actions/DisburseButton.spec.ts
> +  it("opens a modal", async () => {
maybe be specific with "opens disburse nns neuron modal"

2022-09-26 13:09 UTC, lmuntaner commented on frontend/src/lib/utils/sns.utils.ts
> +export const isDissolved = (neuron: SnsNeuron) =>
I guess you should be able to use the helper `getSnsNeuronState`.

A neuron is dissolved when there is no dissolve_state data.

2022-09-26 13:09 UTC, lmuntaner commented on frontend/src/lib/services/sns-neurons.services.ts
> +export const disburse = async ({
Do you have a test for this service?

2022-09-28 09:23 UTC, mstrasinskis commented on frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
> +<WizardModal {steps} bind:currentStep on:nnsClose>
Good point. Done

2022-09-28 10:17 UTC, mstrasinskis commented on frontend/src/lib/utils/sns.utils.ts
> +export const isDissolved = (neuron: SnsNeuron) =>
Good point. Done.

2022-09-28 10:18 UTC, mstrasinskis commented on frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
> +      fee={neuron.neuron_fees_e8s}
Thanks. A todo was added: https://dfinity.atlassian.net/browse/GIX-1044

2022-09-28 10:57 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +export const disburse = async ({
Good catch!

2022-09-28 11:22 UTC, lmuntaner commented on frontend/src/lib/components/neuron-detail/ConfirmDisburseNeuron.svelte
> +  {#if destinationAddress !== undefined}
How can it be optional? Why is that?

2022-09-28 11:22 UTC, lmuntaner commented on frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
> +      fee={neuron.neuron_fees_e8s}
thanks!

2022-09-28 15:26 UTC, lmuntaner requested changes
Just a few more comments / changes.

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/components/accounts/TransactionInfo.svelte
> +      fee === undefined ? $mainTransactionFeeStore : fee.toE8s()
nth: `fee?.toE8s() ?? $mainTransactionFeeStore`?

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/components/accounts/TransactionInfo.svelte
> +  {fee === undefined ? $i18n.core.icp : fee.token.symbol}
nth: `fee?.token.symbol ?? $i18n.core.icp`?

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
> +  let dissolveState: ReturnType<getSnsNeuronState> | undefined;
the return type is `NeuronState` from nns-js, isn't it?

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/modals/neurons/DisburseNeuronModal.svelte
>  <script lang="ts">
Could you maybe rename it to `DisburseNnsNeuronModal`? I found it confusing when reading. I was half expecting it to be generic.

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/modals/neurons/DisburseNeuronModal.svelte
> +        path: AppPath.LegacyNeurons,
can you use the derived store I created `neuronsPathStore` in `derived/paths.derived.ts`.

This way we won't have to change when we enable SNS and it also keeps context.

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/modals/neurons/DisburseSnsNeuronModal.svelte
> +        path: AppPath.LegacyNeurons,
ditto with `neuronsPathStore`

2022-09-28 15:26 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
Why not `NeuronState`?

2022-09-29 08:12 UTC, mstrasinskis commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
Because there is no way to return other values of the enum. But not a strong opinion, would you prefer using `NeuronState`?

2022-09-29 08:14 UTC, mstrasinskis commented on frontend/src/lib/modals/neurons/DisburseNeuronModal.svelte
>  <script lang="ts">
I was initially `DisburseNnsNeuronModal` but then I renamed it back because I saw some samples. But agree, will be renamed 👍

2022-09-29 08:48 UTC, mstrasinskis commented on frontend/src/lib/modals/neurons/DisburseNeuronModal.svelte
> +        path: AppPath.LegacyNeurons,
Cool feature, thanks 👍

2022-09-29 09:49 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
What do you mean "no way to receive other values of the enum". Is it because we are not using all the values of the enum?

2022-09-29 10:58 UTC, mstrasinskis commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
Yes, this function returns only 4 enum values out of 5. But for simplicity I'll undo it to `NeuronState`

2022-09-29 11:09 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
I would say so. Which is the one we don't use?

2022-09-30 09:04 UTC, mstrasinskis commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
not in use here: `NeuronState.Spawning`

2022-10-03 04:51 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +}: SnsNeuron):
Ok, we use that somewhere else, therefore we could reuse this helper. But not in this PR.

2022-10-03 08:15 UTC, lmuntaner approved these changes
LGTM, thanks!

2022-10-04 10:18 UTC, merged