Gix 1175 users can split a neuron
dfinity/nns-dapp pull request #1659
Opened 2022-12-21 22:17 UTC by mstrasinskis

# Motivation

# Changes

# Tests

2022-12-28 09:49 UTC, lmuntaner commented on frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
> +  $: allowedToSplit =
Isn't there a minimum amount to split?

2022-12-28 10:11 UTC, lmuntaner reviewed
Looking good! Some comments only.

2022-12-28 10:11 UTC, lmuntaner commented on frontend/src/lib/services/sns-neurons.services.ts
> +  transactionFee,
Ditto that it could be read from the store.

Yet, not a strong opinion. But it would be good to do it always the same way.

In here these paremeters are used to perform checks and show errors. They are not strictly related to splitting a neuron. That's why I mentioned that the service could access that data.

2022-12-28 10:11 UTC, lmuntaner commented on frontend/src/lib/services/sns-neurons.services.ts
> +
Don't we need to reload neurons as well here? So that they will appear in the neuron list?

2022-12-28 10:11 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +neuron_minimum_stake_e8s
Why these three lines?

2022-12-28 10:11 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +- The amount to split minus the transfer fee is more than the minimum stake (thus the child neuron will have at least the minimum stake)
Shouldn't this comments be in the helper `minNeuronSplittable`?

Then the comment here is: "The neuron can be split when the stake is higher than the minimum required".

2022-12-28 10:11 UTC, lmuntaner commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +export const minNeuronSplittable = ({
The two comments could go here to explain the logic of `2n * ...`

2022-12-29 11:53 UTC, mstrasinskis commented on frontend/src/lib/modals/sns/neurons/SnsStakeMaturityModal.svelte
> +    // TODO: Checks subaccounts of identity in order to find neurons that need to be refreshed or claimed. ?
This comment is not related to this PR, just wanna discuss this w/ you to better understand, is it necessary here or not? There is no `checkSnsNeuronBalances` on the `/neuron detail` page, only on the `/neurons`.

2022-12-29 11:59 UTC, mstrasinskis commented on frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
> +      amount: BigInt(Math.round(amount * Number(E8S_PER_ICP))),
Thanks, saw it in your last PR. Updated 👍

2022-12-29 12:01 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +  token: { symbol },
I would prefer to keep it as a prop, so it's guarded by types. Otherwise the service should handle the lack of value in the store.

2022-12-29 12:02 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +  amount: E8s;
Done. `numberToE8s` applied.

2022-12-29 12:12 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +
The neuron list calls `syncSnsNeurons` using queryAndUpdate. This should provide an updated list.

2022-12-29 12:14 UTC, mstrasinskis commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +neuron_minimum_stake_e8s
Good catch, relic. Removed.

2022-12-29 12:15 UTC, mstrasinskis commented on frontend/src/lib/utils/sns-neuron.utils.ts
> +- The amount to split minus the transfer fee is more than the minimum stake (thus the child neuron will have at least the minimum stake)
Good point. Is moved.

2022-12-30 07:32 UTC, peterpeterparker commented on frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
> +{#if nonNullish(neuron) && nonNullish(neuronState) && nonNullish(parameters)}
Doesn't this make the layout shift? Particularly if loading the paramters is slow.

2022-12-30 07:33 UTC, peterpeterparker commented on frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
> +      {#if ENABLE_SNS_2}
nth: `{#if ENABLE_SNS_2 && allowedToSplit}`

2022-12-30 07:34 UTC, peterpeterparker commented on frontend/src/lib/i18n/en.json
> +    "sns_amount_not_enough_stake_neuron": "Sorry, the amount is too small. You need a minimum of $minimum $token to stake a neuron"
`.` at the end of the sentence?

2022-12-30 07:36 UTC, peterpeterparker commented on frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte
> +      {#if parameters !== undefined && transactionFee !== undefined}
`isNullish` instead of `!== undefined`?

2022-12-30 07:38 UTC, peterpeterparker commented on frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
> +    await reloadNeuron();
we reload the neuron on error too?

2022-12-30 07:40 UTC, peterpeterparker commented on frontend/src/lib/pages/SnsNeuronDetail.svelte
> +        loadSnsParameters(rootCanisterId);
why reloading params and transaction fee but not accounts?

2022-12-30 07:42 UTC, peterpeterparker commented on frontend/src/lib/services/sns-neurons.services.ts
> +    const memo = nextMemo({
why is the next memo not computed by the backend?
or what happens if the next memo used is already taken when processed by the backend?

2022-12-30 07:44 UTC, peterpeterparker commented on frontend/src/lib/utils/token.utils.ts
> +      amount: BigInt(fee.toE8s()),
the cast is needed? isn't `fee.toE8s()` already a `BigInt`?

2022-12-30 07:54 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +    const memo = nextMemo({
Here is the second attempt to discuss this w/ `nns` - https://dfinity.slack.com/archives/C0175CHJ0P6/p1672220542021449.

2022-12-30 07:59 UTC, peterpeterparker commented on frontend/src/lib/services/sns-neurons.services.ts
> +    const memo = nextMemo({
Thanks. Can you add a comment that there is a loop hole in this flow?

i.e. generally speaking, after the payment flow discussions, I think every time we are "forced" in the frontend to evaluate something that in our opinion should be computed in the backend to be more robust we should comment it explicitely in the code

2022-12-30 08:29 UTC, mstrasinskis commented on frontend/src/lib/utils/token.utils.ts
> +      amount: BigInt(fee.toE8s()),
Good catch, a relic.

2022-12-30 08:38 UTC, mstrasinskis commented on frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
> +    await reloadNeuron();
The initial idea was to reload the neuron in any case because the `splitNeuron` is not atomic operation (update parent neuron, create new one). But not a strong opinion, updated.

2022-12-30 08:48 UTC, peterpeterparker commented on frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
> +    await reloadNeuron();
So it's possible that a new neuron is created but the parent isn't updated, is it what you mean?

2022-12-30 09:01 UTC, mstrasinskis commented on frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte
> +      {#if parameters !== undefined && transactionFee !== undefined}
Updated. Is there another gain except better syntax?

2022-12-30 09:03 UTC, mstrasinskis commented on frontend/src/lib/pages/SnsNeuronDetail.svelte
> +        loadSnsParameters(rootCanisterId);
Not sure I got the question, there is no account info on the neuron detail page.

2022-12-30 09:04 UTC, mstrasinskis commented on frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
> +      {#if ENABLE_SNS_2}
Sure, thanks! 😄

2022-12-30 09:07 UTC, peterpeterparker commented on frontend/src/lib/modals/sns/neurons/SnsNeuronModals.svelte
> +      {#if parameters !== undefined && transactionFee !== undefined}
Spontenously I thought only about the syntax, was only a suggestion too 😉. Cool, thanks for the change.

2022-12-30 09:08 UTC, peterpeterparker commented on frontend/src/lib/pages/SnsNeuronDetail.svelte
> +        loadSnsParameters(rootCanisterId);
e.g. we use the accounts on the neuron detail to increase stake maturity

2022-12-30 10:53 UTC, mstrasinskis commented on frontend/src/lib/components/sns-neuron-detail/SnsNeuronMetaInfoCard.svelte
> +{#if nonNullish(neuron) && nonNullish(neuronState) && nonNullish(parameters)}
Good catch, this is not needed anymore because parameters are provided as prop.

2022-12-30 11:41 UTC, lmuntaner commented on frontend/src/lib/modals/sns/neurons/SnsStakeMaturityModal.svelte
> +    // TODO: Checks subaccounts of identity in order to find neurons that need to be refreshed or claimed. ?
Yes there is, in `getSnsNeuron` we also check whether it needs refresh. But it's a simpler check

2022-12-30 11:42 UTC, lmuntaner commented on frontend/src/lib/services/sns-neurons.services.ts
> +  token: { symbol },
Sounds good!

2022-12-30 11:42 UTC, lmuntaner commented on frontend/src/lib/services/sns-neurons.services.ts
> +
true, nns neuron we need it because it's called on init, but in SNS they are called when visiting the page, thanks!

2023-01-03 17:12 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +    const memo = nextMemo({
Thanks, comment was added.

2023-01-04 08:24 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +  token: { symbol },
To have the same pattern was switched to using stores.

2023-01-04 08:24 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +  transactionFee,
Was switched to using stores.

2023-01-04 08:24 UTC, mstrasinskis commented on frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
> +    await reloadNeuron();
Actually now I don't think it's an issue. The reload is moved in success block. Thanks for noticing.

2023-01-04 09:21 UTC, peterpeterparker commented on frontend/src/lib/pages/SnsNeuronDetail.svelte
> +        loadSnsParameters(rootCanisterId);
Discussed in chat, accounts are reloaded when the modal to increase Sns stake maturity is opened, therefore no need to reload the accounts there.

2023-01-04 09:21 UTC, peterpeterparker approved these changes
LGTM, thanks

2023-01-04 10:04 UTC, lmuntaner requested changes

2023-01-04 10:04 UTC, lmuntaner commented on frontend/src/lib/services/sns-neurons.services.ts
> +export const loadNeurons = async ({
Is this one tested? It might not be tested because it was not exported.

Now that you are exporting it, it might make sense to add a test for it as well.

2023-01-04 10:17 UTC, mstrasinskis commented on frontend/src/lib/modals/sns/neurons/SplitSnsNeuronModal.svelte
> +      close();
Thanks didn't know it's possible, never saw this issue during testing. Updated.

2023-01-04 11:28 UTC, mstrasinskis commented on frontend/src/lib/services/sns-neurons.services.ts
> +export const loadNeurons = async ({
Good point, done!

2023-01-04 11:30 UTC, mstrasinskis commented on frontend/src/lib/components/sns-neuron-detail/actions/SplitSnsNeuronButton.svelte
> +  export let parameters: NervousSystemParameters;
It's still an open question. Probably having a bunch of util functions could be a flexible solution.

2023-01-04 12:45 UTC, merged