Gix 1218 sns proposal details page
dfinity/nns-dapp pull request #1717
Opened 2023-01-16 10:46 UTC by mstrasinskis

# Motivation

Add a proposal detail page  behind the feature flag.

# Changes

- rename ProposalDetailPage to NnsProposalDetailPage
- add SnsProposalDetailPage component
- update routing

# Tests

- no logic to test

# Screenshot

<img width="415" alt="image" src="https://user-images.githubusercontent.com/98811342/212659337-f5d861c9-b3b1-421b-a591-e83dcf916c3b.png">

2023-01-16 11:00 UTC, lmuntaner requested changes

2023-01-16 11:00 UTC, lmuntaner commented on frontend/src/lib/components/sns-proposals/SnsProposalCard.svelte
> -        proposalId: `${id}`,
Thanks!

2023-01-16 11:00 UTC, lmuntaner commented on frontend/src/lib/pages/SnsProposalDetail.svelte
> +      goto(buildProposalUrl({ universe: OWN_CANISTER_ID.toText(), proposalId: proposalIdText }));
I would redirect to `/proposals`, not to stay in the proposal details. How do we know that `proposalIdText` is a valid id for an NNS proposal?

2023-01-16 11:00 UTC, lmuntaner commented on frontend/src/tests/lib/pages/ProposalDetail.spec.ts
>   * @jest-environment jsdom
Rename the file also?

2023-01-16 11:00 UTC, lmuntaner commented on frontend/src/lib/routes/ProposalDetail.svelte
> +<script lang="ts">
Routes also need tests, hehe.

But it's easy, just check that the proper page is rendered. I believe the `Neurons` route is a good example.

2023-01-16 14:07 UTC, mstrasinskis commented on frontend/src/tests/lib/pages/ProposalDetail.spec.ts
>   * @jest-environment jsdom
Thanks, done.

2023-01-16 15:00 UTC, mstrasinskis commented on frontend/src/lib/pages/SnsProposalDetail.svelte
> +      goto(buildProposalUrl({ universe: OWN_CANISTER_ID.toText(), proposalId: proposalIdText }));
Good point. Done!

2023-01-16 15:02 UTC, mstrasinskis commented on frontend/src/lib/routes/ProposalDetail.svelte
> +<script lang="ts">
Thanks, there it is - https://github.com/dfinity/nns-dapp/pull/1717/files#diff-d9e039ce2a464903ee48565732ac64d7242d3086fbdea5351c414b73b5ab9da9R32

2023-01-16 15:27 UTC, lmuntaner approved these changes
LGTM, thanks!

2023-01-16 18:53 UTC, peterpeterparker commented on frontend/src/lib/pages/SnsProposalDetail.svelte
> +      goto(buildProposalsUrl({ universe: OWN_CANISTER_ID.toText() }));
Maybe `goto(buildProposalsUrl({ universe: OWN_CANISTER_ID.toText() }, {replaceState: true}));` - i.e. `replaceState` to avoid user clicking back and ending in a loop?

If yes, same for `SnsProposals`.

2023-01-16 18:54 UTC, peterpeterparker commented on frontend/src/lib/routes/ProposalDetail.svelte
> +    <Summary />
There is a summary on detail page?

2023-01-17 07:10 UTC, mstrasinskis commented on frontend/src/lib/pages/SnsProposalDetail.svelte
> +      goto(buildProposalsUrl({ universe: OWN_CANISTER_ID.toText() }));
Makes sense, updated, thanks.

2023-01-17 07:11 UTC, mstrasinskis commented on frontend/src/lib/routes/ProposalDetail.svelte
> +    <Summary />
Thanks, removed.

2023-01-17 07:42 UTC, merged