GIX-1267: Use "query" not signed in users
dfinity/nns-dapp pull request #1808
Opened 2023-02-02 15:01 UTC by lmuntaner

# Motivation

Not logged in users see uncertified data.

This reduces the load of update calls.

# Changes

Main change
* queryAndUpdate can't be used with other than "query" when identity is anonymous, it raises an error otherwise.

Minor change
* Show the test error when loading sns nervous functions if call fails and not certified but it's anonymous identity.

# Tests

* Add two new workflow tests to check that a user load different data in NnsProposals and NnsProposalDetails.
* Rename the file where queryAndUpdate was being tested to the same where it lives.
* Add a test case in queryAndUpdate test.
* Fix tests after change in functionality.

2023-02-02 16:07 UTC, lmuntaner commented
@peterpeterparker @mstrasinskis @dskloetd please review

I did two "integration" tests to really check that the api calls were as expected.

I liked the idea of @dskloetd to ONLY mock api calls.

Yet, I'm still mocking the authStore subscribe. I think that we can improve that if we move the logic of logging in to a service and we use the autoStore to purely store data and not do any side effects.

I believe that's a best practice as well, we don't do any side effect in any other store.

2023-02-02 17:23 UTC, dskloetd commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: strategy = isSignedIn($authStore.identity) ? "query_and_update" : "query";
I don't see where the value of strategy is being used but shouldn't it be an enum or something instead of a string?

2023-02-02 17:37 UTC, lmuntaner commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: strategy = isSignedIn($authStore.identity) ? "query_and_update" : "query";
That would be another change and a style decision, at the moment:

```
export type QueryAndUpdateStrategy = "query_and_update" | "query" | "update";
```

2023-02-02 18:22 UTC, dskloetd commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: strategy = isSignedIn($authStore.identity) ? "query_and_update" : "query";
I didn't realize it already existed. Does TS guarantee that it can only have those 3 values? I guess then effectively it's already (like) an enum.

I'll have a look at the whole PR tomorrow.

2023-02-02 19:13 UTC, lmuntaner commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: strategy = isSignedIn($authStore.identity) ? "query_and_update" : "query";
Yes, if you try passing any other string it will fail. Also, like an enum. Just a matter of style almost.

With enums you can enumerate them at run time though. Not these.

2023-02-02 19:25 UTC, peterpeterparker commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: strategy = isSignedIn($authStore.identity) ? "query_and_update" : "query";
Style but also because working with enum in TypeScript isn't perfect. It adds often an unnecessary level of complexity that brings no more type checking safety than just using types. In addition, their manipulation is often difficult and end in some unlucky compromise (like applying cast). Using enum in vanilla isn't the most enjoyable experience in life neither.

So yep style but also because enum are sometimes more pain that joy. Therefore keep it simple when it can be. That said, we don't exclude these. We inherits some from Candid and sometimes, like Llorenç said, when we need iteratable "constants" too.

2023-02-03 08:47 UTC, dskloetd requested changes

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: findProposal = async () => {
Do you need to update the whole function?
Won't it reference the current value of strategy regardless?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: strategy = isSignedIn($authStore.identity) ? "query_and_update" : "query";
Do you need to have a constantly updating strategy variable as opposed to determining the appropriate strategy when making the loadProposal call?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/lib/pages/NnsProposals.svelte
> +    // We do not want to fetch the proposals twice when the component is mounting because the filter subscriber will emit a first value
Did you mean to move this code?
For what purpose?
Is it related to the strategy change?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/lib/services/$public/proposals.services.ts
> +  strategy?: QueryAndUpdateStrategy;
Do you sometimes not pass the strategy or could it just as well be required?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/tests/lib/services/_public/proposals.services.spec.ts
> +      await expect(call).resolves;
How does this verify that listProposals didn't do an update call?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +  afterEach(() => {
I think it's safer to use beforeEach.

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +      neuronsStore.reset();
Why not reset the neuronsStore at the top level?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +/**
NnsProposalDetail isn't new. Was it not tested before?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +      expect(queryByTestId("voting-confirmation-toolbar")).toBeInTheDocument();
Also expect that there isn't a login button?

2023-02-03 08:47 UTC, dskloetd commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +      expect(queryByTestId("login-button")).toBeInTheDocument();
Is there also something that shouldn't be in the page that you can verify is indeed not there?

2023-02-03 09:00 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +      neuronsStore.reset();
Sounds good

2023-02-03 09:01 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +      expect(queryByTestId("voting-confirmation-toolbar")).toBeInTheDocument();
This is the element instead of the button, but I can add that test also.

2023-02-03 09:01 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +      expect(queryByTestId("login-button")).toBeInTheDocument();
yes, the `voting-confirmation-toolbar`, I'll add it

2023-02-03 09:06 UTC, lmuntaner commented on frontend/src/lib/pages/NnsProposalDetail.svelte
> +  $: findProposal = async () => {
If you use `const` not.

This is outdated anyway, the strategy is not set in the page, but it's always `query` for not logged in users.

2023-02-03 09:06 UTC, lmuntaner commented on frontend/src/lib/pages/NnsProposals.svelte
> +    // We do not want to fetch the proposals twice when the component is mounting because the filter subscriber will emit a first value
Reverted.

2023-02-03 09:06 UTC, lmuntaner commented on frontend/src/lib/services/$public/proposals.services.ts
> +  strategy?: QueryAndUpdateStrategy;
Reverted

2023-02-03 09:06 UTC, lmuntaner commented on frontend/src/tests/lib/services/_public/proposals.services.spec.ts
> +      await expect(call).resolves;
reverted

2023-02-03 09:07 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +  afterEach(() => {
done

2023-02-03 09:08 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +/**
It was tested mocking stores and services.

The tests in `workflows` are tests for page level components where we only mock the api layer.

I started adding one before christmas and haven't added any more.

I believe these are the kind of tests you were expecting from the beginning.

2023-02-03 09:09 UTC, lmuntaner commented
@dskloetd ready for another review

2023-02-03 10:20 UTC, dskloetd requested changes
Probably not for this PR but I don't understand why we have a function called `queryAndUpdate` which might then only query or only update based on a parameter.
Why not call just `query` if you don't want `queryAndUpdate` to actually query **and** update?

2023-02-03 10:20 UTC, dskloetd commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +          run({ identity: undefined });
Is this what causes the user to be not logged in in this test?
Where is the equivalent that makes the user logged in in the previous test?
If it's implicit/default, I recommend making it explicit since it's essential for the test.
At my previous team we had a rule that we only rely on default values in a test, if the test doesn't care about those values. But if a value is important to the test, we set it explicitly, even if it's the same as the default value.
That makes the test easier to read because you don't need to lookup or memorize the default values to know the initial state of the test.
And it makes the test more robust against changes of the default values.
What do you think?

2023-02-03 10:20 UTC, dskloetd commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Can you explain this change?

2023-02-03 10:20 UTC, dskloetd commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
It doesn't seem right that you can pass in a strategy and it will just be ignored in certain cases. Should the parameter be something else like a `boolean alwaysQuery` or something?

2023-02-03 11:59 UTC, lmuntaner commented
> Probably not for this PR but I don't understand why we have a function called `queryAndUpdate` which might then only query or only update based on a parameter. Why not call just `query` if you don't want `queryAndUpdate` to actually query **and** update?

This way we can reuse the same code for different strategies.

In this case, we reuse the same code to query proposals when logged in (query + update) and when not logged in (query).

It's nicer than to have different services that share everything but the type of call.

2023-02-03 11:59 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Yes, I'll add a comment.

2023-02-03 12:02 UTC, lmuntaner commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
That's what I had, but since we agreed that we want to always use query for not logged in users this was the easiest way.

https://dfinity.slack.com/archives/C03HZERHBT3/p1675411741726609

2023-02-03 12:04 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +          run({ identity: undefined });
In the previoous one we also set it:

```
jest
        .spyOn(authStore, "subscribe")
        .mockImplementation(mockAuthStoreSubscribe);
```

Actually, I created a helper for this one, I'll change it.

2023-02-03 12:07 UTC, lmuntaner commented on frontend/src/tests/workflows/NnsProposalDetail.spec.ts
> +          run({ identity: undefined });
In general, I agree we should not rely on default values. We try that, but it's not a written rule, nor an enforced one.

There are some contexts that are set for all tests and it's not very clear. Specifically the authoStore and identity ones.

2023-02-03 12:08 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Done:

```
      // If the user is not logged in, only a query is done.
      // Therefore, we want to show an error even if the error doesn't come from a certified call.
```

2023-02-03 12:18 UTC, mstrasinskis approved these changes
LGTM, thanks! Optional improvement suggestion.

2023-02-03 12:18 UTC, mstrasinskis commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
nth: not having the default value in arguments `strategy = "query_and_update"` but apply this logic only if it's `undefined` and only then use `query_and_update` if not set. Currently this parameter is not heavily used, just to avoid future surprises. Not a strong opinion since it's a temporary solution ;)

2023-02-03 14:03 UTC, lmuntaner commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
I like the idea!

So that the default is not `query_and_update` but it depends on the identity.

I'll also add in the comments that for anonymous identity, only the `query` strategy is "allowed"

2023-02-03 14:19 UTC, dskloetd requested changes

2023-02-03 14:19 UTC, dskloetd commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Ah, ok. So if we do a query and an update, and the query fails, we don't care because the update might succeed?

Can we more explicitly only skip showing the error if it's for the query and there is also an update? For example, right now if you would pass strategy="query", you would not see the error, right?

2023-02-03 14:19 UTC, dskloetd commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
Instead of a comment, can we make the method actually fail with an assertion if you use "query and update" while not logged in?

2023-02-03 14:25 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
No, you would not, but you are the one adding this error handler and the one setting the strategy.

This error handler is coupled with the strategy used here.

2023-02-03 14:29 UTC, lmuntaner commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
Yes, that's also a good idea.

2023-02-03 14:42 UTC, lmuntaner commented on frontend/src/lib/services/utils.services.ts
> +  const currentStrategy = identity.getPrincipal().isAnonymous()
done

2023-02-03 15:08 UTC, dskloetd commented on frontend/src/lib/services/utils.services.ts
> + * If the user is not authenticated, the strategy is ignored and only QUERY is used.
This is no longer the behavior, right?

2023-02-03 15:35 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
no, the error handler is optional

2023-02-03 15:41 UTC, dskloetd commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Do we only need this logic (not showing the error for the first query if there is a second query) for loadSnsNervousSystemFunctions and not in general?

2023-02-03 15:47 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
That's a good point. I caught this because one test failed. But other services might not have the test for failing and that's why I didn't see it.

Yes, ideally, yes.

2023-02-03 16:08 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Done.

I didn't add tests for each of those though. This would increase the size of the PR even more.

2023-02-03 16:27 UTC, merged

2023-02-06 06:52 UTC, dskloetd commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
Did you make a note to add the missing tests?

2023-02-06 07:46 UTC, lmuntaner commented on frontend/src/lib/services/$public/sns.services.ts
> +      if (certified || identity.getPrincipal().isAnonymous()) {
I did now: https://dfinity.atlassian.net/jira/software/c/projects/GIX/boards/182

Thanks!