Use real toasts store in neurons service test.
dfinity/nns-dapp pull request #1815
Opened 2023-02-03 12:35 UTC by dskloetd

# Motivation

There is no need to mock light weight objects like Svelte stores.
This change demonstrates using the real toasts store in neurons.services.spec.ts instead of mocking it.

# Changes

Don't mock `$lib/stores/toasts.store` but instead let the neurons service put messages in the real store.
Subscribe to the store and have tests check the actual messages in the store.
Additionally we expect specific strings instead of just expecting there to be a toast.
Note that all expected toasts are error toasts even though the code uses a mix or toastsShow and toastsError to produce them.

# Tests

only tests

2023-02-03 14:07 UTC, lmuntaner approved these changes
I like it!

2023-02-03 15:13 UTC, dskloetd commented
Can you comment on line 522 and 816?

2023-02-03 15:39 UTC, lmuntaner requested changes
I requested a change.

I'm sorry for this, I should take more time to review and do it more thoroughly.

2023-02-03 15:39 UTC, lmuntaner commented on frontend/src/tests/lib/services/neurons.services.spec.ts
> +      expectToastError("minimum of 1 ICP");
Actually, thinking about it, it would be better to import the translations.

For example:

```
import en from "../../../mocks/i18n.mock";

//...
expect(button?.innerHTML).toEqual(en.core.continue);
```

2023-02-03 16:16 UTC, lmuntaner commented on frontend/src/tests/lib/services/neurons.services.spec.ts
> +      // Is this really the right error for this situation??
No, definitely not.

I'm guessing that the `setAccountIdentity` didn't work setting the identity for the call.

2023-02-03 16:17 UTC, lmuntaner commented on frontend/src/tests/lib/services/neurons.services.spec.ts
> +      // Is this really the right error for this situation??
No, same as before `setAccountIdentity` didn't do what intended.

2023-02-06 16:07 UTC, lmuntaner commented on frontend/src/tests/lib/services/neurons.services.spec.ts
> +      expectToastError("minimum of 1 ICP");
Yes, that sounds good, thanks!

2023-02-06 16:07 UTC, lmuntaner approved these changes

2023-02-06 18:40 UTC, merged