GIX-1335: Fix npm vulnerability
dfinity/nns-dapp pull request #1927
Opened 2023-02-22 06:14 UTC by lmuntaner

# Motivation

`npm audit` found vulenrabilities and security requested to fix them.

# Changes

* Upgrade sveltekit.
* Change the build script. There is no need to create a custom start script.
* Add ".mjs" to the list of file extensions where the backends sets the "Content-Type" header.

# Tests

Only build step is changed.

2023-02-22 06:15 UTC, lmuntaner commented
@peterpeterparker please review

I deployed it to https://q4eej-kyaaa-aaaaa-aaaha-cai.medium06.testnet.dfinity.network/

I tried it with Safari, Firefox and Chrome.

Do you see a reason why it could work in testnet but not in production?

2023-02-22 06:47 UTC, peterpeterparker requested changes
We need `strict-dynamic` for security reason

strict-dynamic > npm warning

2023-02-22 10:45 UTC, lmuntaner commented
@peterpeterparker ready for next review

2023-02-23 06:04 UTC, peterpeterparker commented
All the cool parts of this PR #1934 have been duplicated in PR #1934 which also bumps other dev dependencies and attach preload link after load. That's why I close this PR in favor of the other but great stuffs, the `window` part to be added to the script is notably pretty clever 👍

2023-02-23 06:04 UTC, closed without merging

2023-02-23 06:47 UTC, peterpeterparker commented
Also copied the headers `"mjs" => Some("application/javascript"),` in the other PR 👍

2023-02-23 08:49 UTC, lmuntaner commented
> All the cool parts of this PR #1934 have been duplicated in PR #1934 which also bumps other dev dependencies and attach preload link after load. That's why I close this PR in favor of the other but great stuffs, the `window` part to be added to the script is notably pretty clever 👍

Thanks!!