GIX-1357 Show "high load" message after ~1 minute but keep retrying
dfinity/nns-dapp pull request #1977
Opened 2023-02-28 14:22 UTC by dskloetd

# Motivation

We decide, when we keep retrying requests, to show a message after ~1 minute to indicate that there is high load.

# Changes

After a failure if at least 1 minute has passed, show a toast indicating high load.
Because of exponential backoff, this will probably happen after 62 seconds (2 + 4 + 8 + 16 + 32) + the time it took for those 6 requests to fail.

# Tests

Added tests to `src/tests/lib/utils/utils.spec.ts`.
Tested manually on testnet with smaller timeout and hardcoded error.

2023-02-28 15:17 UTC, lmuntaner requested changes
Suggested another interface.

Let me know what you think.

2023-02-28 15:17 UTC, lmuntaner commented on frontend/src/lib/utils/utils.ts
> +  showHighLoadMessage = true,
How about if we use `millisBeforeHighLoadMessage`? We don't have a default value.

* `undefined` then no message
* `number` then message

2023-02-28 15:17 UTC, lmuntaner commented on frontend/src/tests/lib/utils/utils.spec.ts
> +      const advanceTime = async (): Promise<void> => {
Not sure that will be sufficient in my issue of the `pollAccounts`

2023-02-28 15:32 UTC, dskloetd commented on frontend/src/lib/utils/utils.ts
> +  showHighLoadMessage = true,
The boolean is needed in the recursion to make sure we only show it once. Or are you proposing to use null for that as well? Then we need to add an explicit value to all callers, no?

2023-02-28 15:33 UTC, dskloetd commented on frontend/src/tests/lib/utils/utils.spec.ts
> +      const advanceTime = async (): Promise<void> => {
Don't worry about it now. We'll factor out later if possible. OK?

2023-02-28 15:46 UTC, lmuntaner commented on frontend/src/lib/utils/utils.ts
> +  showHighLoadMessage = true,
Why can't you set it to `undefined`?

2023-02-28 15:46 UTC, lmuntaner commented on frontend/src/tests/lib/utils/utils.spec.ts
> +      const advanceTime = async (): Promise<void> => {
yes, sounds good.

2023-02-28 17:32 UTC, dskloetd commented on frontend/src/lib/utils/utils.ts
> +  showHighLoadMessage = true,
I rewrote it to be a for-loop instead of recursion, so we don't need any additional parameters for recursion.
I made it count failures instead of millis before the "high load" message.
I made it not default.

2023-02-28 17:45 UTC, lmuntaner requested changes
I'd rather use `===` always, unless you have a strong reasone not to.

2023-02-28 17:45 UTC, lmuntaner commented on frontend/src/lib/utils/utils.ts
> +        counter == failuresBeforeHighLoadMessage
why `==` instead of `===`?

2023-02-28 17:45 UTC, lmuntaner commented on frontend/src/lib/services/sns-sale.services.ts
> +    failuresBeforeHighLoadMessage: 6,
Maybe add a constant for this `6`

2023-02-28 18:11 UTC, dskloetd commented on frontend/src/lib/utils/utils.ts
> +        counter == failuresBeforeHighLoadMessage
Because there's no lint check. I've changed it to ===.

2023-02-28 18:11 UTC, dskloetd commented on frontend/src/lib/services/sns-sale.services.ts
> +    failuresBeforeHighLoadMessage: 6,
Done

2023-03-01 06:50 UTC, lmuntaner approved these changes
Thanks!

2023-03-01 07:16 UTC, merged