Factor out build
dfinity/nns-dapp pull request #2640
Opened 2023-06-05 13:03 UTC by bitdivine

# Motivation

# Changes

# Tests

2023-06-05 13:42 UTC, bitdivine commented on .github/actions/build_nns_dapp/action.yaml
This is what I would like to propose as the standard build.  I believe it covers all cases apart from populating the docker cache.

2023-06-05 13:42 UTC, bitdivine commented on .github/workflows/aggregator.yaml
A standard replacement.

2023-06-05 13:42 UTC, bitdivine commented on .github/workflows/build.yml
A standard replacement, except that the location of the out dir also needs to be changed.  Note that the dir is _not_ included in the uploaded artefact.

2023-06-05 13:42 UTC, bitdivine commented on .github/workflows/build.yml
> +            DFX_NETWORK=local
As the standard build uses mainnet as the target, to compare we need to build for local.

2023-06-05 13:42 UTC, bitdivine commented on .github/workflows/docker-build.yaml
This workflow used to have a matrix to build for different networks.  Now we build the wasm for all networks in one go, so the matrix is not needed.

2023-06-05 13:42 UTC, bitdivine commented on .github/workflows/nightly.yaml
A standard replacement.  I have added the step of recording the git log head in the standard build.

2023-06-05 13:44 UTC, bitdivine commented on .github/actions/build_nns_dapp/action.yaml
This is what I would like to propose as the standard build. I believe it covers all cases apart from populating the docker cache.

2023-06-05 13:44 UTC, bitdivine commented on .github/workflows/aggregator.yaml
A standard replacement.

2023-06-05 13:44 UTC, bitdivine commented on .github/workflows/docker-build.yaml
This workflow used to have a matrix to build for different networks. Now we build one wasm for all networks, so the matrix is not needed.

2023-06-05 13:44 UTC, bitdivine commented on .github/workflows/nightly.yaml
A standard replacement. I have added the step of recording the git log head in the standard build.

2023-06-05 14:50 UTC, bitdivine commented on .github/actions/build_nns_dapp/action.yaml
> +        DFX_NETWORK=local ./config.sh && cp nns-dapp-arg-local.did out && didc encode "$(cat out/nns-dapp-arg-local.did)" | xxd -r -p >out/nns-dapp-arg-local.bin
Note: I would prefer to create these arguments in docker, however the main goal of this PR is to establish a single standardized build, not to polish that standardized build, so I have implemented the simplest thing possible here.

2023-06-06 06:11 UTC, dskloetd approved these changes

2023-06-06 06:11 UTC, dskloetd commented on .github/actions/build_nns_dapp/action.yaml
> +        else DFX_VERSION="$(jq -r .dfx dfx.json)" sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
In other places we use the script from snsdemo (which retries for up to 8 minutes). Is there any reason we can't use that here?

2023-06-06 06:11 UTC, dskloetd commented on .github/actions/build_nns_dapp/action.yaml
> +          curl -Lf "https://github.com/dfinity/candid/releases/download/${version}/didc-linux64" | install -m 755 /dev/stdin "$USER_BIN/didc"
Don't we have a script to install `didc`?

2023-06-06 06:12 UTC, dskloetd requested changes
Actually, is this safe given that we still have https://dfinity.atlassian.net/browse/GIX-1584 ?

2023-06-06 09:45 UTC, bitdivine commented
@dskloetd - why should it not be safe?  Here the one build is a mainnet build.  Assertion: The wasm and args are identical to the wasm on main, when this PR is up to date with main.  If that assertion is true, would you be satisfied that this is safe?

2023-06-06 09:48 UTC, bitdivine commented on .github/actions/build_nns_dapp/action.yaml
> +        else DFX_VERSION="$(jq -r .dfx dfx.json)" sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
We could, afaik.  I'm not convinced it has much benefit given that we are using only one of its many options.  But I don't mind.

2023-06-07 08:32 UTC, bitdivine commented on .github/actions/build_nns_dapp/action.yaml
> +        else DFX_VERSION="$(jq -r .dfx dfx.json)" sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
Done.

2023-06-07 08:33 UTC, bitdivine commented on .github/actions/build_nns_dapp/action.yaml
> +          curl -Lf "https://github.com/dfinity/candid/releases/download/${version}/didc-linux64" | install -m 755 /dev/stdin "$USER_BIN/didc"
Done.  It does add a dependency on another repo for a one-liner but as long as it works reliably I don't mind.

2023-06-07 09:23 UTC, bitdivine commented
@dskloetd  I have copmpared the wasm hash with main.  Given that the commit is included in the metadata, it is necessary to extract the wasm before the metadata is added and compare that.  With that:

Main @ 5bf5ac78812a9cf2af599612ee49e7caea81f442
```
max@sinkpad:~/dfn/nns-dapp (53:19)$ sha256sum out/nns-dapp-nometa.wasm 
1fa88924ba2d7558ef9067cce9e56811d6ef61c7458fa57f0a9601e283ffcfda  out/nns-dapp-nometa.wasm
max@sinkpad:~/dfn/nns-dapp (53:41)$ 
```
This PR @ a2590775305f3254b18da5acfdb14b13f9929537
```
max@sinkpad:~/dfn/nns-dapp/branches/build-nns-dapp-action (9:52:22)$ sha256sum out/nns-dapp-nometa.wasm 
1fa88924ba2d7558ef9067cce9e56811d6ef61c7458fa57f0a9601e283ffcfda  out/nns-dapp-nometa.wasm
max@sinkpad:~/dfn/nns-dapp/branches/build-nns-dapp-action (9:55:35)$ 
```

2023-06-07 13:03 UTC, dskloetd commented on .github/workflows/build.yml
> +          snsdemo_ref: '0e61f618018db099a01b1686535fff8eff980d1c'
Can we limit the scope of the PR and not also upgrade to a different dfx version at the same time?
Also, the snapshot on the line below won't work with the new version, right?

2023-06-13 01:33 UTC, bitdivine commented on .github/workflows/aggregator.yaml
> +        uses: ./.github/actions/build_nns_dapp
The docker build builds both.

2023-06-13 01:54 UTC, bitdivine commented on .github/workflows/build.yml
> +          snsdemo_ref: '0e61f618018db099a01b1686535fff8eff980d1c'
dfx has already been bumped in both `nns-dapp` and `sns_demo`.  But, sure, the snapshot could be bumped in another PR.  Here: https://github.com/dfinity/nns-dapp/pull/2680

If the snapshot doesn't work, CI will fail.

2023-06-13 07:09 UTC, dskloetd commented on .github/workflows/aggregator.yaml
> +        uses: ./.github/actions/build_nns_dapp
Then I think you should give the action a less misleading name.
How about naming the action `docker_build`?

2023-06-16 03:06 UTC, bitdivine commented
Bump. @dskloetd

2023-06-16 06:34 UTC, dskloetd commented on .github/workflows/aggregator.yaml
> +        uses: ./.github/actions/build_nns_dapp
This doesn't seem to be addressed.

2023-06-16 07:05 UTC, bitdivine commented on .github/workflows/aggregator.yaml
> +        uses: ./.github/actions/build_nns_dapp
I think that building the assets is the point of the action.  How it does so is an implementation detail.  I have however clarified that nns-dapp refers to the repo, not the canister.

2023-06-16 07:22 UTC, dskloetd commented on .github/workflows/build.yml
> +        uses: ./.github/actions/build_nns_dapp
If you must insist on keeping the confusing name of this action, please add a comment here:
```
# .github/actions/build_nns_dapp builds all the assets, including the sns_aggregator.
```

2023-06-16 07:33 UTC, bitdivine commented on .github/workflows/build.yml
> +        uses: ./.github/actions/build_nns_dapp
The action includes that information in the description. There is no need to duplicate it.

2023-06-16 07:36 UTC, bitdivine commented on .github/workflows/build.yml
> +        uses: ./.github/actions/build_nns_dapp
I have clarified the meaning of nns-dapp in the step title, though.

2023-06-16 07:49 UTC, dskloetd commented on .github/workflows/build.yml
> +        uses: ./.github/actions/build_nns_dapp
Please add the comment.

2023-06-16 11:56 UTC, bitdivine commented on .github/workflows/build.yml
> +        uses: ./.github/actions/build_nns_dapp
Thank you for your opinion on this but I do not believe that it is appropriate or maintainable.  There is one action, it is documented.  The documentation should not be repeated with every one of the calls.

2023-06-17 03:29 UTC, merged