Update CI workflow name used by ci-link
dfinity/nns-dapp pull request #2783
Opened 2023-06-28 16:36 UTC by dskloetd

# Motivation

https://github.com/dfinity/nns-dapp/pull/2744 changed workflow names.
`scripts/nns-dapp/ci-link` expects there to be a workflow named "Docker build" but it no longer exists.

# Changes

Change `scripts/nns-dapp/ci-link` to use `scripts/nns-dapp/get-ci-build-run` which is tested.
The only difference is that `ci-link` used to output multiple links and now only 1.
But the only place where it's used, it was followed by `tail -n 1` so this fine.

# Tests

None, but now most of the work is done by `scripts/nns-dapp/get-ci-build-run`, which is used by `scripts/nns-dapp/download-ci-wasm` and thus tested here: https://github.com/dfinity/nns-dapp/blob/75936135f738040a3cdfeec73d626cb4e3b9eb46/.github/workflows/checks.yml#L271

# Todos

- [ ] Add entry to changelog (if necessary).

2023-06-29 12:10 UTC, bitdivine requested changes

2023-06-29 12:10 UTC, bitdivine commented on scripts/nns-dapp/ci-link
> +echo "https://github.com/dfinity/nns-dapp/actions/runs/$ci_build_run_id"
This command is used to find _all_ builds of the current commit so that they can be checked for consistency.  The code on the right does not do this.  You probably need to update `get-ci-build-run` to emit all hits.

2023-06-29 12:10 UTC, bitdivine commented on scripts/nns-dapp/release-template
> +  CI="$("$SOURCE_DIR/nns-dapp/ci-link" --commit tags/release-candidate | grep .)"
ci-link can emit multiple lines, so the tail is still needed.

2023-06-29 12:14 UTC, dskloetd commented on scripts/nns-dapp/ci-link
> +echo "https://github.com/dfinity/nns-dapp/actions/runs/$ci_build_run_id"
In the PR description I wrote:
> The only difference is that ci-link used to output multiple links and now only 1.
> But the only place where it's used, it was followed by tail -n 1 so this fine.

Do you disagree with this?

2023-06-29 13:51 UTC, dskloetd commented on scripts/nns-dapp/ci-link
> +echo "https://github.com/dfinity/nns-dapp/actions/runs/$ci_build_run_id"
In person: Max uses the script manually and likes that it outputs multiple links.

2023-06-29 16:01 UTC, dskloetd commented on scripts/nns-dapp/ci-link
> +echo "https://github.com/dfinity/nns-dapp/actions/runs/$ci_build_run_id"
I added `--all` flag to `get-ci-build-run` and used it here so it output all links again.

2023-06-30 11:30 UTC, bitdivine approved these changes
LGTM.  Thank you.

2023-06-30 12:25 UTC, dskloetd commented on scripts/nns-dapp/ci-link
> +ci_build_run_ids="$("$SOURCE_DIR/nns-dapp/get-ci-build-run" --commit "$DFX_COMMIT" --limit "$DFX_LIMIT" --all)"
Done

2023-06-30 12:33 UTC, merged