Disburse maturity button
dfinity/nns-dapp pull request #3076
Opened 2023-08-10 10:42 UTC by mstrasinskis

# Motivation

Add SnsDisburseMaturityButton to the neuron settings page.

# Changes

- rename `hasEnoughMaturityToStake` to `hasEnoughMaturityToStakeOrDisburse`
- new `ENABLE_DISBURSE_MATURITY` flag
- `DisburseMaturityButton` component
- `SnsDisburseMaturityButton` component
- hasPermissionToDisburseMaturity

# Tests

- `hasPermissionToDisburseMaturity`
- `DisburseMaturityButton`
- `SnsDisburseMaturityButton`

<img width="711" alt="image" src="https://github.com/dfinity/nns-dapp/assets/98811342/14ee5888-c52c-400e-a8e8-cda0cdc70fcc">

# Todos

Part of the Disburse Maturity feature. Doesn't need to be mentioned.
- [ ] Add entry to changelog (if necessary).

2023-08-10 10:52 UTC, lmuntaner requested changes
A few comments. Thanks!

2023-08-10 10:52 UTC, lmuntaner commented on dfx.json
> +          "ENABLE_DISBURSE_MATURITY": false
I would have preferred to have a PR with only the feature flag.

2023-08-10 10:52 UTC, lmuntaner commented on frontend/src/lib/components/neuron-detail/actions/DisburseMaturityButton.svelte
> +  export let variant: "primary" | "secondary" = "primary";
Why the variant?

I added the variant in the others because they were used also in the old UI.

But we don't need to support Disburse Maturity in the old UI.

2023-08-10 10:52 UTC, lmuntaner commented on frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.svelte
> +    <SnsDisburseMaturityButton variant="secondary" />
Can you add a test for this?

```
it("renders disburse button if user is allowed to disburse maturity")
it("doesn't render disburse button if flag is false")
it("doesn't render disburse button if user is not allowed to disburse maturity")
```

2023-08-10 10:52 UTC, lmuntaner commented on frontend/src/tests/lib/components/neuron-detail/actions/DisburseMaturityButton.spec.ts
> +  afterEach(() => {
We said to always use `beforeEach`.

2023-08-10 10:52 UTC, lmuntaner commented on frontend/src/tests/lib/components/neuron-detail/actions/DisburseMaturityButton.spec.ts
> +    const { getByText } = render(DisburseMaturityButton, {
This is a new component, could you create a page object for this?

2023-08-10 10:52 UTC, lmuntaner commented on frontend/src/tests/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.spec.ts
> +    const { getByTestId } = render(SnsNeuronContextTest, {
Ditto to create a page object for this new component.

2023-08-10 12:27 UTC, mstrasinskis commented on dfx.json
> +          "ENABLE_DISBURSE_MATURITY": false
Makes sense. Here it is - https://github.com/dfinity/nns-dapp/pull/3078

2023-08-10 16:02 UTC, mstrasinskis commented on frontend/src/lib/components/sns-neuron-detail/SnsAvailableMaturityItemAction.svelte
> +    <SnsDisburseMaturityButton variant="secondary" />
Good point, SnsAvailableMaturityItemAction.spec was extended..

2023-08-10 16:02 UTC, mstrasinskis commented on frontend/src/tests/lib/components/neuron-detail/actions/DisburseMaturityButton.spec.ts
> +    const { getByText } = render(DisburseMaturityButton, {
Right, done.

2023-08-10 16:08 UTC, lmuntaner commented on frontend/src/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.svelte
> +<TestIdWrapper testId="sns-disburse-maturity-button-component">
You can use the PO of `DisburseMaturityButton` instead of having to create another one.

Take a look at:
 * StakeItemAction.page-object.ts
 * NnsStakeItemAction.svelte
 * NnsStakeItemAction.spec.ts

No need to be one component one PO if the component is directly another one.

2023-08-11 08:03 UTC, mstrasinskis commented on frontend/src/lib/components/sns-neuron-detail/actions/SnsDisburseMaturityButton.svelte
> +<TestIdWrapper testId="sns-disburse-maturity-button-component">
Initially I was also not sure about creation so empty po :)
Thanks for the explanation.

2023-08-11 08:03 UTC, mstrasinskis commented on frontend/src/tests/lib/components/neuron-detail/actions/DisburseMaturityButton.spec.ts
> +    const { container } = render(DisburseMaturityButton, {
Good point, done.

2023-08-11 08:06 UTC, mstrasinskis commented
@lmuntaner another one?

2023-08-11 09:43 UTC, merged