Chore: Use new sns project test util
dfinity/nns-dapp pull request #3079
Opened 2023-08-10 13:18 UTC by lmuntaner

# Motivation

Final motivation: Stop using get_state. But on the way, clean the unnecessary complexity of snsQueryStore.

In this PR: Use the new test util `setSnsProjects` in more tests.

# Changes

* Move from `snsQueryStore.setData` to `setSnsProjects` in some test files.

# Tests

Only test changes.

# Todos

Already covered by a changelog entry.

2023-08-10 13:55 UTC, dskloetd approved these changes

2023-08-10 13:55 UTC, dskloetd commented on frontend/src/tests/lib/derived/sns/sns-total-supply-token-amount.derived.spec.ts
> +      { rootCanisterId: principal(0), lifecycle: SnsSwapLifecycle.Committed },
Suggestion:
If `rootCanisterId` is not set on the param, `setSnsProjects` could default it to `principal(i)`.

2023-08-10 14:23 UTC, lmuntaner commented on frontend/src/tests/lib/derived/sns/sns-total-supply-token-amount.derived.spec.ts
> +      { rootCanisterId: principal(0), lifecycle: SnsSwapLifecycle.Committed },
It makes sense. But lifecycle I would still leave as mandatory.

2023-08-10 14:30 UTC, dskloetd requested changes

2023-08-10 14:48 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
ah, yes, true. Otherwise all sns will have same root canister id

2023-08-10 14:49 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
We only have 5 principals. Should we raise if we try to create more than 5 SNSes?

or just if there are more without root canister id?

2023-08-10 14:51 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
```
  if (
    params.filter(({ rootCanisterId }) => isNullish(rootCanisterId)).length > 5
  ) {
    throw new Error("Too many projects without canister id.");
  }
```

Not perfect, but I believe is enough. We will either use it setting always the root canister id or never. I don't think we'll mix

2023-08-10 15:09 UTC, lmuntaner commented on frontend/src/tests/lib/derived/sns/sns-total-supply-token-amount.derived.spec.ts
> +      { rootCanisterId: principal(0), lifecycle: SnsSwapLifecycle.Committed },
It wasn't there because the root canister ids were read after creating the mock data:

```
const rootCanisterIds = responses[0].map(({ rootCanisterId }) =>
      Principal.fromText(rootCanisterId)
    );
```

I still do that:

```
    const rootCanisterIds = projectsParams.map(
      ({ rootCanisterId }) => rootCanisterId
    );
```

2023-08-10 15:56 UTC, dskloetd approved these changes

2023-08-10 15:56 UTC, dskloetd commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
Yeah, this is fine.
Although I wonder if it needs to be these specific principals because otherwise you could also do
```
Principal.fromHex(index.toString(16))
```
instead of
```
principal(index)
```
and it would generate as many as you want.
I was actually assuming that's what it did.

2023-08-10 15:56 UTC, dskloetd commented on frontend/src/tests/lib/derived/sns/sns-total-supply-token-amount.derived.spec.ts
> +      { rootCanisterId: principal(0), lifecycle: SnsSwapLifecycle.Committed },
I see. You're right. My bad.

2023-08-10 19:28 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
No, they are 5 hardcoded principals. That's it.

2023-08-10 19:38 UTC, merged

2023-08-11 06:05 UTC, dskloetd commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
Yeah, I realize that now. But do we have to use those? Or can we use any (generated) principal just fine?

2023-08-11 06:18 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
We can use those fine, yes. They are used in other tests.

Let me ask how can we create principals for testing. Maybe there is an easy way.

2023-08-11 06:26 UTC, dskloetd commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
You don't find this easy? `Principal.fromHex(index.toString(16))`

2023-08-11 07:12 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
This doesn't work:

```
const principal = Principal.fromHex(index.toString("hex"));
```

But this works

```
const principal = Principal.fromUint8Array(new Uint8Array([index]));
```

2023-08-11 07:17 UTC, dskloetd commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
> This doesn't work:
> `const principal = Principal.fromHex(index.toString("hex"));`

That's not what I wrote. I wrote `Principal.fromHex(index.toString(16))`.
And we already use that here: https://github.com/dfinity/nns-dapp/blob/07a8e1b19be6003d8eb35f18ed9946ac78762699/frontend/src/tests/mocks/auth.store.mock.ts#L17
So it definitely creates a `Principal`.
The only thing I don't know is if we need a special principal but based on what you say works, I don't think so.

2023-08-11 07:17 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
Ah, it's `toString(16)`, not `"hext"`

2023-08-11 07:20 UTC, lmuntaner commented on frontend/src/tests/utils/sns.test-utils.ts
> +        principal: rootCanisterId ?? principal(0),
Why did I read `"hex"`???!!