Script to deploy from CI artefact
dfinity/nns-dapp pull request #364
Opened 2022-01-18 14:53 UTC by bitdivine

# Motivation
People wish to deploy to a testnet for reasons including, but not limited to:
- Not being able to build locally, due to Mac M1 chips
- Not wanting to waste time building when CI has already built a wasm file.

# Changes
- Added a script to deploy a wasm file downloaded from CI.

Note: github assets cannot be downloaded by anonymous users.  In the envisaged use case, a human user will be choosing a build artifact so they might as well click "Download" while they are about it.

2022-01-18 15:04 UTC, nmattia reviewed
The script isn't very robust (relies on specific paths and things like the unfortunate `DEPLOY_ENV`) and requires manual interaction anyway. I think a list of steps to run would be much better

2022-01-18 15:04 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +TMPDIR="$(mktemp -d)"
Use [`TMPDIR`](https://en.wikipedia.org/wiki/TMPDIR) as a var name is probably not a good idea

2022-01-18 16:20 UTC, bitdivine commented on scripts/deploy-ci-to-testnet
> +TMPDIR="$(mktemp -d)"
I can namespace it, although that dir is the tmpdir for everything in this script.  Do you have a specific example of what might go wrong?

2022-01-18 16:54 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +TMPDIR="$(mktemp -d)"
Better thanks! `TMPDIR` may be `export`ed by default and is the filesystem's default temporary directory. Tools that you use here (like `unzip`, etc) may read that and use the directory for their own, private temporary files

2022-01-19 09:28 UTC, bitdivine commented on scripts/deploy-ci-to-testnet
> +TMPDIR="$(mktemp -d)"
Exactly, default is the key and it is standard practice, indeed required, to override TMPDIR when one wants a program to put its tmp files in a different location.  So when that is the intention, that is correct.  Here it does't really matter either way but I fail to see what would be wrong if we really wanted all the tmpfiles to be in this directory, not just the wasm artifact.

2022-01-19 10:02 UTC, bitdivine commented
Regarding DEPLOY_ENV - that is the canonical way, and indeed the only way, of deploying this repo without building.  That can be changed, perhaps, but that is not the subject of this PR so it would be inappropriate to address it here.

2022-01-20 09:12 UTC, nmattia approved these changes
I think there are a few things that are not ideal:
* The dockerfile changes look good (module the potential issue with `dfx` not finding the canister) but I don't think this is the right way about. We should probably invest some time (not much I reckon) getting rid of this `DEPLOY_ENV` and make it a post-build config parameter.
* I am not sure the `deploy-ci-to-testnet` script is all that useful. It requires manual interaction, relies on artefacts that in general are GCed after a week, and basically just unzips a downloaded file. If we wanted something like this I'd rather push actual releases to GitHub and have no manual step.

All that being said, still gonna rubber stamp this and will probably fix it later on

2022-01-20 09:12 UTC, nmattia commented on .github/workflows/docker-build.yaml
> +         - DEPLOY_ENV: "testnet"
I doubt this will work since `dfx` will try to look up the canister ID (which hasn't been created in the docker image)

2022-01-20 09:12 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +rm -fr "${UNZIP_TMPDIR:-this-is-not-the-dir-you-are-looking-for}"
How could `UNZIP_TMPDIR` not be set? i.e. when would we `rf -fr this-is-not...`?

2022-01-20 09:12 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +set +x
I don't see a `set -x`, what does this do?

2022-01-20 09:41 UTC, bitdivine commented on .github/workflows/docker-build.yaml
> +         - DEPLOY_ENV: "testnet"
It won't - this needs the canister_ids.json mentioned.  There is no canister-ds.json commited in the repo so that developers don't clobber each other's work, and canister_ids.json is in the gitignore.  There used to be a canister_ids.json committe din git but that was removed, in July if I recall correctly.

What we can do is to have a `canister_ids.default.json` and use that e.g. here.  It is also useful if other testnets that just want to use nns, not develop it, use the default canister ID.  I can add that here or wait for your change.

Added here but can revert.

2022-01-20 10:14 UTC, nmattia requested changes

2022-01-20 10:14 UTC, nmattia commented on .github/workflows/docker-build.yaml
> +        run: cp canister_ids.default canister_ids.json
This is too much of a hack; let's merge https://github.com/dfinity/nns-dapp/pull/365 and then you can set `OWN_CANISTER_ID` from the Dockerfile

2022-01-20 10:45 UTC, bitdivine commented on scripts/deploy-ci-to-testnet
> +rm -fr "${UNZIP_TMPDIR:-this-is-not-the-dir-you-are-looking-for}"
When a developer tinkers with this script.  Much better to tell them that they have a bug than potentially wipe their system.  That said, I use that by habit and in this case, as there is no stem so this would reduce to `rm -fr ""` which is safe, so the additional safety mechanism isn't needed.  I'll drop it.

2022-01-20 10:45 UTC, bitdivine commented on scripts/deploy-ci-to-testnet
> +set +x
Good point.  I had a set -x but dropped it.

2022-01-20 10:45 UTC, bitdivine commented on .github/workflows/docker-build.yaml
> +         - DEPLOY_ENV: "testnet"
Switched to OWN_CANISTER_ID - please review.

2022-01-20 10:55 UTC, nmattia commented on .github/workflows/docker-build.yaml
> +         - DEPLOY_ENV: "testnet"
Thanks!

2022-01-20 11:05 UTC, nmattia approved these changes

2022-01-20 11:05 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +  DOWNLOAD_FILENAME="$(ls -t "$DOWNLOADS_DIR" | grep -E '^Testnet backend wasm module( [(][0-9]+[)])?.zip$' | head -n1)"
```suggestion
  DOWNLOAD_FILENAME="$(ls --sort=time "$DOWNLOADS_DIR" | grep -E '^Testnet backend wasm module( [(][0-9]+[)])?.zip$' | head -n1)"
```

note: not sure how posix `-t` (and `--sort`) is

2022-01-20 11:05 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +  echo "Sourcing WASM from: $DOWNLOAD_PATH"
```suggestion
```

2022-01-20 11:05 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +
```suggestion
  echo "Sourcing WASM from: $DOWNLOAD_FILENAME"
```

2022-01-20 11:05 UTC, nmattia commented on scripts/deploy-ci-to-testnet
> +mv "$UNZIP_TMPDIR/$WASM_FILENAME" "$WASM_PATH"
note: not sure about this but there's a chance this will mess with cargo (e.g. it may refuse to rebuild if the mtime of the downloaded wasm is more recent than that of the local files)

2022-01-20 11:50 UTC, merged