Fix docker build
dfinity/nns-dapp pull request #376
Opened 2022-01-25 14:27 UTC by bitdivine

# Motivation
The prod release process broke due to changes introduced for ci testing.  This PR is an attempt to find a clean solution that works for both.

Design goals:
- Simplify code.
- Have a documented algorithm for setting OWN_CANISTER_ID.
- Centralize logic, so that developers don't need to search through the codebase to try to figure out how variables are set.
  - Note: We can and probably should also set the default own_canister_id in this code block.  That requires more changes and more testing though, and right now deployments break so it would be better to add that later.

# Changes
The logic for determining OWN_CANISTER_ID implements this design:
```
# Here the OWN_CANISTER_ID is set.  The value is taken from the following, in order of priority:
# - The env var OWN_CANISTER_ID
# - canister_ids.json
# - try to deduce the value.
```

2022-01-25 15:11 UTC, nmattia requested changes

2022-01-25 15:11 UTC, nmattia commented on scripts/docker-build
> +if test -n "${OWN_CANISTER_ID:-}"
```suggestion
if [ -n "${OWN_CANISTER_ID:-}" ]
```

here and elsewhere

2022-01-25 15:11 UTC, nmattia commented on scripts/docker-build
> +then OWN_CANISTER_ID="$(jq -r '.["nns-dapp"]["'"$DEPLOY_ENV"'"]' canister_ids.json)"
I'd rather not depend on `jq` if we can avoid it, and more importantly I'd rather not depend on temporary, `dfx` created file. Why not simply read `OWN_CANISTER_ID` on line `22`? Then feel free to add as much logic as you want in `deploy-docker-build-to-testnet`.

Also it's now odd to have different heuristics for `testnet` and `local` (whereas AFAICT they both depend on whatever canister ID was created)

2022-01-25 15:11 UTC, nmattia commented on scripts/docker-build
> +if test -z "${OWN_CANISTER_ID:-}" && test -e canister_ids.json
`test -z "${OWN_CANISTER_ID:-}"`: You have the exact opposite test above (`-n`), why not add the test for `canister_ids` etc inside an else branch?

2022-01-25 15:11 UTC, nmattia commented on scripts/docker-build
> +if test -z "${OWN_CANISTER_ID:-}"
This now doesn't really make sense; why not invert the logic and add a `testnet` branch?

2022-01-25 15:32 UTC, nmattia commented
Thought: why not remove all the `DEPLOY_ENV` and `OWN_CANISTER_ID` logic from docker-build and lift this to the callers? I think it makes most sense (and then docker-build just reads the values and sets them as build-args)

2022-02-02 16:02 UTC, bitdivine commented
Getting `OWN_CANISTER_ID` from canister_ids.json requires jq.  Are you OK with requiring developers to have jq installed?

2022-02-03 09:28 UTC, nmattia commented
This isn't ideal but sure if that's the only way! Also didn't you wanna reduce the docker build to a single line `docker build` with buildx and `-o .`?

2022-02-07 19:36 UTC, bitdivine commented
Test: f15670f623d7c7f679cb408117984edd508375c3

2022-02-08 13:28 UTC, nmattia approved these changes
Unblocking, clarified offline!

2022-05-18 12:38 UTC, closed without merging