feat: Svelte neuron card
dfinity/nns-dapp pull request #391
Opened 2022-02-01 14:31 UTC by lmuntanerDfinity

# Motivation

Create the card summary of a Neuron. Just the UI with hardcoded details.

# Changes

- Changed `Card` can be clickable.
- Create `NeuronCard` component. Hard-coded information for now.
- `NeuronCard` is in `components/neurons`, in advance of [L2-217](https://dfinity.atlassian.net/browse/L2-217).
- Added two new icons: Lock with time and closed lock.

2022-02-01 14:36 UTC, lmuntanerDfinity commented
@peterpeterparker @bitdivine just my first PR to see how many things I got wrong: coding style, PR comment, missing information, ...

2022-02-01 14:46 UTC, peterpeterparker requested changes
Thanks! I'll go for a run, if we should discuss some stuffs we can have a look together in a call tomorrow :)

2022-02-01 14:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/Card.svelte
> +{#if to}
1. actually, after thinking about it and now that I see the code, I think we can / should stick to the `article` with a role

```
<article role="button" ...>
```

and apply the mixin `tappable`.

2. The card can be something else than a link aka a button. Therefor it should `dispatch` an event.

2022-02-01 14:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +<Card to="/#/neurons/one">
add a `<!-- TODO. ... -->` so that we do not forget ;)

2022-02-01 14:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +  p {
you can drop the `p {margin: 0}` it will be fixed with my open PR that set globally such margin for paragraphs

2022-02-01 14:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +  .lock {
feels like you can spare some `class` probably. style is automatically scoped so you can target for example `h3` directly. likewise with scss you can get children.

2022-02-01 14:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +<!-- <svg
should we remove the commented svg?

2022-02-01 14:46 UTC, peterpeterparker commented on frontend/svelte/src/routes/Neurons.svelte
> +<Layout>
the `{#if !process.env.REDIRECT_TO_LEGACY}` most probably should not be dropped yet?

2022-02-01 14:49 UTC, peterpeterparker commented
Forgot to mention: can you add some spec tests? like for the new card action and to check that a card is rendered in the "neurons" page

2022-02-01 14:51 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +<Card to="/#/neurons/one">
and create a ticket, and link to it :)

2022-02-02 06:11 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +<!-- <svg
oh yes!

2022-02-02 06:11 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +  class={size}
sure

2022-02-02 06:11 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Neurons.svelte
> +<Layout>
ah, ok

2022-02-02 06:31 UTC, lmuntanerDfinity commented
@peterpeterparker Did the changes, except for the Card with `role="button"`. We can talk about this one if you want.

2022-02-02 06:38 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/Card.svelte
> +{#if to}
We need `click` events when the card is use in modal (just had a look, like when you select an account in a modal) so even though `<a/>` would be semantically more correct in case of navigation, I rather like  `<article role="button" ...>` at the end because it makes the code simpler to maintain. 

Following:

```
if link
 <a... 
else if 
 <button...
else
  <article...
```

would be ok if the content of each a, button and article would not be copy/pasted (as currently in your pr) but extracted to a component (don't think you can create tag from string as you can do in jsx). also then we would have to check that `slot` can passed through two children (I never tried out yet).

what do you think?

note: events are alright,  we have functions to navigate programmatically

2022-02-02 07:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/Card.svelte
> +{#if to}
ok, let's go with the `<article role="button"`.

2022-02-02 08:01 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/Card.svelte
> +<article {role} on:click class={clickableRoles.includes(role) && "clickable"}>
@peterpeterparker what do you think?

From the [docs](https://svelte.dev/docs#template-syntax-element-directives-on-eventname):
```
If the on: directive is used without a value, the component will forward the event, meaning that a consumer of the component can listen for it.
```

I guessed it made more sense to avoid code and in the end even make it more readable when being used. `<Card on:click` looks also nice. 😄

2022-02-02 08:01 UTC, lmuntanerDfinity commented
@peterpeterparker ready for next review

2022-02-02 11:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/Card.svelte
> +<article {role} on:click class={clickableRoles.includes(role) && "clickable"}>
looks cool

2022-02-02 11:15 UTC, peterpeterparker approved these changes
LGTM, thanks!

2022-02-03 09:51 UTC, nmattia reviewed
Few comments!

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/Card.svelte
> +  // check testing for firing events
Is this comment related to the code below or is this a TODO? What is "check testing"?

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/Card.svelte
> +  export let role: string | undefined = undefined;
Is this ever not a `link`, except in the tests? Otherwise I'd rather keep things simple until we need complexity

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/Card.svelte
> +  export let role: string | undefined = undefined;
Also, I see `AccountCard` also uses the `Card`. What's its `role`? Is it OK for the `Card` to have a `role` that's `undefined`?

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/Card.svelte
> +  export let role: string | undefined = undefined;
Finally, should `role` really be a `string | undefined`? What values can it have?

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/Card.svelte
> +    display: block;
isn't this the default for `article` elements?

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    // Go to the detail page of Neuron
Is this a todo?

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    <h4>14225061177570733325</h4>
nitpick: I do wonder if semantically this should be `h4`/`h5` etc

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    display: flex;
nit: I wonder if flex isn't too big a hammer when you could probably `text-align`

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +    l: 33,
is this meant to be `33`? Looks a bit odd, I would have guessed `32`. Also, could we get away with just preserving the aspect ratio?

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +  export let size: Size = "m";
what about actually writing out the words? It took me a few second to realize those meant "small", "medium" and "large". Also, I thought `l` was a 1!

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/types/shared.ts
> +export type Size = "m" | "s" | "l";
what about actually writing out the words? It took me a few second to realize those meant "small", "medium" and "large". Also, I thought `l` was a 1!

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +  export let size: Size = "m";
Is this ever not a `small` icon? Again, I'd prefer to avoid complexity until it's needed

2022-02-03 09:51 UTC, nmattia commented on frontend/svelte/src/lib/types/i18n.d.ts
> +  sign_in: string;
Where is this used?

2022-02-03 10:35 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/Card.svelte
> +  // check testing for firing events
It can be removed, it was a WIP todo for me, sorry

2022-02-03 10:35 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    // Go to the detail page of Neuron
Yes, to be done in L2-218, same as all the others

2022-02-03 10:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +<Card role="link" on:click={goToDetail} ariaLabel="go to neuron details">
@nmattia you were asking when do we use the role. Here.

2022-02-03 10:37 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    <h4>14225061177570733325</h4>
Good question. I am also not sure. I chose h4 here because the one afterwards, Locked, could also me considered a heading, but it seems to me lower than this ID.

2022-02-03 10:37 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    display: flex;
This might change with L2-218 when I use the ICP component.

2022-02-03 10:37 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +  export let size: Size = "m";
makes sense to me

2022-02-03 10:39 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +  export let size: Size = "m";
That I know of, for now it's only small, yes. I can keep it always with 18.

I also prefer avoiding flexibility, but the svg I got from the previous project was this size, I assumed it was also used with it.

2022-02-03 10:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/icons/IconLockClock.svelte
> +    l: 33,
This is to preserve the `viewBox="0 0 32 33"`. I got this svg from the previous project.

2022-02-03 10:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/types/i18n.d.ts
> +  sign_in: string;
This was added by prettier

2022-02-03 10:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/types/shared.ts
> +export type Size = "m" | "s" | "l";
We might remove this, since we only use one size

2022-02-03 10:41 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/Card.svelte
> +    display: block;
yes, true. I think I had an anchor tag before, instead of the `role` and needed this. But not anymore.

2022-02-03 10:41 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/Card.svelte
> +  export let role: string | undefined = undefined;
I mentioned you where "role" is used.

Good point, I will change the type to allowed values

2022-02-03 10:50 UTC, lmuntanerDfinity commented
@nmattia ready for another review 😄

2022-02-04 09:30 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +<Card role="link" on:click={goToDetail} ariaLabel="go to neuron details">
Right, I was asking when this is _not_ a `link`. Is it _ever_ a `button`?

2022-02-04 09:31 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    <h4>14225061177570733325</h4>
Then I'd suggest we stick to something else, I rarely see anything beyond h3. But really this one is up to @peterpeterparker

2022-02-04 09:31 UTC, nmattia commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    <h4>14225061177570733325</h4>
(really feel free to leave as is)

2022-02-04 09:33 UTC, nmattia approved these changes
LGTM, sorry for the delay!

2022-02-04 09:43 UTC, merged

2022-02-04 09:50 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    <h4>14225061177570733325</h4>
yeah these information looks like `<p/>` to me too - i.e. not titles

something we can update when the implementation of the dynamic data will find place (L2-218)

2022-02-04 09:52 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    <h4>14225061177570733325</h4>
I will make a note on the issue to not forget about it