L2-214: Dark Modal
dfinity/nns-dapp pull request #396
Opened 2022-02-03 12:54 UTC by lmuntanerDfinity

# Motivation

Add the dark version of the modal.

# Changes

- Add `dark` prop to `Modal` component.
- Changed `Modal` title to h3. Previous Modal had different sizes for dark and light modals. Some dark modals had long titles. I changed to a midway solution. Old dark modal title was too small.

2022-02-03 12:55 UTC, lmuntanerDfinity commented
@nmattia @mstrasinskis please review

Here are the light and dark versions:

![Screenshot 2022-02-03 at 13 50 00](https://user-images.githubusercontent.com/98735375/152346803-ea78d9ca-dd0e-4dab-9276-f94324bd5af9.png)

![Screenshot 2022-02-03 at 13 50 24](https://user-images.githubusercontent.com/98735375/152346806-aed80da7-7030-4a4f-a71a-2b8a638bbd95.png)

2022-02-03 13:49 UTC, peterpeterparker requested changes

2022-02-03 13:49 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
don't get why you wrap the close button in a `div` with an `absolute` positioning?
what cannot be achieve with the current `flex` display?

2022-02-03 13:51 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
I tried, but then the button was not aligned with the title. I used this wrapper to set it the the height of the parent and then align the button in the center.

2022-02-03 13:51 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
Any idea of how to improve this?

2022-02-03 13:52 UTC, peterpeterparker commented
For accessibility reason shouldn't we define a base `color` for the content of the "dark" modal? 

In your first screenshot the content is not contrasting enough.

2022-02-03 13:54 UTC, lmuntanerDfinity commented
Good point, I designed in the way that the color is defined in the content, but good point, I can change the color of the content as well.

2022-02-03 13:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
wasn't it previously?

we can have a look next week together.

generally I like to spare dom elements specially those for styling purpose, worth a shot.

2022-02-03 14:04 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
yes, but now I wanted the title in the middle, like in the dark mode.

But the middle of the whole width, without considering of the button. Therefore, I used display: flex, and to remove the button from the normal flow, I used `position: absolute`. But `position: absolute;` pushed the button to the top.

One option was to hardcode how far from the top the button lives with just `top: XXX`. But I thought this solution is not very responsive. Therefore, I added the extra `div`, that starts at `top: 0` and height of the parent and places the contents (button) in the middle.

2022-02-03 14:28 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
a display `grid` might solve this but in the nns rewrite, we follow the design of the current app.

however if we see small improvements, we shall proceed. in this case, i see an improvement in constancy if both types of modal present the title with the same alignment. 

finally:

ios = modal title center
material design = dialog & modal title left

since we target both mobile and desktop, kind of feel we follow a style closer to material design.

that's why I suggest then to revert and keep the `space-between` aka align the title to the left in the dark modal as well.

2022-02-03 14:33 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
speaking of, I just realize the "dark" modal might contains a back button, so we might need a grid anyway 🤪

do you want to foreseen such slot in this PR or should we do this afterwards?

2022-02-03 14:33 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
And what do we do with the "back arrow", see example below:

<img width="608" alt="Screenshot 2022-02-03 at 15 32 13" src="https://user-images.githubusercontent.com/98735375/152362902-636fb786-f542-445a-909b-e440289f4c40.png">

That is not in the Material dialogs...

2022-02-03 14:34 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
I can use a grid, makes sense to me. I can do it here.

2022-02-03 14:37 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +        <div class="button-container">
Yeah would look this this in material-ich

<img width="608" alt="152362902-636fb786-f542-445a-909b-e440289f4c40" src="https://user-images.githubusercontent.com/16886711/152363658-746353cf-36f7-4b5d-8098-99d746e65d80.png">
ch

let's try grid 🤘

2022-02-03 16:15 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    display: grid;
@peterpeterparker here is the solution with grid.

I avoided using an extra DOM element by using a `margin-left` on the title to make up for the missing back button.

Not super happy, but it's the best idea I got.

2022-02-03 16:40 UTC, mstrasinskis commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    h3 {
May I ask why the headline was degraded?

2022-02-03 16:47 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    display: grid;
cool no extra dom element 👍

regarding spacing, `grid-column-start` ?

```
display: grid;
    grid-template-columns: var(--icon-width) 1fr var(--icon-width);

    h3 {
      color: inherit;
      font-weight: 400;
      margin-bottom: 0;
      line-height: 1.5;
      text-align: center;
      grid-column-start: 2;
    }
```

2022-02-03 16:48 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    display: grid;
with above `.showBackButton` can be removed too

2022-02-03 17:09 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    h3 {
The be consistent with Dark and Light modals. In the previous design, the light modal had a way bigger title than the light because in the dark some titles were longer.

To be consistent and still allow for longer titles, I think it made sense to reduce.

Do you think that semantically, a h2 is better fitted here?

2022-02-03 17:10 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    display: grid;
good point!

2022-02-03 17:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    display: grid;
@peterpeterparker change done!

2022-02-03 19:24 UTC, mstrasinskis commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    h3 {
Thank for description. Semantically I think h2 would be more preferable but it's totally not critical especially if we rebuild everything later :D

2022-02-04 06:12 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    display: grid;
cool 👍

2022-02-04 06:55 UTC, lmuntanerDfinity commented
@peterpeterparker @nmattia @mstrasinskis ready for another review

2022-02-04 09:08 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +          <button class="back" on:click|stopPropagation={back} aria-label="Back"
Done!

2022-02-04 09:09 UTC, lmuntanerDfinity commented
@peterpeterparker ready for review

2022-02-04 10:03 UTC, peterpeterparker commented
I did a try locally, looks good 👍.

However, doing so I noticed an inconsistency in the declaration of the dark property.

In this PR - in the `<Modal />`:

```
export let dark: boolean = false;
```

In the existing `<Checkbox />`:

```
export let color: "dark" | "light" = "light";
```

I think it would be good to have a consistent approach.

I kind of rather like the one of the checkbox because it feels maybe a bit more readable when used (`color="light"` vs `dark={false}`). What do you think @lmuntanerDfinity, any preferences?

2022-02-04 10:22 UTC, nmattia commented on frontend/svelte/src/lib/i18n/en.json
> +    "close": "Close",
I think we can stick to [a single close](https://github.com/dfinity/nns-dapp/blob/1d5aa2c60606a33ae29c8f39959505a8f96976e9/frontend/svelte/src/lib/i18n/en.json#L3) for now

2022-02-04 10:22 UTC, nmattia commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  export let showBackButton: boolean = false;
so someone using this modal should only ever `showBackButton=true` if they listen `on:nnsBack`? Can we add a note about this?

2022-02-04 12:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  export let showBackButton: boolean = false;
Another option is to use a callback: "onBack" for example. I can check for the presence of that and show/hide the arrow.

But the callback is not the pattern you are using now.

Where else do you propose to add a note? That's why I added the comment here.

2022-02-04 12:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/i18n/en.json
> +    "close": "Close",
👍

2022-02-04 12:51 UTC, lmuntanerDfinity commented
> I did a try locally, looks good 👍.
> 
> However, doing so I noticed an inconsistency in the declaration of the dark property.
> 
> In this PR - in the `<Modal />`:
> 
> ```
> export let dark: boolean = false;
> ```
> 
> In the existing `<Checkbox />`:
> 
> ```
> export let color: "dark" | "light" = "light";
> ```
> 
> I think it would be good to have a consistent approach.
> 
> I kind of rather like the one of the checkbox because it feels maybe a bit more readable when used (`color="light"` vs `dark={false}`). What do you think @lmuntanerDfinity, any preferences?

I don't have a strong opinion on the pattern.

But yes, for the name of the prop. I'd rather call it "theme" than "color". Is that ok?

I can rename Checkbox and change it in the modal.

2022-02-04 13:02 UTC, peterpeterparker commented
@lmuntanerDfinity `theme` works for me. let's go for it 👍 . sure please also refactor `<Checkbox />`, thx!

```
export let theme: "dark" | "light" = "light";
```

2022-02-04 13:21 UTC, lmuntanerDfinity commented
@peterpeterparker changes applied

2022-02-04 13:31 UTC, peterpeterparker approved these changes
@lmuntanerDfinity LGTM, thanks!

I already approve it so that it won't be blocked but please do first resolve @nmattia open questions before merging it.

2022-02-04 13:34 UTC, lmuntanerDfinity commented
@peterpeterparker ready for one (last?) review 😅

2022-02-04 14:07 UTC, nmattia commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  export let showBackButton: boolean = false;
The comment isn't particularly clear, in particular it doesn't explicitly tell you to use both or neither. Maybe a line about this before the `export` list?

2022-02-04 14:09 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  export let showBackButton: boolean = false;
done!

2022-02-04 14:15 UTC, nmattia approved these changes
LGTM!

2022-02-04 14:19 UTC, merged