L2 218: Create Neuron UI
dfinity/nns-dapp pull request #423
Opened 2022-02-10 15:17 UTC by lmuntanerDfinity

# Motivation

Develop the UI components to create a neuron.

# Changes

* New components in `modals/CreateNeuronModal`.
* Expanded `Input` to support dark theme.
* Expanded `button` styles to support full-width.
* Expanded Identifier to hide button to copy to the clipboard.

# Tests

* New test in route Neurons to check opening the modal
* Test for `CreateNeuronModal`. The inner components are implementation details. Tested here.

2022-02-10 16:48 UTC, mstrasinskis requested changes

2022-02-10 16:48 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +      on:click={copyToClipboard}
`stopPropagation` in case of click event on the Card

2022-02-10 17:07 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +      on:click={copyToClipboard}
> Where are the tests?
> 
> 😜

Hehehe, I first like to do a PR, to give you time to review, then I add the tests.

If you prefer to review all at once, I can always wait for the tests.

2022-02-10 17:08 UTC, lmuntanerDfinity commented
> Where are the tests?
> 
> 😜

I like to first do a PR without tests to start the review. While you review, I add the tests and also do the changes requests.

If you prefer, I can wait to have everything finished.

2022-02-10 17:08 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +    wizard?.subscribe((value) => (currentIndex = value));
I did it as well. I realized it adding the tests, thanks!

2022-02-10 17:10 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +      on:click={copyToClipboard}
yes, thanks!

2022-02-10 17:15 UTC, peterpeterparker commented
> I like to first do a PR without tests to start the review. 

@lmuntanerDfinity create / modify the PR to "draft" then.

Will have a look tomorrow.

2022-02-11 06:42 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +      <Input
the default is `number`. Which is what I use in the `amount` as well. I didn't remember it.

2022-02-11 06:49 UTC, lmuntanerDfinity commented
> > I like to first do a PR without tests to start the review.
> 
> @lmuntanerDfinity create / modify the PR to "draft" then.
> 
> Will have a look tomorrow.

Yes, you are right, I always forget. I will try to remember next time.

2022-02-11 06:50 UTC, lmuntanerDfinity commented
@peterpeterparker @nmattia @mstrasinskis ready for review!

2022-02-11 06:57 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/accounts/AccountCard.svelte
> +<Card on:click {role}>
Question: Shouldn't `click` be available only if `role` is set to `button`?

TODO: add mixin `@include interaction.tappable;` when clickable

2022-02-11 07:00 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +  export let showCopyIcon: boolean = true;
- rename prop, it is more than an icon, it's a function. `showCopy` maybe?

- on main screen the copy is activated but anywhere else not - i.e. more often the copy action is hidden (I think, to be checked), therefore default value shall probably be `false`?

2022-02-11 07:02 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  export let fullWidth: boolean = false;
shouldn't we solve this styling option with a CSS variable?

2022-02-11 07:03 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
you don't need that state I think

```
<div class="input-block" class:fullWidth class={theme}>
```

2022-02-11 07:06 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Wizard/Wizard.svelte
> +  export function subscribe(callback) {
same topic we already discussed but sinc it's a global store, why not using directly `selectedStepStore` in the `Modal`? it would made the code shorter

2022-02-11 07:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const chooseAccount = () => {
goodie - inline code:

```
const chooseAccount = () => wizard?.next();
```

2022-02-11 07:11 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const titleMapper = {
`const titleMapper: Record<string, string>`?

2022-02-11 07:12 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  showBackButton={currentIndex === 1}
is there a chance that we add more steps? if yes then maybe `> 0` or even using a reusable function or else?

2022-02-11 07:14 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let main: Account | undefined;
that's actually the selected account right? the main or a sub-account (once we have implemented these) right? so maybe already rename the state in something like `selectedAccount`?

2022-02-11 07:17 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const chooseAccount = () => {
maybe add some comments / todos like "// TODO: apply accounts selection"

2022-02-11 07:21 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +  const createNeuron = () => {
add some todos

2022-02-11 07:25 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +  { min, max }: { min?: number; max?: number } = { min: 8, max: 8 }
a couple of weeks ago before you started we, the all team in a 1pm chat, decided to always display 8 decimals in the nns rewrite. I guess you are setting 4 because it's 4 currently in production. probably something worth to discuss.

2022-02-11 07:26 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +    gap: 1.4rem;
rem? shouldn't be a value related to `--padding` or a multiple of 5px or 10px?

2022-02-11 07:28 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +    width: 90%;
90% ? what is the 10% value? shouldn't be something like 100% - a known value, like `calc(100% - var(--padding))` or something?

2022-02-11 07:29 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +      margin-top: 2rem;
should be related  to`--padding` I think - no rem

2022-02-11 07:29 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  let medium: boolean;
can probably spare the state with `class={size}`

2022-02-11 07:30 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +      width: 520px;
shall we - can we - use some mixin value @mstrasinskis recently defined?

2022-02-11 07:31 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    z-index: 1;
use `--z-index`

2022-02-11 07:34 UTC, peterpeterparker requested changes
A couple of feedback and questions, thanks.

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Wizard/Wizard.svelte
> +  export function subscribe(callback) {
We would expose that we are using a store for the Wizard. I'd rather focus on the API than leaking implementation details.

Maybe @nmattia or @mstrasinskis can also help.

I have the feeling that if at some point we want to use different Wizard in the same page, we couldn't use the store as is. If we then removed the store, we would have to refactor all the code where we imported the store.

I agree that it feels a little bit hacky, I can't say I am proud of this part 😂

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let main: Account | undefined;
I can rename and add a TODO.

Btw, this means that the Neurons page has dependency on the Account page, at least for this part. It might make sense to start with that page as well.

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const chooseAccount = () => {
yep

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const titleMapper = {
ok

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  showBackButton={currentIndex === 1}
yes, there will be more steps, not added yet. But the back button is only valid on the second step (index 1), the other steps do not allow to go back.

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +  const createNeuron = () => {
and remove console log 😅

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +    gap: 1.4rem;
ah, true, we don't use `rem` here, sorry. I usually use rem.

I will change it.

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +    width: 90%;
Actually, I think it would be better to apply a padding to the parent instead, and use a 100% width here.

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +      margin-top: 2rem;
yep, sorry

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  let medium: boolean;
same, I thought we preferred this pattern, I will change it.

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +      width: 520px;
the breakpoints?

Or I can create new variables `--width-modal-small`, `--width-modal-medium`, ...

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    z-index: 1;
👍

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +  { min, max }: { min?: number; max?: number } = { min: 8, max: 8 }
Yes, in prod it's only 4, shall I leave it at 8?

2022-02-11 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Neurons.svelte
> +  const stakeNeurons = () => {
ok, I usually used the short notation only if I cared about the return value.

I will change the pattern I usually use.

2022-02-11 08:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  export let fullWidth: boolean = false;
Let's have a look together next week.

2022-02-11 08:56 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
> Attributes need to be unique

In HTML but svelte takes care of regrouping these.

```
<script>
	let name = 'world';
	
	const theme = 'dark';
	
	const fullWidth = true;
</script>

<h1 class={theme} class:fullWidth>Hello {name}!</h1>
```

output => `<h1 class="dark fullWidth">Hello world!</h1>`

2022-02-11 08:58 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  showBackButton={currentIndex === 1}
alright. maybe a comment then?

2022-02-11 09:01 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +  { min, max }: { min?: number; max?: number } = { min: 8, max: 8 }
Maybe leave at 8 and add a TODO?

I might mean, if the team agree to 4, that you will have to revert the code to 4 in a separate PR but it will make the choice explicit then, maybe not that bad?

2022-02-11 09:02 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +      margin-top: 2rem;
no worries at all

2022-02-11 09:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/accounts/AccountCard.svelte
> +<Card on:click {role}>
If you don't pass a `on:click` when using the `Card` it's not clickable. Nothing is passed to `on:click`, it would be the same as `on:click={undefined}` which is the same as not having `on:click`.

2022-02-11 09:05 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
note it was just a test, maybe that's not a bad practice in svelte and such pattern is bad in svelte too?

then maybe `class={`${theme} ${fullWidth ? 'fullWidth' : ''}`}

I just fear that with time passing we've got a lot of states and `$:` so if we can spare some it might be worth it

2022-02-11 09:08 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  export let fullWidth: boolean = false;
I might need this to continue with the next task, the task was to create a Neuron, I splitted in two, to make the PRs easier to review.

2022-02-11 09:09 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
yes, but not `class="input-block" class={theme}`, I changed it to `class={ `input-block ${theme} `}`

2022-02-11 09:09 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  showBackButton={currentIndex === 1}
ok

2022-02-11 09:10 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
Alright it is ok. In svelte [doc](https://svelte.dev/docs#class_name) they have following example:

```
<!-- Multiple class toggles can be included -->
<div class:active class:inactive={!active} class:isAdmin>...</div>
```

2022-02-11 09:11 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +  { min, max }: { min?: number; max?: number } = { min: 8, max: 8 }
ok, sounds good

2022-02-11 09:20 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
For booleans it's ok, not for strings.

2022-02-11 09:44 UTC, mstrasinskis commented on frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
> +    await fireEvent.input(input, { target: { value: 22 } });
Nice 😊

2022-02-11 10:04 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/accounts/AccountCard.svelte
> +<Card on:click {role}>
Alright then, thx

2022-02-11 10:05 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  export let fullWidth: boolean = false;
Add a // TODO to go on and we have a look together next week.

2022-02-11 10:06 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  let dark: boolean;
> For booleans it's ok, not for strings.

You tried out or found that in the svelte doc?

2022-02-11 10:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +      width: 520px;
just thought maybe worth not have "hard coded" length in a component, so yeah either mixin or variables. @mstrasinskis  took care of the media queries recently, he can probably answer that's why i pinged it

2022-02-11 10:11 UTC, peterpeterparker commented
Adding tests for the changes in the existing components that have been modified is something you will do once everything reviewed do I get it right?

2022-02-11 12:18 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/Modal.svelte
> +      width: 520px;
done, discussed with @mstrasinskis and found a nice way to do it.

2022-02-11 12:20 UTC, lmuntanerDfinity commented
> Adding tests for the changes in the existing components that have been modified is something you will do once everything reviewed do I get it right?

I already changed the tests for the `Identifier` regarding the copy icon. Also added the test in the `Neurons` route that opens the modal. Do you want me to add tests for the prop `size` in the `Modal` and also the props `theme` and `fullWidth` in `Input`? I didn't know we wanted to test all the css props as well.

A part from that, @peterpeterparker ready for another review

2022-02-11 12:20 UTC, lmuntanerDfinity commented
@mstrasinskis @nmattia ready for one more review

2022-02-11 12:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +  export let fullWidth: boolean = false;
thx

2022-02-11 12:54 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +      width: 520px;
cool 👍

2022-02-11 12:58 UTC, peterpeterparker commented
@lmuntanerDfinity I personally would say yes, tests for any props particularly if they are changes but if the others are fine without for sure I can live with it.

a part from that, review is alright thanks for the changes. only thing which still remains open though is my question regarding "wizard global store and "hacky" (😉) subscribe". looking forward to the feedback of maks and nicolas about it.

2022-02-11 13:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Wizard/Wizard.svelte
> +  export function subscribe(callback) {
@mstrasinskis @nmattia we need your input here if you don't mind.

2022-02-11 13:43 UTC, mstrasinskis requested changes

2022-02-11 13:43 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Wizard/Wizard.svelte
> +  export function subscribe(callback) {
TBH looking on:
```
$: {
    if (!unsubscribeWizard && wizard) {
      unsubscribeWizard = wizard.subscribe((value) => {
        currentIndex = value;
      });
    }
  }
```
I would prefer Wizard to dispatch the changes 🙈

2022-02-11 13:43 UTC, mstrasinskis commented on frontend/svelte/src/lib/themes/variables.scss
> +  --small-width: 300px;
Because it's a global scope some variable name prefix (like `modal-`) would be useful.

2022-02-11 13:43 UTC, mstrasinskis commented on frontend/svelte/src/lib/themes/variables.scss
> +  @media (min-width: 768px) {
```scss
  @use "./mixins/media";
  ...
  @include media.min-width(medium) {
     ...
```
?

2022-02-11 14:08 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Wizard/Wizard.svelte
> +  export function subscribe(callback) {
But actually `selectedStepStore` is already used here. Probably @peterpeterparker's suggestion is not so bad.

2022-02-11 14:14 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/themes/variables.scss
> +  @media (min-width: 768px) {
I didn't know I could add the mixin here, great!

2022-02-11 14:14 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/themes/variables.scss
> +  --small-width: 300px;
ok, makes sense

2022-02-11 14:14 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Wizard/Wizard.svelte
> +  export function subscribe(callback) {
ok, I will import it directly.

2022-02-11 14:42 UTC, lmuntanerDfinity commented
@peterpeterparker I have refactored the `wizardStore` to the pattern we use when we expose it.

https://github.com/dfinity/nns-dapp/pull/423/files#diff-38e808e7afe7d3789d555425b9b06349a1139d67e3bac771c3897b89d0b057bfR3

I have also added extra tests. Also one on the Wizard that when unmounted, it resets the store.

@mstrasinskis please also review 😄

2022-02-11 15:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Wizard/wizardStore.ts
> +const initStore = () => {
Can you add a small comment about what the store does and what are the exposed functions (@nmattia will appreciate it, see other stores as example)?

2022-02-11 15:26 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +      currentIndex = value;
goodie / question - not sure can't you spare the `onMount` and `subscribe` by using `showBackButton={$currentIndex === 1}` in the template (-> `$`)

I can live with it, just in case it can indeed same some lines of code

2022-02-11 15:28 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Wizard/wizardStore.ts
> +export const wizardStore = initStore();
can you add tests`wizard.store.spec.ts` for this store?

2022-02-11 15:29 UTC, peterpeterparker requested changes
Thanks for the improvements!!! Almost there 😉

2022-02-12 06:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Wizard/wizardStore.ts
> +const initStore = () => {
done!

2022-02-12 06:42 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Wizard/wizardStore.ts
> +export const wizardStore = initStore();
Instead of testing the store on it sown, I added tests in `Wizard.spec.ts`.

https://github.com/dfinity/nns-dapp/pull/423/files#diff-ae65a891043a0a4f905b31d49b0f92984adbb79920a0434887b0fcb59abee1c3R38

I also added a comment in the store about the testing:

https://github.com/dfinity/nns-dapp/pull/423/files#diff-38e808e7afe7d3789d555425b9b06349a1139d67e3bac771c3897b89d0b057bfR9

2022-02-12 06:44 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +      currentIndex = value;
Yes, true. I didn't need the `$`. The same way we subscribe to the `accountsStore`.

2022-02-12 06:45 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review!

2022-02-14 06:01 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Wizard/wizardStore.ts
> +export const wizardStore = initStore();
ok

2022-02-14 06:02 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let unsubscribeWizard: Unsubscriber = wizardStore.subscribe(
`const`

2022-02-14 06:04 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let titleKey: string = "select_source";
`let titleKey: string = titleMapper[0]` so you can spare writing "select_source" twice

2022-02-14 06:05 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +  const transactionIcp = ICP.fromString("0.0001") as ICP;
`const transactionIcp: ICP = `

2022-02-14 06:09 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +  {#if showCopy}
isn't a test missing for this new toggle?

2022-02-14 06:11 UTC, peterpeterparker requested changes
A few goodie (not must) and I think it needs a small additional test.

Afterwards I'll approve it.

2022-02-14 06:35 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let titleKey: string = "select_source";
good point!

2022-02-14 06:35 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let unsubscribeWizard: Unsubscriber = wizardStore.subscribe(
yep

2022-02-14 06:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/StakeNeuron.svelte
> +  const transactionIcp = ICP.fromString("0.0001") as ICP;
ok

2022-02-14 06:38 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +  {#if showCopy}
Yes, it's there: https://github.com/dfinity/nns-dapp/pull/423/files#diff-2a1cb7a26e14da35ffc680918de7a4b86ead4fb68bea404b2687f84f72c5e51bR20

The first test does not check for the button, while the second one does.

The next test: "should copy identifier to clipboard" also uses this prop to check that it actually copies the text to the clipboard.

2022-02-14 06:39 UTC, lmuntanerDfinity commented
> 

Thanks @peterpeterparker !

IMHO, those changes should be taken care with a linter.

2022-02-14 07:20 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +  {#if showCopy}
The link does not point to the specific code for me. Anyway as far as I can tell there is no test that assert that the button is not rendered for the default showCopy=false value.

2022-02-14 07:56 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +  {#if showCopy}
No, there is no test that when the prop is false there is no button.

IMHO, I find testing that the `false` don't do something, it's a little bit too much testing.

Sorry for the broken link, not sure what happened. Here are the tests in this branch: one to check that it renders the identifier and another one that the `showCopy` renders a button. There is also the one that the button copies the text to the clipboard.

```
  it("should render an identifier", () => {
    const { container } = render(Identifier, { props });

    const small = container.querySelector("small");
    expect(small).not.toBeNull();
    expect(small.textContent).toEqual(identifier);
  });

  it("should render an accessible button", () => {
    const { getByRole } = render(Identifier, {
      props: { identifier, showCopy: true },
    });

    const button = getByRole("button");

    expect(button).not.toBeNull();
    expect(button.getAttribute("aria-label")).toEqual(
      "Copy identifier to clipboard"
    );
  });
```

2022-02-14 08:50 UTC, peterpeterparker approved these changes
Beside my comment about the test, good to me.

2022-02-14 08:56 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ic/Identifier.svelte
> +  {#if showCopy}
I added it

2022-02-14 08:59 UTC, mstrasinskis approved these changes

2022-02-14 09:09 UTC, merged