Page skeleton layout
dfinity/nns-dapp pull request #424
Opened 2022-02-10 16:01 UTC by mstrasinskis

# Motivation

Create the components for layout - skeleton of the “sub-pages” which should work with the footer.
[L2-212](https://dfinity.atlassian.net/browse/L2-212)

<img width="871" alt="image" src="https://user-images.githubusercontent.com/98811342/153446273-a58585c2-0c02-45d6-82b3-456231b86eb3.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/98811342/153446367-52909261-9f4b-4979-a8d3-ee6280ab29cf.png">

# Changes

- ++ `<IsolatedPageLayout>`
- ++ contentless `<Wallet>` page (as PoC for IsolatedPageLayout)
- ++ contentless `<ProposalDetails>` page (as PoC for IsolatedPageLayout)
- ++ simple `<Tooltip>` component (for the back button)
- ++ `<Footer>` as separate component (reusability)
- ++ `routeStore.back()`
- ++ `routeStore.previousPath`
- Routes were refactored (reusability)
- Refactored page-path-matching to support wallet and proposal_detail dynamic urls

# Tests

🚧

2022-02-10 16:11 UTC, mstrasinskis commented on frontend/svelte/src/routes/ProposalDetails.svelte
> +      // TODO: TBD
📌 Not sure about this place

2022-02-11 09:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/App.svelte
> +  import { AppPath } from "./routes/routes";
👏

2022-02-11 09:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/common/PrivateRoute.svelte
> +    if (signedIn || comparePathWithRoutePath(path, routePath()) === false) {
```
signedIn || !comparePathWithRoutePath(path, routePath())
```

2022-02-11 09:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/icons/IconBackIosNew.svelte
> +<!-- source: https://fonts.google.com/icons?selected=Material+Icons&icon.query=arrow+back+ios+new -->
We already have a back icon for the Modal, should we use the same one?

2022-02-11 09:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/ProposalDetails.svelte
> +      routeStore.navigate({
If we always go back to Proposals, why checking? to keep the navigation history?

2022-02-11 14:39 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/accounts/AccountCard.svelte
> +    routeStore.navigate({ path: `${AppPath.Wallet}/${identifier}` });
Not sure, because most of them (all_paths - 2) are static string only.

2022-02-11 14:45 UTC, mstrasinskis commented on frontend/svelte/src/routes/ProposalDetails.svelte
> +      routeStore.navigate({
Tried to improve UX a bit 😄
@peterpeterparker what are your thoughts?

2022-02-14 08:46 UTC, peterpeterparker requested changes
Looks cool and works well 👍

Just a couple of comments.

2022-02-14 08:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/route.store.ts
> +      history.back();
For constistency reason, can you also implement `back` in `route.utils` with fallback if the history API is not supported ?

2022-02-14 08:46 UTC, peterpeterparker commented on frontend/svelte/src/routes/routes.ts
> +export const comparePathWithRoutePath: (
we have no lint rules about it but I like for maintanability reason, as soon as more than 1 param is available, to use descriptive / interface for params.

`export const comparePathWithRoutePath: ({path, routePath}: {path: AppPath, routePath: string})`

works for you?

2022-02-14 08:46 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetails.svelte
> +      routeStore.navigate({
we probably need the check or a check because user can access the page with alternative routes on desktop, like through bookmarks.

2022-02-14 08:46 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetails.svelte
> +  const goBack = () => {
code is duplified, can you extract a utiliy function?

2022-02-14 08:46 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetails.svelte
> +      // TODO: TBD
As far as I remember we placed the redirect in `onMount` on purpose and/or after some tests. Therefore as it follow other routes, I think it should be good. Doesn't mean of course that you cannot challenge it, just FYI :)

2022-02-14 10:13 UTC, mstrasinskis commented on frontend/svelte/src/lib/stores/route.store.ts
> +      history.back();
Just asking because of not so simple implementation, do we really need to support IE <= 9 ([history api](https://caniuse.com/history))

2022-02-14 10:34 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/route.store.ts
> +      history.back();
I see. Alright then only maybe refactor (move function, so we have all navigation related functions at the same placee) and add a comment please.

Of course if we still need .back ;)

2022-02-14 10:53 UTC, mstrasinskis commented on frontend/svelte/src/routes/routes.ts
> +export const comparePathWithRoutePath: (
Sure, done!

2022-02-14 11:08 UTC, peterpeterparker approved these changes
LGTM, thx

2022-02-14 11:55 UTC, lmuntanerDfinity approved these changes

2022-02-14 17:19 UTC, merged