Feat: Add Fetch Root Key in development
dfinity/nns-dapp pull request #425
Opened 2022-02-11 13:28 UTC by lmuntanerDfinity

# Motivation

Calls in testnet need to fetch the root key.

# Changes

When creating the agent, if the environment is development, then it fetches the root key.

# Tests

No new functionality.

2022-02-11 13:30 UTC, lmuntanerDfinity commented
@nmattia please review. I think that we discussed it the other day. I ended up not using it in my issue, but I had forgot about it and we will need it next week when we start interacting with testnet using nns-js.

2022-02-11 13:31 UTC, lmuntanerDfinity commented
@mstrasinskis @peterpeterparker fyi, this is needed for the calls to testnet to work properly.

2022-02-11 13:47 UTC, nmattia commented on frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
> +      new Promise<HttpAgent>((resolve) => resolve(undefined));
```suggestion
    const mockCreateAgent = Promise.resolve(undefined)
```

Is this actually being used? I'm surprised not to see any changes at call sites

2022-02-11 14:43 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/agent.utils.ts
> +  if (process.env.FETCH_ROOT_KEY === "true") {
Oops, I forgot to add the changes in rolllup confit, I always skip those because I change it for local development

2022-02-11 14:50 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
> +      new Promise<HttpAgent>((resolve) => resolve(undefined));
We mock the `LedgerCanister.create`, therefore the `createAgent` is never used in the tests.

```
jest
      .spyOn(LedgerCanister, "create")
      .mockImplementation((): LedgerCanister => mockLedgerCanister);
```

Yet, to avoid a dependency on fetch when creating the agent from `@dfinity/agent`, we need to avoid importing it. Without a mockImplementation, it imports the file, also the library and the error appears.

```
    Fetch implementation was not available. You appear to be in a Node.js context, but global.fetch was not available.

      4 | // To avoid being executed in tests that only import it
      5 | export const createAgent = async () => {
    > 6 |   const agent = new HttpAgent({ host: serviceURL });
        |                 ^
      7 |
      8 |   if (process.env.FETCH_ROOT_KEY === "true") {
      9 |     await agent.fetchRootKey();

      at getDefaultFetch (node_modules/@dfinity/agent/src/agent/http/index.ts:100:13)
      at new HttpAgent (node_modules/@dfinity/agent/src/agent/http/index.ts:147:38)
      at createAgent (src/lib/utils/agent.utils.ts:6:17)
      at loadAccounts (src/lib/utils/accounts.utils.ts:12:29)
      at Object.<anonymous> (src/tests/lib/utils/accounts.utils.spec.ts:41:23)
```

2022-02-11 14:51 UTC, lmuntanerDfinity commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
I added this to avoid having the change this every time we develop locally.

We can assume this, is that correct?

2022-02-11 14:51 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/agent.utils.ts
> +  if (process.env.FETCH_ROOT_KEY === "true") {
Here it is: https://github.com/dfinity/nns-dapp/pull/425/files#diff-74abfab6043a5b76506f46cdfcf671a49f4c45cb86796255a237b2b66bdd685fR87

2022-02-11 14:52 UTC, lmuntanerDfinity commented
@nmattia ready for another one 😸

2022-02-11 14:57 UTC, nmattia commented on frontend/svelte/src/tests/lib/utils/accounts.utils.spec.ts
> +      new Promise<HttpAgent>((resolve) => resolve(undefined));
I'm still a bit confused about why having `mockCreateAgent` makes an error about `global.fetch` not existing disappear, but I don't have much experience with typescript :)

2022-02-11 14:59 UTC, nmattia commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
I _think_ so! but does that mean that you set `DEPLOY_ENV` to `testnet` when developing locally?

2022-02-11 15:00 UTC, nmattia commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
Wait, this is `REDIRECT_TO_LEGACY`, I misread. I never quite understood what it did so better check with @bitdivine

2022-02-11 15:04 UTC, nmattia commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
I actually have no idea, I haven't actively worked on the frontend here!

2022-02-11 16:09 UTC, nmattia reviewed
Unblocking! Though not quite approving because I didn't grasp everything re. the mock config, leaving this up to @bitdivine and @peterpeterparker

2022-02-11 16:09 UTC, nmattia approved these changes
Unblocking

2022-02-14 06:19 UTC, peterpeterparker commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
`REDIRECT_TO_LEGACY` = svelte redirect to flutter

Therefore I think it cannot be extended as suggested here. Current staging deployment happens my understanding with Redirect and Testnet at the same time.

But yes @bitdivine can confirm.

2022-02-14 06:21 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/agent.utils.ts
> +  if (process.env.FETCH_ROOT_KEY === "true") {
the value is stringifie in the rollup config => `if (process.env.FETCH_ROOT_KEY)`

2022-02-14 06:32 UTC, peterpeterparker requested changes
We are already using the configuration `DEPLOY_ENV` in `<Header/>`  for a check `{#if deployEnv === "testnet"}`.

Therefore I think it is not a good idea to have this test and another different configuration `FETCH_ROOT_KEY` that both check for the exact same equality on "testnet".

Possible solutions:

- rename `FETCH_ROOT_KEY` to something more generic and update  - use it in`<Header/>`

- remove `FETCH_ROOT_KEY` and use `DEPLOY_ENV` in `createAgent`

2022-02-14 06:32 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/agent.utils.ts
> +  if (process.env.FETCH_ROOT_KEY === "true") {
the value is stringified in the rollup config => `if (process.env.FETCH_ROOT_KEY) {`

2022-02-14 06:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/agent.utils.ts
> +  if (process.env.FETCH_ROOT_KEY === "true") {
Yes, but depends on how we agree, this might change.

2022-02-14 06:49 UTC, lmuntanerDfinity commented
> We are already using the configuration `DEPLOY_ENV` in `<Header/>` for a check `{#if deployEnv === "testnet"}`.
> 
> Therefore I think it is not a good idea to have this test and another different configuration `FETCH_ROOT_KEY` that both check for the exact same equality on "testnet".
> 
> Possible solutions:
> 
> * rename `FETCH_ROOT_KEY` to something more generic and update  - use it in`<Header/>`
> * remove `FETCH_ROOT_KEY` and use `DEPLOY_ENV` in `createAgent`

I agree on refactor and simplify the process. Also the `REDIRECT_TO_LEGACY` I'd say:

```
      "process.env.REDIRECT_TO_LEGACY": JSON.stringify(
        ["true", "1"].includes(process.env.REDIRECT_TO_LEGACY)
          ? true
          : ["false", "0"].includes(process.env.REDIRECT_TO_LEGACY)
          ? false
          : process.env.DEPLOY_ENV === "testnet"
          ? false
          : true
```

Let me set up a document to see if I understand the usage of each and we can agree on how to simplify it.

2022-02-14 08:18 UTC, mstrasinskis commented on frontend/svelte/rollup.config.js
> +        process.env.DEPLOY_ENV === "testnet" ? true : false
I guess `? true : false` is redundant.

2022-02-14 08:43 UTC, bitdivine commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
Correct, pre-release deployments happen with REDIRECT_TO_LEGACY unset, defaulting to true, however I can always set the env var `REDIRECT_TO_LECACY=1` as that will take priority over this change, so this is not a problem for me.  I would be fine with that.  If this does get merged, please ping @hpeebles as he mostly develops on the flutter side of the app and would be surprised if flutter did not show up.  I was using the rule of thumb:  "Make it like production except when the user says otherwise."

2022-02-14 09:34 UTC, lmuntanerDfinity commented on frontend/svelte/rollup.config.js
> +          : process.env.DEPLOY_ENV === "testnet"
thanks! I am continuing the conversation in the Notion page, we can then use the decisions there to change this PR, update the config and also write this in comments or in a markdown doc in the same repo.

2022-02-16 09:27 UTC, lmuntanerDfinity commented
Closing, changes are stale and not worth it.

2022-02-16 09:27 UTC, closed without merging