LM-259: Add Account
dfinity/nns-dapp pull request #447
Opened 2022-02-16 09:01 UTC by lmuntanerDfinity

# Motivation

Create SubAccount

# Changes

* New Modal `AddAccountModal`
* New accounts store method `createSubAccount`
* New accounts utils function `createSubAccount`
* Using new nns-js function `createSubAccount`

# Tests

* `AddAccountModal.spec.ts`
* PENDING utils and store tests

2022-02-16 09:02 UTC, lmuntanerDfinity commented
Screenshots below

![Screenshot 2022-02-16 at 10 01 35](https://user-images.githubusercontent.com/98735375/154230749-d300053f-19bc-4edf-b870-d6bfc00520dd.png)
![Screenshot 2022-02-16 at 10 01 42](https://user-images.githubusercontent.com/98735375/154230754-178df4a0-723d-4202-b6e8-8ad817818b1b.png)

2022-02-16 09:02 UTC, lmuntanerDfinity commented
BLOCKED by https://github.com/dfinity/nns-js/pull/36

2022-02-16 09:15 UTC, mstrasinskis commented on frontend/svelte/src/routes/Accounts.svelte
> +    <AddAcountModal visible={showAddAccountModal} on:nnsClose={closeModal} />
There is one `<main>` tag in `<Layout>` component. Probably the Layout needs to be extended w/ the `hidden` prop.

> A document must not have more than one [main](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element) element that does not have the [hidden](https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden) attribute specified.

2022-02-16 14:58 UTC, peterpeterparker commented
FYI As we discussed in one of my PR, I provided a PR that refactor utils in services and refactored the logic to load the accounts as we expected. I guess once merged it will conflicts with your PR.

👉 https://github.com/dfinity/nns-dapp/pull/452

2022-02-22 13:26 UTC, mstrasinskis reviewed
👍 Just a couple of questions.

2022-02-22 13:26 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      if (currentError.kind !== AccountNotFoundError.kind) {
Why not `currentError  instanceof AccountNotFoundError`?

2022-02-22 13:26 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      newSubAccount = await nnsDapp.createSubAccount({
`error = undefined;` here? To avoid `throw error`on line 88. Or should it throw anyway?

2022-02-22 13:26 UTC, mstrasinskis commented on frontend/svelte/src/routes/Accounts.svelte
> +      <AddAcountModal visible={showAddAccountModal} on:nnsClose={closeModal} />
Will it work if `modal.visible` is true by default?

2022-02-22 13:29 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      newSubAccount = await nnsDapp.createSubAccount({
oh yes!

2022-02-22 13:29 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Accounts.svelte
> +      <AddAcountModal visible={showAddAccountModal} on:nnsClose={closeModal} />
mhm, in that case I could avoid the `visible={...}`, chall we change that?

2022-02-22 13:32 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      if (currentError.kind !== AccountNotFoundError.kind) {
🤞

2022-02-22 13:34 UTC, mstrasinskis commented on frontend/svelte/src/routes/Accounts.svelte
> +      <AddAcountModal visible={showAddAccountModal} on:nnsClose={closeModal} />
Could you please test that this wouldn't break the animation?

2022-02-22 13:53 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      if (currentError.kind !== AccountNotFoundError.kind) {
It would be "not instance" do you think it's nicer? `!(currentError instanceof AccountNotFound)`?

2022-02-22 13:55 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Accounts.svelte
> +      <AddAcountModal visible={showAddAccountModal} on:nnsClose={closeModal} />
animation to appear looks good, to go out not so much. Any suggestion?

2022-02-22 13:56 UTC, lmuntanerDfinity commented
@peterpeterparker ready for review

2022-02-22 14:07 UTC, peterpeterparker requested changes

2022-02-22 14:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/accounts.services.ts
> +  while (tries < MAX_TRIES && newSubAccount === undefined) {
can we rather comment the all block until it is clear what and why and how?

I am not comfortable merging that `while` in main branch.

2022-02-22 14:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +    subAccounts: [],
Should be the all object of accounts | undefined? Something like

```
const { subscribe, set, update } = writable<Accounts | undefined>(undefined)
```

feels like an empty array of sub-accounts and a main account undefined does not match well together

2022-02-22 14:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/AddAccountModal/SelectTypeAccount.svelte
> +<script lang="ts">
no tests for SelectTypAccount?

2022-02-22 14:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
> +<script lang="ts">
no test for AddNewAccount?

2022-02-22 14:07 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +export const accountsStore = initAccountsStore();
some tests?

2022-02-22 14:11 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      if (currentError.kind !== AccountNotFoundError.kind) {
If only this helps to get rid of `kind` property.

2022-02-22 14:14 UTC, mstrasinskis commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +    subAccounts: [],
LGTM So main is undefined and subAccounts[0..n] are undefined

2022-02-22 14:33 UTC, lmuntanerDfinity commented on frontend/svelte/env.config.mjs
> +// Testnet Canister Ids
ah, I didn't know. I will update the comment.

2022-02-22 14:33 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/AddAccountModal/AddAccountModal.svelte
> +    height: 500px;
the user won't be able to see it all.

I think this modal height could be handled in general as well.

Maybe in https://dfinity.atlassian.net/browse/L2-302 as well?

2022-02-22 14:33 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
> +<script lang="ts">
I consider the components `AddNewAccount` and `SelectTypeAccount` as implementation details.

I test them in the `AddAccountModal.spec.ts`. In there I test both of them.

2022-02-22 14:33 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +  while (tries < MAX_TRIES && newSubAccount === undefined) {
sure

2022-02-22 14:45 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Accounts.svelte
> +      <AddAcountModal visible={showAddAccountModal} on:nnsClose={closeModal} />
it's not because of the `visible` but because of the `{#if `. Which I prefer to avoid having components rendered that do nothing.

2022-02-23 05:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +  export let visible: boolean = true;
alright. I'm surprised it pass without crashing a test or there weren't one. if none, can you add a small one for it?

2022-02-23 06:08 UTC, peterpeterparker requested changes

2022-02-23 06:08 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
I am not sure about the store definition. With this form we can potentially ends up in a state where `subAccounts` are loaded but the `mainAccount` isn't or the contrary. Means we potentially might display partial information and make functions available that should not, like creating a first sub account even though they would exists and stuffs like that

That's why I ask myself if it would not be better to have a store "all or nothing" - i.e. either the `mainAccount` and the `subAccounts` are loaded or nothing .

These accounts are linked money - user ICPs, therefore the precaution.

What do you think?

Something like `writable<Accounts | undefined>(`

2022-02-23 07:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
So you propose that we cannot just add a `subAccount`, either set all the store or nothing else?

2022-02-23 08:00 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
Yes that's my suggestion / question

2022-02-23 08:17 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
I created an issue to remove the add_account call, the one that its commented, I will start when I merge this.

https://dfinity.atlassian.net/browse/L2-301

What I could do is to always fetch main and subaccounts and set the store.

Even after creating a subaccount, we could make the call to fetch all new. This way, it's not only the store that could set partial information, but that we ensure that when fetching, we always fetch it together.

Otherwise, even though we use set when creating a new subaccount, we are relying that the data is there, but we cannot be sure about it as you say. If we want to be safe, it's not just the store, but also the fetch that we should to together.

Does that make sense? I can add it to the issue.

2022-02-23 08:25 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
> What I could do is to always fetch main and subaccounts and set the store.
> 
> Even after creating a subaccount, we could make the call to fetch all new. This way, it's not only the store that could set partial information, but that we ensure that when fetching, we always fetch it together.

This ain't a guarantee that both values are set at once or not. It would programmatically amend that both are set at the same time in your code but does not gives the guarantee that these are always set at once. Likewise, in x months or somewhere else in the code, someone might add a piece of code that desynchronize both values.

It's first a general question first, do we want:

a. set all the store (main + sub) in one single block or nothing else - i.e. a store that contains all accounts or nothing
b. set either main and subaccount - i.e. a store that has either a main account only, either subaccounts only or both or nothing

For the reason I listed previously I feel it's rather more secure to have a.

But, it's a question, what do you @lmuntanerDfinity and @mstrasinskis think? a. or b.?

2022-02-23 08:31 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
I don't have a strong opinion. "a" is safer but less performant. If we prefer safety than UX, then we should go for "a".

We should establish the priorities of the application as a whole to have consistent patterns. I don't think that we should be talking only about account and subaccounts here. There will be other places where we will need to choose between performance and security.

2022-02-23 09:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/stores/accounts.store.ts
> +  const { subscribe, set, update } = writable<AccountsStore>({
added comments, this task will be done in https://dfinity.atlassian.net/browse/L2-301

2022-02-23 09:19 UTC, peterpeterparker approved these changes
LGTM

About `main` and `subAccounts`, we, @lmuntanerDfinity @mstrasinskis and I, have decided in a chat to go with solution `a.` for security reason ("all or nothing - i.e. `main` and `sub` accounts are fetched or nothing is added to store"). 

In addition to the store API itself that will expose only a setter (no update), we also decided to secure this choice that we will synchronize "in block" the accounts information not only at boot time but also after any operation on the account - e.g. creating a sub-account.

This will be done in upcoming PRs.

2022-02-23 10:32 UTC, merged