Feat: Refactor Wizard and Setup Eslint
dfinity/nns-dapp pull request #454
Opened 2022-02-17 09:48 UTC by lmuntanerDfinity

# Motivation

Refactor Wizard component to something simpler and enable multiple in the same page.
Setup Eslint to enforce type rules.

# Changes

* Add `.eslintrc.js` file.
* Installed Eslint dependencies.
* Removed `Wizard` and `Wizard` Components in favor of a `WizardStore`.
* New UI Component for transitions: `Transition`.

# Tests

* Tests for `WizardStore`.

2022-02-17 09:49 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-02-17 14:18 UTC, mstrasinskis commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +    {#if currentIndex === Steps.SelectAccount}
currentIndex -> currentStep: Steps

2022-02-17 15:23 UTC, peterpeterparker requested changes

2022-02-17 15:23 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  enum Steps {
I recently a hard time with `enum`, still got PTSD 🤣. if it is possible with `type` I would not be against.

2022-02-17 15:23 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
- we use the modal also without the wizard (filters for example), therefore not sure it is a good idea to initialize it every time for every cases

- is it safe to init the wizard in component related script?

2022-02-17 15:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +  let container: HTMLDivElement | undefined;
`bind:this` does not set `null` after inspecting it. But I can't find any docs that support this statement.

2022-02-17 15:59 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +module.exports = {
No, this PR does not add any additional linter rules. I wanted to do the setup and then decide with the team which rules we want to enforce. I preferred not to make the decision myself.

`svelte-check` does not seem to provide functionality to check for consistency in how we use types. For example, ensuring that all the variables have a type instead of relying in implicit types.

The PR #326  seems to have been closed because you were looking for a more global way of linting (based on the comments). Not because `svelte-check` was a substitute.

I don't mind not adding eslint, but enforcing style rules without being able to check the automatically just calls for inconsistency.

2022-02-17 16:00 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +  let container: HTMLDivElement | undefined;
interesting, thanks for having a look and for the feedback 👍

2022-02-17 16:02 UTC, peterpeterparker commented on frontend/svelte/.eslintrc.js
> +module.exports = {
Not against at all! Can you just then as I said above provide a specific PR and adds it to the CI build? Thanks

2022-02-17 16:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  enum Steps {
I use an `enum` because I want to use 0 and 1 actually. The `enum` is just a more readable way to have 0 and 1.

Do you propose the following?

```
const Steps = {
  SelectAccount: 0,
  StakeNeuron: 1,
};
```

The, I would also need a type; otherwise I would be relying on implicit types. More lines. Do you prefer this? With or without type definition?

2022-02-17 16:06 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
This is what could enable us to have multiple Wizards in the same page each in a different step. If we initialize it in the component where it's used. Otherwise we are stuck with using one wizard per page.

I don't see any problem nor any article about not initializing stores inside a component.

I see this more as a way to reuse functionality. A class would also work, but it would not rerender. (I will try this)

2022-02-17 16:07 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +module.exports = {
Do you mean a PR just for the linter?

2022-02-17 16:18 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
does the script needs to be declared as `module` then?
does the store needs to be destroyed when the component is destroyed or does it happens automatically (memory overflow...)?

it's cool if we can scope the store sure.

2022-02-17 16:27 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +module.exports = {
done! #456

2022-02-17 16:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
Well, once the component is dismounted, the store is not referenced by any other variable, so I guess that the garbage collector should do its work.

Actually, if that is true, I don't even need to reset the store `onDestroy`.

2022-02-17 16:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
> I guess that the garbage collector should do its work.

Please analyze and be sure that the store is destroyed.

In addition, as I said in my [first](https://github.com/dfinity/nns-dapp/pull/454#discussion_r809167505) comment we do not have a wizard in every modal. Can you implement a solution for this as well?

2022-02-17 16:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  enum Steps {
alright then

2022-02-17 17:36 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
A store is just an object, if the other variables are also destroyed, I don't see why this one wouldn't.

I haven't found anywhere how to destroy stores. Yet, I found the "[Store Contract](https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values-store-contract)", where we could create our own stores as long as we keep the API.

Therefore, we cas assume, that the same way we can create objects inside a component, we can also create stores.

2022-02-18 06:47 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  const wizardStore = initWizardStore();
- Modal name: gotcha, yes, super confusing. Please rename or comment with a TODO if renamed in another PR.

- Store: I'll check briefly Monday

2022-02-18 07:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +  $: absolutOffset = container?.clientWidth || DEFAULT_OFFSET;
That's cool, but why would I do that? The width is already there, I use this for the transition. Not to change the width

2022-02-18 08:21 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis 

I joined the Svelte Discord channel that they [suggest](https://github.com/sveltejs/svelte/issues/new/choose) in their Github page and asked the following question:

> question - is it a bad practice to create a store inside a component? what happens when the component is destroyed, is the store garbage collected?

There are thousands of users and two moderators. One of the moderators answered to the question and we started talking. Long story short, this was his final answer:

> yeah sure, you can make a mycustomstore.js file and export a function that returns a store from there
> it’s a fairly common pattern :slightly_smiling_face:
> so you would do in your component:
> import { storeCreator } from ‘storeCreator.js’;
> const mystore = storeCreator()
> no mystore only exists within the context of that instance and will be safely removed when the component is

What do you think?

2022-02-18 08:33 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +  $: absolutOffset = container?.clientWidth || DEFAULT_OFFSET;
These bindings are readonly — changing the values of width won't have any effect.

2022-02-18 08:34 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +  $: absolutOffset = container?.clientWidth || DEFAULT_OFFSET;
aaahhh, you mean instead of using the container! Good one!

2022-02-18 08:45 UTC, peterpeterparker commented
@lmuntanerDfinity sounds good. as said previously, I still gonna have a brief look on Monday though 😉

2022-02-21 08:37 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/stores/StepsState.ts
> +export class StepsState<EnumType> {
Something that could be worth considering, is that the "class pattern" will only work if the "functionality + state" is only used in one component.

Whereas the "store pattern" could be used in many components at the same time, hence the pattern. That means that in case we wanted this functionality to apply to multiple components, we would need to find a way to do so in other ways, such as exposing methods from the component or passing props.

2022-02-22 06:01 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let stateStep = new StepsState(Steps);
When we will discuss eslint, I am not against explicit types for object `let stateStep: StepsState = ...`

2022-02-22 06:05 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  $: titleKey = titleMapper[stateStep.currentStep];
not sure but you can maybe destruct `stateStep`

```
let currentStep: number;
let diff: number;
$: ({currentStep, diff}) = stateStep

$: titleKey = titleMapper[currentStep];

...

showBackButton={currentStep === Steps.StakeNeuron}

....

{#if currentStep === Steps.SelectAccount}

...

<Transition diff={stateStep.diff}>
```

2022-02-22 06:06 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +function enumSize<EnumType>(enm: EnumType): number {
you can move the utils to `enum.utils`

2022-02-22 06:10 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +export class StepsState<EnumType> {
the class is not generic as far as I understand, so why `StepsState<EnumType>` instead of `StepsState`?

2022-02-22 06:13 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +  public get diff(): number {
I honestly did not understand what would returns `diff` and what was the goal of `diff`. can live with it - i.e. can be merged as it - but if you find something more meaningful, not against

2022-02-22 06:14 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +<script lang="ts">
we have test for the transition? if yes, should the related spec file be renamed too? if no, can we - should we add a test?

2022-02-22 06:15 UTC, peterpeterparker requested changes
No biggie, just a couple of small questions

2022-02-22 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +  public get diff(): number {
good point, I also didn't find a better name.

2022-02-22 08:15 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +function enumSize<EnumType>(enm: EnumType): number {
sure

2022-02-22 08:17 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  $: titleKey = titleMapper[stateStep.currentStep];
looks good

2022-02-22 08:22 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/CreateNeuronModal/Modal.svelte
> +  let stateStep = new StepsState(Steps);
ok

2022-02-22 08:45 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +<script lang="ts">
alright I guess we can rely on the e2e tests for this

2022-02-22 08:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Transition.svelte
> +<script lang="ts">
yes, also the modal tests check that the new component is rendered, not that there is a transition, but that the transition doesn't mess it up.

2022-02-22 08:49 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +export class StepsState<EnumType> {
it is confusing because you do not specify the enum type when you instantiate the class in your component `new StepsState(Steps);`. can you please add the type?

2022-02-22 08:52 UTC, peterpeterparker requested changes

2022-02-22 08:52 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/enum.utils.ts
> +export const enumSize = <EnumType>(enm: EnumType): number => {
cool, now we can even add a small test 😉

2022-02-22 08:52 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +  public get diff(): number {
only think I can think of is something like `direction` that return `forward` or `backward` but still not optional. maybe someday we will find a better naming

2022-02-22 08:58 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/enum.utils.ts
> +export const enumSize = <EnumType>(enm: EnumType): number => {
done

2022-02-22 10:17 UTC, mstrasinskis approved these changes
LGTM. Thanks for the state implementation 👍

2022-02-22 10:20 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +export class StepsState<EnumType> {
I have it in the assignment
```
let stateStep: StepsState<typeof Steps> = new StepsState(Steps);
```

2022-02-22 10:27 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/stepsState.services.ts
> +export class StepsState<EnumType> {
done

2022-02-22 10:29 UTC, peterpeterparker approved these changes
Thx

2022-02-22 10:44 UTC, merged