Feat: Canister Home Messaging
dfinity/nns-dapp pull request #457
Opened 2022-02-18 13:15 UTC by lmuntanerDfinity

# Motivation

Add content in Canisters Home

# Changes

* Add messages for Canisters Home.
* Increase margin in messages in Neurons Home

2022-02-18 13:16 UTC, lmuntanerDfinity commented
@mstrasinskis @peterpeterparker a super simple one.

Here are the screenshots:

![Screenshot 2022-02-18 at 13 50 09](https://user-images.githubusercontent.com/98735375/154689684-b9923ad4-15ff-4da4-8107-10c55f7941e6.png)

![Screenshot 2022-02-18 at 13 50 16](https://user-images.githubusercontent.com/98735375/154689689-f246fd14-b0d1-4718-8064-885d5d9f2889.png)

2022-02-21 06:15 UTC, peterpeterparker commented on frontend/svelte/src/routes/Canisters.svelte
> +        {$i18n.canisters.principal_is} "{$authStore.principal}"
`"{$authStore.principal}"` is automatically casted to string?

in `Neurons.svelte` we explicitly use `principal?.toText()`

2022-02-21 07:58 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Canisters.svelte
> +        {$i18n.canisters.principal_is} "{$authStore.principal}"
Good point, I didn't see it. It was working but it's better to change it.

2022-02-21 07:59 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review

2022-02-21 08:01 UTC, peterpeterparker requested changes
Cool, looks good.

Just one thing, can you add a test?

Probably worth testing that the `principal.toText` is rendered

2022-02-21 08:16 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis ready for review with a test.

Interesting to note that even though I didn't explicitly use the `subscribe` method, instead used the `$` to access the store value, I still had to mock the subscribe method. Otherwise, the value in the store was `undefined`.

2022-02-21 08:25 UTC, peterpeterparker approved these changes
Thanks for the PR

2022-02-21 08:39 UTC, merged