Add "includeBallotsByCaller" to actionable sns proposals store
dfinity/nns-dapp pull request #4589
Opened 2024-03-05 10:40 UTC by mstrasinskis

# Motivation

This pull request adds the flag `includeBallotsByCaller` to the store, allowing it to be used later to determine which message needs to be displayed.

# Changes

- rename method `setProposals` to `set`
- add `includeBallotsByCaller` to the `actionableProposalsStore`
   Instead of `[rootCanisterId]: undefined`, sns w/o ballots support well be stored as `[rootCanisterId]: { proposals: [], includeBallotsByCaller: false }`
- update logic in `actionableProposalsDerivedStore` to rely on this flag

# Tests

- added `includeBallotsByCaller` to mocks

# Todos

- [ ] Add entry to changelog (if necessary).
Not necessary

2024-03-05 13:44 UTC, daniel-wong-dfinity-org requested changes
This review was written together with David sitting next to me.

2024-03-05 13:44 UTC, daniel-wong-dfinity-org commented on frontend/src/lib/derived/actionable-proposals.derived.ts
> +          includeBallotsByCaller ? [canisterId, proposals.length] : undefined,
I think you need to add a test that covers the case where `includeBallotsByCaller: undefined`. At least, I do not see this being covered yet.

2024-03-05 13:44 UTC, daniel-wong-dfinity-org commented on frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
> +          includeBallotsByCaller: false,
In this case, the mock should return `[]` not `[false]` in order to be more realistic.

2024-03-05 13:44 UTC, daniel-wong-dfinity-org commented on frontend/src/tests/lib/stores/actionable-sns-proposals.store.spec.ts
> +      includeBallotsByCaller: true,
Is false covered?

2024-03-05 16:33 UTC, mstrasinskis commented on frontend/src/lib/derived/actionable-proposals.derived.ts
> +          includeBallotsByCaller ? [canisterId, proposals.length] : undefined,
Good point, thanks! The test data were updated -- https://github.com/dfinity/nns-dapp/pull/4589/files#diff-6b300fbe92e1d0fea32ec15209d80b2105d9bb8f4c23ef08874f0ac3111afc53R135

2024-03-05 16:36 UTC, mstrasinskis commented on frontend/src/tests/lib/services/actionable-sns-proposals.services.spec.ts
> +          includeBallotsByCaller: false,
Thanks, updated. Here is the description https://github.com/dfinity/nns-dapp/pull/4589/files#diff-6b300fbe92e1d0fea32ec15209d80b2105d9bb8f4c23ef08874f0ac3111afc53R132

2024-03-05 16:39 UTC, mstrasinskis commented on frontend/src/tests/lib/stores/actionable-sns-proposals.store.spec.ts
> +      includeBallotsByCaller: true,
I'm not sure if it adds more coverage, but for formality, a sample with the 'false' value was added 👍

2024-03-05 16:50 UTC, dskloetd commented on frontend/src/lib/derived/actionable-proposals.derived.ts
> +          includeBallotsByCaller ? [canisterId, proposals.length] : undefined,
This is a change in behavior in the derived store, right?
So I would expect this additional behavior to be covered in
`actionable-proposals.derived.spec.ts`.
But the only changes I see in that file is changing `setProposals` to `set` and adding `includeBallotsByCaller: true,`.
Shouldn't a test be added where `includeBallotsByCaller` is false and we expect the entry to be absent rather than 0?

2024-03-05 17:04 UTC, mstrasinskis commented on frontend/src/lib/derived/actionable-proposals.derived.ts
> +          includeBallotsByCaller ? [canisterId, proposals.length] : undefined,
Ah, thanks for the explanation. Adding.

2024-03-05 17:13 UTC, dskloetd approved these changes
Thanks!

2024-03-06 16:41 UTC, daniel-wong-dfinity-org approved these changes

2024-03-06 16:56 UTC, merged