L2 266 proposal details page
dfinity/nns-dapp pull request #469
Opened 2022-02-22 22:54 UTC by mstrasinskis

# Motivation

Display basic proposal information.
Initially was started as one task [L2-266](https://dfinity.atlassian.net/browse/L2-266). Later was divided in multiple.  As a result the current implementation contains:
- [Proposal Detail Card](https://dfinity.atlassian.net/browse/L2-268)
- [Adopt/Reject Card](https://dfinity.atlassian.net/browse/L2-269)

# Changes

- new page ProposalDetail
- ProposalDetailCard
- VotesCard

# Note

Fetching logic will be updated soon

# Screens

<img width="1153" alt="Screenshot 2022-02-22 at 23 07 04" src="https://user-images.githubusercontent.com/98811342/155233082-f6372c08-1291-445f-a30f-e7cf57b74ed0.png">

![127 0 0 1_8080_](https://user-images.githubusercontent.com/98811342/155232974-b6060645-eb28-468d-a49c-3b352f90df67.png)

2022-02-23 06:15 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +<Card>
Note in this PR but maybe in the future worth splitting this component in multiple components, it has quite a size

2022-02-23 06:36 UTC, peterpeterparker requested changes
Difficult to review, the PR is quite huge 😲, so a few small comments.

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +        >{`${formatICP({
Can - shall - we ask again the team about the decimals of the ICP? Somewhere I reckon we discussed it weeks ago (before you began) and decided it should also always be 8 decimals.

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposals/ProposalCard.svelte
> +      path: `${AppPath.ProposalDetail}/${proposalInfo.id}`,
you can deconstrusct the `id` on existing line 21

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposals/ProposalCard.svelte
> +<Card on:click={showProposal}>
`<Card role="link"...` ?

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +    @include media.min-width(medium) {
empty?

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  const governance: GovernanceCanister = GovernanceCanister.create();
not sure I should comment this since you might modify it later but it you use the `GovernanceCanister` you need the `identity` and the `createAgent` I think.

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/proposals.services.ts
> +export const proposalIdFromRoute = (): ProposalId | undefined => {
do we have other headless pages than proposals? if yes, it can be a more generic utils `getRouteDetail` or else?

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  }
isn't the `return undefined` missing?

2022-02-23 06:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +export const proposalFirstActionKey = (proposal: Proposal) =>
typescript return type is missing `... = (proposal: Proposal): xxxx`

2022-02-23 07:21 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +        >{`${formatICP({
I noticed that in some places it is quite critical eg ``/#/proposal/46435`
<img width="833" alt="image" src="https://user-images.githubusercontent.com/98811342/155276136-b97e6f6c-e48c-4639-a845-09fb457cf51f.png">

2022-02-23 07:27 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +        >{`${formatICP({
The current width was optimised for 2 digits. Probably we could align the titles to the progress-bar and show the numbers below.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/98811342/155276607-01131025-f355-4f25-af00-16e16da8913b.png">

2022-02-23 07:35 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  const governance: GovernanceCanister = GovernanceCanister.create();
Thanks for reminder, this part is still under construction 🚧

2022-02-23 07:39 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/proposals.services.ts
> +export const proposalIdFromRoute = (): ProposalId | undefined => {
It is used also in `/wallet/123abc123` page. I'll refactor `proposalIdFromRoute` into `getRouteDetail` and validation proposalId function. Good point.

2022-02-23 08:12 UTC, lmuntanerDfinity reviewed
A few comments

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +<script lang="ts">
Do they share (or should) the `article` styles?

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/proposals.services.ts
> +export const proposalIdFromRoute = (): ProposalId | undefined => {
Isn't there a way to access the dynamic parameters of the routes?

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/app-path.utils.ts
> +    [AppPath.ProposalDetail]: `${AppPath.ProposalDetail}/[0-9]+`,
are we confidet they will only be numbers?

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +export const formatICP = ({
why not `formatICP(value, options)`? This way we can separate the mandatory and non-mandatory fields and not change the API of the current usage.

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/route.utils.ts
> +// e.g. #/wallet/123?a=b => wallet/123
why this change in the comment?

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +    const proposalId = proposalIdFromRoute();
why all this logic here in the subscribe function even though we are not using the value from routeStore?

2022-02-23 08:12 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/mocks/proposal.mock.ts
> +} as unknown as ProposalInfo;
why this? `const mockProposalInfo: ProposalInfo` is not enough?

2022-02-23 09:57 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +        >{`${formatICP({
I was confused. These are not ICPs. Going to create separate formatting function suggested by @peterpeterparker.

2022-02-23 10:07 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/common/HeadlessLayout.svelte
> +  <Footer>
Good point. To preserve the same structure for both Layouts I wouldn't change it now. But some refactoring could be useful later. Probably the shadow needs to be extracted from the footer and be part of the layout itself.

2022-02-23 10:15 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +    <a on:click|preventDefault|stopPropagation={showProposerNeuron} href="/"
Because of this warning `A11y: '#' is not a valid href attributesvelte(a11y-invalid-attribute)`. What do you think about using `#_`?

2022-02-23 10:17 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +    <p>{$i18n.proposal_detail.id_prefix} {proposalInfo.id}</p>
Just retested. Looks like it's the prettier default settings 🤷‍♂️

2022-02-23 10:21 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/common/HeadlessLayout.svelte
> +  <Footer>
good point, we don't really need to do it in this project to be honest.

2022-02-23 10:22 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +    <a on:click|preventDefault|stopPropagation={showProposerNeuron} href="/"
LGTM

2022-02-23 10:22 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +    <p>{$i18n.proposal_detail.id_prefix} {proposalInfo.id}</p>
maybe the length  of the one above was in one line...

2022-02-23 10:25 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +<script lang="ts">
Not sure about style sharing. In the future the CardBlock should be optionally collapsible. Better component name suggestions are welcome :)

<img width="879" alt="Screenshot 2022-02-23 at 11 20 24" src="https://user-images.githubusercontent.com/98811342/155300775-3816b2ae-7dfd-467b-a61c-b7e821e969b9.png">

2022-02-23 10:33 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +<script lang="ts">
Oh, I didn't understood it well. This is perfect then, thanks!

2022-02-23 11:03 UTC, mstrasinskis commented on frontend/svelte/src/tests/mocks/proposal.mock.ts
> +} as unknown as ProposalInfo;
There are much more fields in ProposalInfo object. But they are not relevant for tested components.

2022-02-23 11:44 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/mocks/proposal.mock.ts
> +} as unknown as ProposalInfo;
ok, thanks for the clarification. maybe a comment to understand it?

2022-02-23 13:04 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/app-path.utils.ts
> +    [AppPath.ProposalDetail]: `${AppPath.ProposalDetail}/[0-9]+`,
yep
<img width="339" alt="image" src="https://user-images.githubusercontent.com/98811342/155324803-be5c0b86-20b5-4522-bd70-7ad729a7d0b6.png">

2022-02-23 13:39 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/route.utils.ts
> +// e.g. #/wallet/123?a=b => wallet/123
Valid point. It's a comment update, no code changes. I would say this change doesn't deserve its own PR.

2022-02-23 13:44 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/app-path.utils.ts
> +    [AppPath.ProposalDetail]: `${AppPath.ProposalDetail}/[0-9]+`,
👍

2022-02-23 13:45 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/route.utils.ts
> +// e.g. #/wallet/123?a=b => wallet/123
Agree that it doesn't deserve its own PR, I am just wondering why the change in the comment, hehe. What query params are used?

2022-02-23 14:01 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +    max-height: 300px;
Agree. It could depend on collapsible implementation. I added a comment and updated the task description to not forget it.

2022-02-23 14:04 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  }
Added for readability 👍

2022-02-24 12:43 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +export const formatICP = ({
Your suggestion was applied to formatNumber util function.

2022-02-25 15:29 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  const governance: GovernanceCanister = GovernanceCanister.create();
done

2022-02-25 15:33 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/proposals.services.ts
> +export const proposalIdFromRoute = (): ProposalId | undefined => {
@lmuntanerDfinity As I know there is no functionality like this.
@peterpeterparker Instead of `getRouteDetail` (it's just `path.split("/").pop()`) getProposalId function was added -- https://github.com/dfinity/nns-dapp/pull/469/files#diff-60c180d8fc2c4be28fe38b6f33fcf692ffa3467223282115a198ec5a537c02b7R132

2022-02-25 15:41 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +<Card>
A jira task was added 👍

2022-02-25 15:43 UTC, mstrasinskis commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +    const proposalId = proposalIdFromRoute();
Switched to store value. Good point. Let the store be the source of true.

2022-02-25 15:45 UTC, mstrasinskis reviewed
Is blocked by nns_js PR -- https://github.com/dfinity/nns-js/pull/37

2022-02-25 15:50 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +<Card>
thanks!

2022-02-28 13:20 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +    <a on:click|preventDefault|stopPropagation={showProposerNeuron} href="#_"
any particular reason to use a link here instead of a `button` since there is not navigation and only click?

2022-02-28 13:29 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +    const proposalId = getProposalId(path);
shouldn't `unsubscribe` be generally called once at the begin of the function because the code has to run one time only?

2022-03-01 09:53 UTC, mstrasinskis commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +    const proposalId = getProposalId(path);
Depends on how we need to support hash change for that page. Because w/ initial `unsubscribe` call there will be no feedback on proposalId change in url.

2022-03-01 09:53 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard.svelte
> +    <a on:click|preventDefault|stopPropagation={showProposerNeuron} href="#_"
Good point. Updated 👍

2022-03-01 11:27 UTC, peterpeterparker approved these changes
LGTM, thanks!

If it would need improvements, let's provide these in separate PRs later on.

2022-03-01 11:38 UTC, merged