L2 301 lm fetch accounts subaccounts init
dfinity/nns-dapp pull request #484
Opened 2022-02-24 06:23 UTC by lmuntanerDfinity

# Motivation

Fetch account and subaccount details and render them in Accounts page.

# Changes

# Tests

2022-02-24 12:50 UTC, lmuntanerDfinity commented
Screenshot of subaccounts

![Screenshot 2022-02-24 at 13 50 12](https://user-images.githubusercontent.com/98735375/155527328-63378514-667e-422b-bfd9-d0e71369a256.png)

2022-02-24 12:51 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-02-25 08:18 UTC, mstrasinskis reviewed
Looks good. A couple of comments to discuss.

2022-02-25 08:18 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +export const addICPs = (...icps: ICP[]): ICP =>
Suggestion `sumICPs`

2022-02-25 08:18 UTC, mstrasinskis commented on frontend/svelte/src/routes/Accounts.svelte
> +      accounts?.main?.balance || zeroICPs,
What is the default value of balance? Or it's not present if empty?

2022-02-25 08:18 UTC, mstrasinskis commented on frontend/svelte/src/tests/lib/modals/AddAccountModal.spec.ts
> +// prettier-ignore
why? 😄

2022-02-25 08:19 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      certified: false,
It was like this before, I didn't want to change it. Maybe @peterpeterparker on Monday can explain us why.

2022-02-25 08:21 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Accounts.svelte
> +      accounts?.main?.balance || zeroICPs,
`balance` is always present. But there might not be `accounts` and `accounts.main`, thus the `|| zeroICPs`.

2022-02-25 08:21 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/lib/modals/AddAccountModal.spec.ts
> +// prettier-ignore
oh, I can remove it

2022-02-25 08:22 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/icp.utils.ts
> +export const addICPs = (...icps: ICP[]): ICP =>
sure, not a strong opinion.

2022-02-25 09:27 UTC, mstrasinskis commented on frontend/svelte/src/routes/Accounts.svelte
> +      accounts?.main?.balance || zeroICPs,
Thanks, I was just curious.

2022-02-28 06:22 UTC, peterpeterparker requested changes

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/App.svelte
> +      if (auth.identity) {
- why this check and where the accounts reset now happens on logout?

- goodie: code style, I tend to rather like not to wrap code with if, think it's more readable

```
if (!auth.identity) {
   return;
}

await syncAccounts...
```

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/App.svelte
>      }
not related to your PR, errors are not cached and displayed. we should add a `// TODO` about it and implement this in another PR

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/accounts/AccountCard.svelte
> +  export let role: "button" | "link" | undefined = undefined;
can you provide this in another PR, it is not related to this subject

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
> +      let labelKey = "create_subaccount";
goodie: you can inline this and make `labelKey` a `const`

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/accounts.services.ts
> +  await nnsDapp.addAccount();
- so this does not always create an account, do I get it right?

- did you definitely find an answer to the question "should nns-dapp create the main account if it does not exist and is that correct, a main account can potentially not exist the first time a user sign in nns-dapp"?

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      certified: false,
It was implemented early on, before the subject "should the calls be done in a certified way or not" was discussed. It should probably be certified now.

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      name: "name" in account ? account.name : undefined,
why checking `name in`? if not in, then it is `undefined` no?

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/accounts.services.ts
> +    account: AccountDetails | SubAccountDetails
destruct? `{account_identifier, name}: AccountDetails | SubAccountDetails`

2022-02-28 06:22 UTC, peterpeterparker commented on frontend/svelte/src/routes/Accounts.svelte
> +    totalBalance = sumICPs(
do we display the sum of icps for the accounts somewhere else in the app?
if yes, might be worth to extract a function

2022-02-28 06:24 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      certified: false,
ok, I can change it.

2022-02-28 06:27 UTC, lmuntanerDfinity commented on frontend/svelte/src/App.svelte
> +      if (auth.identity) {
The logout resets all the state by refreshing the page:

```
// We reload the page to make sure all the states are cleared
window.location.reload();
```

I will change the if statement.

2022-02-28 06:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/accounts/AccountCard.svelte
> +  export let role: "button" | "link" | undefined = undefined;
I was working with Accounts, I saw that the account card was not using a cursor, therefore I changed it.

I can remove it. But I normally like fixing small things in PRs even though they are not related. Maybe something to discuss if we want to allow small fixes on unrelated things or not. I will remove it.

2022-02-28 06:31 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
> +      let labelKey = "create_subaccount";
It can change value below, hence the `let`.

2022-02-28 06:36 UTC, peterpeterparker commented on frontend/svelte/src/App.svelte
> +      if (auth.identity) {
> ... to make sure ...

Never to sure ;) all good thanks.

2022-02-28 06:39 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +  await nnsDapp.addAccount();
* yes, it does not create if it already exists: [add_account](https://github.com/dfinity/nns-dapp/blob/main/rs/src/accounts_store.rs#L271)

* I didn't get confirmation from anyone, I looked into the [code](https://github.com/dfinity/nns-dapp/blob/main/rs/src/accounts_store.rs#L232):

```
            // If the principal is empty, return None so that the browser will call add_account
            // which will allow us to set the principal.
```

2022-02-28 06:39 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
> +      let labelKey = "create_subaccount";
> you can inline this

const labelKey = something ? something : something ? something : something;

2022-02-28 06:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +      name: "name" in account ? account.name : undefined,
here the account can be an AccountDetails, that doesn't have the `name` property. In JS trying to access a property that does not exist is ok, but Tyescript does not allow me to do that. That's why I added the `in` and also the comment. Because it was not clear why I was doing it.

2022-02-28 06:42 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +    account: AccountDetails | SubAccountDetails
I can't do it with `name` since it doesn't exit in AccountDetails.

2022-02-28 06:43 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Accounts.svelte
> +    totalBalance = sumICPs(
Not that I know of. But we might show additions of ICPs, which is why I created the `sumICPs` helper.

2022-02-28 06:47 UTC, lmuntanerDfinity commented
@peterpeterparker pushed changes and replied to your comments, remember that this PR is blocked by https://github.com/dfinity/nns-js/pull/44 if you could also take a look there. thanks!

2022-02-28 06:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/AddAccountModal/AddNewAccount.svelte
> +      let labelKey = "create_subaccount";
I usually don't like two ternary operators on the same line, but if here is the pattern I can do it.

2022-02-28 07:30 UTC, lmuntanerDfinity commented
@peterpeterparker this is not blocked by any other PR, sorry, I confused PRs. Ready for another review.

2022-02-28 08:15 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/accounts.services.ts
> +  await nnsDapp.addAccount();
Thanks for checking this.

Can you add these two references - the same comment as you added here above - within the code?

2022-02-28 08:18 UTC, peterpeterparker approved these changes
LGTM.

Before merge please just add the comments and links to code regarding `addAccount`, thx.

2022-02-28 08:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/accounts.services.ts
> +  await nnsDapp.addAccount();
yes, good idea!

2022-02-28 08:43 UTC, merged