chore: introduce decoding quota to http_request in SNS aggregator canister
dfinity/nns-dapp pull request #5004
Opened 2024-06-06 07:16 UTC by mraszyk

This PR introduces the decoding quota to the `http_request` method of the SNS aggregator canister. Setting a decoding quota of 10000 (corresponding to roughly 10KB of decoded data incl. overhead) prevents the SNS aggregator canister from wasting instructions on parsing large HTTP requests which are not expected to be used (the SNS aggregator supports GET requests for its assets and thus no HTTP requests should be larger than a few KB). I've tested the MR manually using dfx (successfully retrieving the candid interface and the landing page and failing to make a large HTTP request which is what this PR addresses).

2024-06-06 10:46 UTC, bitdivine approved these changes

2024-07-15 06:13 UTC, dskloetd commented
@anchpop and @aterga would probably be the right people to review this.

2024-08-20 14:54 UTC, aterga commented on CHANGELOG-Sns_Aggregator.md
> +- Decoding quota of 10,000 in the `http_request` method.
```suggestion
- Decoding quota of 10,000 bytes in the `http_request` method.
```
?

2024-08-20 14:56 UTC, aterga commented on rs/sns_aggregator/src/lib.rs
> +#[ic_cdk_macros::query(decoding_quota = 10000)]
Could you explain in a comment where does this quota come from, please?

2024-08-20 15:00 UTC, aterga requested changes
LGTM modulo testing — could we please add a test to demonstrate that the `http_request` function works expectedly with inputs that (1) meet quota and (2) exceed quota by 1?

I see from the description that you've already tested this manually, I think that's enough in this case. Approving

2024-08-20 15:01 UTC, mraszyk commented on CHANGELOG-Sns_Aggregator.md
> +- Decoding quota of 10,000 in the `http_request` method.
The decoding quota follows its own [cost](https://github.com/dfinity/candid/blob/f324a1686d6f2bd4fba9307a37f8e3f90cc7222b/rust/candid/src/de.rs#L170) model, i.e., it is not expressed in bytes.

2024-08-20 15:03 UTC, aterga approved these changes

2024-08-21 12:09 UTC, mraszyk commented on rs/sns_aggregator/src/lib.rs
> +#[ic_cdk_macros::query(decoding_quota = 10000)]
Done: [60b7d1d](https://github.com/dfinity/nns-dapp/pull/5004/commits/60b7d1dd9b27e58001a5f1313c286e7464dd477e)

2024-08-21 13:07 UTC, aterga commented on CHANGELOG-Sns_Aggregator.md
> +- Decoding quota of 10,000 in the `http_request` method.
Would it make sense in the doc to explain what the unit means?

2024-08-21 13:10 UTC, aterga commented on CHANGELOG-Sns_Aggregator.md
> +- Decoding quota of 10,000 in the `http_request` method.
I think the explanation you've added in the code is enough, thanks!

2024-08-21 13:10 UTC, aterga approved these changes

2024-08-21 13:28 UTC, merged