L2 283 lm my votes block
dfinity/nns-dapp pull request #524
Opened 2022-03-04 06:47 UTC by lmuntanerDfinity

# Motivation

* Add user votes in proposal details

# Changes

* VotesCard reads neurons store and filters the ones that voted.
* VotesCard renders data about each neuron and vote.

# Tests

* Update VotesCard test.

2022-03-04 06:47 UTC, lmuntanerDfinity commented
Screenshot

![Screenshot 2022-03-03 at 16 13 15](https://user-images.githubusercontent.com/98735375/156713556-b7bf7f0d-62e1-4c48-8de4-1e351d7d277f.png)

2022-03-04 06:48 UTC, lmuntanerDfinity commented on frontend/svelte/env.config.mjs
> -  (development ? "qhbym-qaaaa-aaaaa-aaafq-cai" : "qoctq-giaaa-aaaaa-aaaea-cai");
Change because the canister id changed with a new testnet deployment.

We need to do https://dfinity.atlassian.net/browse/L2-265 to avoid this in the future.

2022-03-04 06:48 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-03-04 07:48 UTC, mstrasinskis requested changes
Looks good. Just a couple of comments.

2022-03-04 07:48 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  neuronsStore.subscribe((neurons) => {
`unsubscribe` or `$: ...`?

2022-03-04 07:48 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +      votingPower: Number(votingPower) / E8S_PER_ICP,
Could you plz insert a comment before `// TODO: replace w/ formatVotingPower()`?

2022-03-04 07:48 UTC, mstrasinskis commented on frontend/svelte/src/lib/stores/neurons.store.ts
> +export type NeuronsStore = NeuronInfo[];
👍

2022-03-04 08:24 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  neuronsStore.subscribe((neurons) => {
let me try again, it wasn't working, but maybe I wasn't using it properly.

2022-03-04 08:24 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +      votingPower: Number(votingPower) / E8S_PER_ICP,
👍

2022-03-04 08:33 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  neuronsStore.subscribe((neurons) => {
I don't know what I was doing, but now it worked.

2022-03-04 08:34 UTC, lmuntanerDfinity commented
@mstrasinskis ready for another review

2022-03-04 08:42 UTC, mstrasinskis approved these changes
LGTM

2022-03-04 09:18 UTC, merged

2022-03-07 05:53 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  type CompactNeuronInfo = {
shouldn't this be an `interface` not a `type` @lmuntanerDfinity ?

2022-03-07 06:20 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  type CompactNeuronInfo = {
Do we have a preference? I felt I saw `type` being used for this. I don't mind.

2022-03-07 06:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  type CompactNeuronInfo = {
I always use `interface` for object. Open to discussion. Can we have an eslint rule?

2022-03-07 06:57 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/proposal-detail/VotesCard.svelte
> +  type CompactNeuronInfo = {
Yes, we could.