L2-312: Setup Eslint Bundle
dfinity/nns-dapp pull request #525
Opened 2022-03-04 07:49 UTC by lmuntanerDfinity

# Motivation

Add eslint rules.

# Changes

* Add bundle of rules to eslint.
* Add eslint ignore file.
* Fix a few style issues.

2022-03-04 07:50 UTC, lmuntanerDfinity commented
@mstrasinskis @peterpeterparker @bitdivine please review

2022-03-04 07:51 UTC, lmuntanerDfinity commented
We have:

```
263 problems (226 errors, 37 warnings)
6 errors and 0 warnings potentially fixable with the `--fix` option.
```

Let's take it easy.

2022-03-04 09:17 UTC, bitdivine approved these changes
No objections but please wait until others have reviewed as well.

2022-03-04 09:17 UTC, bitdivine commented on frontend/svelte/.eslintrc.js
> +    "plugin:@typescript-eslint/recommended-requiring-type-checking",
One idea:  Can we introduce these one at a time?  I.e. add one rule, fix everything over the next few days, add the next and so on?

A second point:  Beware the type checking.  I am all in favour of requiring ts types, however when I first pitched in with svelte I tried adding types everywhere and in some cases the linter would require a type annotation but the svelte parser choked on the annotation.  There was an open svelte issue about this.  I don't have the link and perhaps this has been fixed.  We can hope! :-)

2022-03-04 09:17 UTC, bitdivine commented on frontend/svelte/.eslintrc.js
> +    node: true,
What does that do in this context?

2022-03-04 09:43 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +    node: true,
For example, it recognizes `process` instead of raising an error as a not defined variable.

2022-03-04 09:53 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +    "plugin:@typescript-eslint/recommended-requiring-type-checking",
I haven't got any weird type annotation needed that the svelte parse had problems with.

But I removed the types part for now. I like the idea of introducing it per parts.

With only the recommended eslint rules we have `67 problems (30 errors, 37 warnings)`.

We need to add `eslint:recommended` together with `plugin:@typescript-eslint/recommended`. This is the recommendation in the typescript-eslint plugin [docs](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/eslint-plugin#usage).

2022-03-04 12:24 UTC, nmattia commented on frontend/svelte/.eslintrc.js
> +  rules: {
How about adding the ones used in II as well? https://github.com/dfinity/internet-identity/blob/33950f4518b0acd2691d6e2a52d687b3b540d408/.eslintrc.json#L12-L19

2022-03-04 12:26 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +  rules: {
looks good to me and it keeps consistency across projects, so perfect. Thanks!

2022-03-04 15:39 UTC, nmattia approved these changes
Rubber stamping; please check with @peterpeterparker for details!

2022-03-04 15:59 UTC, mstrasinskis commented on frontend/svelte/src/tests/routes/Accounts.spec.ts
> +    titleRow &&
Generally speaking about this approach, doesn't this change the logic of tests that if the component isn't presented in the DOM the test wouldn't fail?

2022-03-04 17:37 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/routes/Accounts.spec.ts
> +    titleRow &&
done! thanks for the call!

2022-03-04 20:20 UTC, mstrasinskis approved these changes
LGTM. Thanks 👍

2022-03-07 06:22 UTC, peterpeterparker commented on frontend/svelte/.eslintrc.js
> +    "eslint:recommended",
In sveltekit they also extends prettier per default

```
extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'prettier'],
```

something we also want?

2022-03-07 06:25 UTC, lmuntanerDfinity commented on frontend/svelte/.eslintrc.js
> +    "eslint:recommended",
I don't mind.

Here I also didn't integrate yet the type-checking to do it in smaller PRs.

I can create a PR to add "prettier" as well.

2022-03-07 06:34 UTC, peterpeterparker requested changes
A couple of questions

2022-03-07 06:34 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/dev.services.ts
> +  if (!main) {
that's a logic change not eslint. should it be safely ignored or should an error be throw because such use case should not be reached?

2022-03-07 06:34 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/dev.services.ts
> +  if (identity) {
as previous comment

2022-03-07 06:34 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  if (pathDetail === undefined) {
as previous comment

2022-03-07 06:34 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +  return Object.entries(proposal.action?.[key])
that will throw an error no? `Object.entries(undefined)` throw an error

2022-03-07 06:34 UTC, peterpeterparker commented on frontend/svelte/src/tests/mocks/canisters.store.mock.ts
> -import { NNSDappCanister } from "../../lib/canisters/nns-dapp/nns-dapp.canister";
why removed in this PR?

2022-03-07 06:34 UTC, peterpeterparker commented on frontend/svelte/src/tests/mocks/ledger.canister.mock.ts
> -import { AccountIdentifier, ICP, LedgerCanister } from "@dfinity/nns";
why removed in this PR?

2022-03-07 06:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/dev.services.ts
> +  if (!main) {
it would throw an error if it doesn't despite eslint, so I can throw an error here.

Although, this is somethig we need to fix at a broad level as well. How do we handle session expiration at the app level?

2022-03-07 06:41 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +  return Object.entries(proposal.action?.[key])
same as before

2022-03-07 06:42 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/mocks/canisters.store.mock.ts
> -import { NNSDappCanister } from "../../lib/canisters/nns-dapp/nns-dapp.canister";
there were some `null` types in the mock and it was easier to do the test with `jest-extended-mock` than to fix the nul l type errors in the mock.

2022-03-07 06:42 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/mocks/ledger.canister.mock.ts
> -import { AccountIdentifier, ICP, LedgerCanister } from "@dfinity/nns";
Ditto, there were some `null` type errors that were needed to be solved. But it was easier to use `jest-extended-mock` than to fix the type issues in the mock.

2022-03-07 06:44 UTC, peterpeterparker commented
Regarding rules these are the one I would spontaneously to suggest:

- no-else-return
- no-continue
- prefer-const
- prefer-destructuring

We can of course discuss about it. We shall also discuss the thematic "implicit vs explicit typing" (object-shorthand I guess).

2022-03-07 06:54 UTC, lmuntanerDfinity commented
@peterpeterparker since we are going to start working, can we add these rules in another PR? This touches a lot of files and we don't want to start getting into conflicts.

If I had known your preference on the rules I would have added them to this PR.

2022-03-07 06:56 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  if (pathDetail === undefined) {
I tried, and if pathDetail is undefined, parseInt returns NaN, therefore the `isFinite` returns false and the whole function returns `undefined`. There is no change in logic.

2022-03-07 07:06 UTC, peterpeterparker commented
@lmuntanerDfinity sure definitely in another PR 👍

2022-03-07 07:07 UTC, peterpeterparker commented on frontend/svelte/.eslintrc.js
> +    "eslint:recommended",
another pr sounds good 👍

2022-03-07 07:08 UTC, lmuntanerDfinity commented
@peterpeterparker please review

I create the new Jira issue to discuss and to add new rules once we fix the ones we have here: https://dfinity.atlassian.net/browse/L2-347

2022-03-07 07:21 UTC, peterpeterparker requested changes

2022-03-07 07:21 UTC, peterpeterparker commented on frontend/svelte/src/routes/NeuronDetail.svelte
> +{#if showThisRoute}
this is not related to eslint right or is it?

2022-03-07 07:25 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/NeuronDetail.svelte
> +{#if showThisRoute}
no, it was broken though. The previous commit added a refactor on `REDIRECT_TO_LEGACY`

2022-03-07 07:26 UTC, peterpeterparker commented on frontend/svelte/src/routes/NeuronDetail.svelte
> +{#if showThisRoute}
@lmuntanerDfinity can you then provide the fix in a separate PR?

2022-03-07 07:27 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/NeuronDetail.svelte
> +{#if showThisRoute}
`main` is broken withuot this change, I couldn't check that everything was still working witoht this fix.

2022-03-07 07:52 UTC, lmuntanerDfinity commented
@peterpeterparker changes in REDIRECT_TO_LEGACY merged from `main`.

2022-03-07 07:59 UTC, peterpeterparker approved these changes

2022-03-07 08:33 UTC, merged