fix: stringify all proposalActionFields
dfinity/nns-dapp pull request #526
Opened 2022-03-06 14:12 UTC by mstrasinskis

# Motivation

Currently only the payload was stringified. It appears that other fields could also contain objects (screenshot)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/98811342/156926891-42ed2107-762b-4023-b319-20338877d4e7.png">

# Changes

- apply stringifyJson to all fields
- update post-formatting to simulate flutter dapp

# Tests

- TBD

2022-03-07 06:16 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +      if (asText?.length) {
- the test might not needed I think, you can use the `?` on each `asText = asText?.replace`

- can we extract the "remove redundant wrappers" in a function?

2022-03-07 06:18 UTC, peterpeterparker requested changes

2022-03-07 06:18 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +      let asText = stringifyJson(value, { indentation: 2 });
- the test might not needed I think, you can use the `?` on each `asText = asText?.replace`

- can we extract the "remove redundant wrappers" in a function?

2022-03-07 06:23 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +      let asText = stringifyJson(value, { indentation: 2 });
agree with extracting it to a function, then it will be easy to test.

2022-03-08 11:09 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +      let asText = stringifyJson(value, { indentation: 2 });
Not sure about separate function because it will pollute the global scope w/ a temporary solution. A test for formatting was added 👍

2022-03-08 11:39 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +      let asText = stringifyJson(value, { indentation: 2 });
Then a local function? 

When I read the code, I first notice many lines in a .map but don't get their context until I read the comments and code.

If I read `.map(removeRedundantWrappers)` then I get the context instantly.

2022-03-08 15:26 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +      let asText = stringifyJson(value, { indentation: 2 });
Refactoring is done. Thanks, much cleaner 👍

2022-03-08 18:55 UTC, merged

2022-03-08 18:56 UTC, peterpeterparker commented
@mstrasinskis I have merged it so everything is in for the demo, hope you don't mind