🚧 WIP: L2 281 cast vote card
dfinity/nns-dapp pull request #527
Opened 2022-03-06 14:47 UTC by mstrasinskis

# Motivation

The user should be able to register votes

**Steps:**
1. select available neurons
2. chose vote type (Adopt|Refect)
3. confirm the choice

# Changes

- update ProposalDetail to fetch neurons on mount
- update Modal should not render a title block if empty
- add CastVoteCard register-vote functionality
- add ConfirmationModal (general usage)
- add VoteConfirmationModal (based on ConfirmationModal)
- add proposals.services / castVote - make multiple updates
- add button.danger (the pink one)
- add proposals.utils / formatVotingPower function
- add i18n.utils / replacePlaceholders function
- add utils / uniqObjects function

# Tests

In progress

# Screens

## Mobile

![image](https://user-images.githubusercontent.com/98811342/156927561-1043cca2-372e-4fee-88bb-f83f3dae1748.png)

## Desktop

![image](https://user-images.githubusercontent.com/98811342/156927597-83e4ceaa-1ffb-4278-ad76-659609229b5a.png)

## Confirm Adopt

<img width="956" alt="image" src="https://user-images.githubusercontent.com/98811342/156927692-5edd473e-8b9d-4900-82d7-b0392a31588d.png">

## Confirm Reject

<img width="428" alt="image" src="https://user-images.githubusercontent.com/98811342/156927711-c3b6351f-c30b-4421-affe-0f6eaa7bde9e.png">

## Confirm Mobile

<img width="374" alt="image" src="https://user-images.githubusercontent.com/98811342/156927728-9fca975a-c89f-472f-a6d8-bdb9448f5ef6.png">

2022-03-07 06:18 UTC, lmuntanerDfinity reviewed
Just some comments, looking very good!

2022-03-07 06:18 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/ConfirmationModal.svelte
> +<script lang="ts">
Good idea, I bet we are going to reuse this a lot!

2022-03-07 06:18 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/proposals.services.ts
> +    throw new Error(get(i18n).error.missing_identity);
We also need a way to check globally for expired session. But in another task.

2022-03-07 06:18 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/i18n.utils.ts
> +export const replacePlaceholders = (
👏

2022-03-07 06:18 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/i18n.utils.ts
> + * ("Why $1?", {$1: "World", Why: "Hallo", "?": "!"}) => "Hello World!"
`Why: "Hello"` or result is `"Hallo World!"`, hehe.

2022-03-07 06:18 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +        <CastVoteCard {proposalInfo} neurons={$neuronsStore} />
Oh, I thought we agreed the component would access the store, now I am not sure anymore. I think that `VotesCard` I did was accessing the store directly. I don't mind it. Can you also change `VotesCard` then?

2022-03-07 10:33 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/i18n.utils.ts
> + * ("Why $1?", {$1: "World", Why: "Hallo", "?": "!"}) => "Hello World!"
I hope the result is `"Hello World!"` but i'll recheck this w/ a test 😉

2022-03-07 10:34 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/i18n.utils.ts
> + * ("Why $1?", {$1: "World", Why: "Hallo", "?": "!"}) => "Hello World!"
Damn, a type 🤦‍♂️

2022-03-07 10:35 UTC, mstrasinskis commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +        <CastVoteCard {proposalInfo} neurons={$neuronsStore} />
Sorry, forgot about this. I'll refactor my code 👍

2022-03-07 10:40 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/proposal-detail/CastVoteCard.svelte
> +      const errors = await castVote({
Reminder: to discuss w/ the team.

2022-03-07 10:42 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/i18n.utils.ts
> + * ("Why $1?", {$1: "World", Why: "Hallo", "?": "!"}) => "Hello World!"
Thanks, fixed! 👍

2022-03-08 10:51 UTC, peterpeterparker requested changes
That's quite a PR, lots of cool stuffs 👍

Few comments and questions.

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/CastVoteCard.svelte
> +      {#each notVotedNeurons as { neuronId, votingPower }}
this component has quite a size, is it a lot of work to extract the  notvotedneuron and maybe toolbar (yes / no) to dedicated components?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/proposal-detail/ProposalDetailCard/ProposalDetailCard.svelte
> +  export let proposalInfo: ProposalInfo | undefined;
then it can crash on line 21 no?

```
$: ({ proposal, status = ProposalStatus.PROPOSAL_STATUS_UNKNOWN } =
    proposalInfo);
 ```

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/ConfirmationModal.svelte
> +        data-test="confirm-no"
I pinged @lmuntanerDfinity about using `data-test` too. We shall discuss it before using these.

- do we want to use attributes for testing purpose?
- if yes, shall we use `data-test` and should we have some rule to be sure it is the only key we use?
- do we want to have `data-test` attributes within the DOM in production or do we want to clean up the code between e2e test and deploy?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +    aria-labelledby={showToolbar ? "modalTitle" : undefined}
out of curiosity, the `aria-labelledby` is not rendered in the DOM or is rendered as `<...aria-labelledby` when set to undefined?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/proposals/VoteConfirmationModal.svelte
> +      <svelte:component this={IconThumbUp} />
any particular reason why using `svelte:component` here?

`<svelte:component this={IconThumbUp} />` vs `<IconThumbUp />`

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  if (!identity) {
you can add `// TODO: https://dfinity.atlassian.net/browse/L2-346` here

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/proposals.services.ts
> +  return Promise.all(
should it be promise.all or promise.allSettled?  what happens if there are three votes like the first is ok, the second is error, the third did not happen?

not linked to code, more a question to be sure it can't end in a shaky state

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/busy.store.ts
> +export type BusyStateInitiator = "vote" | "test";
test? for testing purpose or?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/stores/busy.store.ts
> +const initBusyStore = () => {
since the busy component covers the all screen, to simplify thing, isn't actually the state just a boolean?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +  if (summary?.length === 0) return "";
if summary is optional, it should also be declared as optional

if summary is not optional, you probably don't need this check

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/utils.ts
> +export const uniqObjects = <T>(list: T[]): T[] => {
typo maybe? uniq vs unique

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/utils.ts
> +    uniqHashes.add(hash);
not a functional programming expert but modifying external values (such as `uniqHashes`) within filter or map functions might not be a best practice. can we avoid this?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +    await listNeurons();
add `// TODO catch errors`?

2022-03-08 10:51 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +        <CastVoteCard {proposalInfo} {neurons} />
goodie: if only used in CastVoteCard, why not loading the neurons only in that card? 

aka should we already display the rest while the neurons are loading?

2022-03-08 12:33 UTC, peterpeterparker approved these changes
LGTM

2022-03-08 14:46 UTC, merged