Fix: Neurons Route Test
dfinity/nns-dapp pull request #531
Opened 2022-03-07 09:24 UTC by lmuntanerDfinity

# Motivation

Neurons Route test was passing for the wrong reasons.

# Changes

* Add `data-test` to Card, and NeuronCard to identity cards in tests.
* Changes in Neurons route test.
* Reuse the neurons subscribe mock in multiple tests.
* Fixed some style issues.

# Tests

All changes are in the tests.

2022-03-07 09:24 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-03-07 16:02 UTC, peterpeterparker requested changes

2022-03-07 17:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +<Card {role} on:click {ariaLabel} dataTest="neuron-card">
The problem was that before I was relying on the `a`, and it was failing. Using a more specific but still generic selector can have the same problem.

Shall I create an issue to look into this?

2022-03-07 17:04 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Card.svelte
> +  $: clickable = role !== undefined ? ["button", "link"].includes(role) : false;
Yes

2022-03-07 17:06 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/routes/Neurons.spec.ts
> +    const anchor = container.querySelector('[data-test="neuron-card"]');
good idea!

2022-03-07 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +    neuron.state === NeuronState.DISSOLVING &&
I create an issue and added a comment above these lines.

2022-03-07 17:50 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis ready for another review

2022-03-08 06:46 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/NeuronCard.svelte
> +<Card {role} on:click {ariaLabel} dataTest="neuron-card">
Removed data-test dependence

2022-03-08 07:14 UTC, peterpeterparker approved these changes
LGTM

2022-03-08 07:44 UTC, mstrasinskis approved these changes
Thanks!

2022-03-08 09:10 UTC, merged