L2 330 lm update neuron delay
dfinity/nns-dapp pull request #538
Opened 2022-03-07 13:39 UTC by lmuntanerDfinity

# Motivation

Functionality to updating neuron delay after creating a new neuron.

# Changes

* Neuron service `updateDelay`.
* Update Delay in SetDissolveDelay component

# Tests

* Add tests for service `updateDelay`.
* Updated test in CreateNeuronModal to update the delay calles the service.

2022-03-07 13:40 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-03-07 14:32 UTC, mstrasinskis requested changes
Looks good, just a couple of comments.

2022-03-07 14:32 UTC, mstrasinskis commented on frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
> +        disabled={amount === undefined || amount <= 0 || creating}
Probably the previous variant is more reliable... If the Input default type will be changed to be "text" disabled state would be broken. Another solution would be to set type=number to the Input.

2022-03-07 14:38 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +    {#if currentStep === Steps.SetDissolveDelay && newNeuronId}
I did the `neuronId` in the `SetDissolveDelay` mandatory.

This would fall into error management. Not sure which way to follow. I will create an issue to keep working on this as well as you other comment on the topic.

2022-03-07 14:38 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
> +      // TODO: Manage errors
I will add one.

2022-03-07 14:39 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
> +    updateDelayButton && (await fireEvent.click(updateDelayButton));
it would fall here: `expect(updateDelayButton?.getAttribute("disabled")).toBeNull();`, and it did. `undefined` is not `null`, hehe.

2022-03-07 15:02 UTC, mstrasinskis commented on frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
> +    updateDelayButton && (await fireEvent.click(updateDelayButton));
not sure, because querySelector return null by default

2022-03-07 15:04 UTC, mstrasinskis commented on frontend/svelte/src/tests/lib/modals/CreateNeuronModal.spec.ts
> +    updateDelayButton && (await fireEvent.click(updateDelayButton));
ah, correct. Yep plz ignore

2022-03-07 15:07 UTC, mstrasinskis approved these changes
LGTM

2022-03-07 15:48 UTC, peterpeterparker requested changes

2022-03-07 15:48 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  const goToDissolveDelay = (event: CustomEvent<{ neuronId: NeuronId }>) => {
I read somewhere it's a bad practice to use  `event` because it gets transpiled and conflicts with native `event` or something. So just in case I would use `eventSomething` or destruct `{detail}`

2022-03-07 15:48 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +    newNeuronId = event.detail.neuronId;
I gonna play the paranoiac here: is it possible that actually `stateStep.next();` is faster than `newNeuronId` has re-rendered the view therefore leading to an issue in the cmp `SetDissolveDelay` because it has to be rendered briefly with a neuronId equals to undefined - i.e. shoudl the cmp `SetDissolveDelay`  handles `neuronId` equals to `undefined`?

2022-03-07 15:48 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
> +      dispatcher("nnsNext");
you've got twice `dispatcher("nnsNext");` in the cmp, worth a function?

2022-03-07 15:48 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
> +      syncAccounts({ identity: $authStore.identity as Identity });
can you rather add a check and test (with the todo as the other usage of the identity) on the identity rather than casting it?

2022-03-07 16:04 UTC, mstrasinskis commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  const goToDissolveDelay = (event: CustomEvent<{ neuronId: NeuronId }>) => {
We could also update our eslint ruleset (`"id-denylist": [2, "event"]`) accordingly.

2022-03-08 09:00 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +    newNeuronId = event.detail.neuronId;
if that happens, the worst case scenario is that the modal won't render anything until `neuronId` is set. The if statement handles that there is a neuronId:

```
{#if currentStep === Steps.SetDissolveDelay && newNeuronId}
```

2022-03-08 09:00 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
> +      dispatcher("nnsNext");
not for me.

2022-03-08 09:01 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/StakeNeuron.svelte
> +      syncAccounts({ identity: $authStore.identity as Identity });
ok

2022-03-08 09:15 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  const goToDissolveDelay = (event: CustomEvent<{ neuronId: NeuronId }>) => {
@mstrasinskis add the rule to the Jira, I like it! https://dfinity.atlassian.net/browse/L2-347

2022-03-08 09:15 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  const goToDissolveDelay = (event: CustomEvent<{ neuronId: NeuronId }>) => {
@mstrasinskis add the rule to the Jira, I like it! https://dfinity.atlassian.net/browse/L2-347

2022-03-08 09:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +    newNeuronId = event.detail.neuronId;
good. can you then update the declaration of `newNeuronId` if it amends not being set?

Currently `let newNeuronId: NeuronId;` I guess it can be `undefined` too according your comment.

2022-03-08 09:55 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +    newNeuronId = event.detail.neuronId;
yes, weird that TS didn't catch that. We might want to look into that...

2022-03-08 10:05 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/SetDissolveDelay.svelte
> +      dispatcher("nnsNext");
done

2022-03-08 10:53 UTC, peterpeterparker approved these changes
LGTM, thx!

2022-03-08 10:54 UTC, merged