Add neuron visibility cell
dfinity/nns-dapp pull request #5621
Opened 2024-10-15 09:26 UTC by coskucinkilic

# Motivation

Have a component to display bulk visibility change form neurons.

# Changes

 Add NeuronVisibilityCell to display controlled and uncontrolled neruons in the form

# Tests

Add tests to check NeuronVisibilityCell functioning as expected

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary

2024-10-15 18:09 UTC, dskloetd commented on frontend/src/lib/modals/neurons/NeuronVisibilityRow.svelte
> +          ? shortenWithMiddleEllipsis(rowData.uncontrolledNeuronDetails.text)
Didn't you already shorten the neuron ID here:
https://github.com/dfinity/nns-dapp/blob/7e3b2aa0e39631162587b38ddf34112beb0bff72/frontend/src/lib/utils/neuron.utils.ts#L530

This seems redundant.

2024-10-15 18:09 UTC, dskloetd commented on frontend/src/tests/lib/modals/neurons/NeuronVisibilityRow.spec.ts
> +      po: NeuronVisibilityRowPo.under(
Do you anticipate a reason not to return the `po` directly?

2024-10-15 18:09 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +    neuronId: string
named parameters

2024-10-15 18:09 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +    this.neuronId = neuronId;
`this.neuronId` seems to be unused.

2024-10-15 18:09 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +    return this.root
This can be replaced with just `this.isPresent("public-icon-container")`.

2024-10-15 18:09 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +    return await this.root
This can be replaced with just `return this.getText("ncontrolled-neuron-detail")` and then the method doesn't need to be `async`.

2024-10-16 06:13 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +    return await this.root
It still needs to return a `Promise`, but since it doesn't use the word `await` anymore, you don't need to declare the method as `async`.

2024-10-16 06:13 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
>      return this.root.querySelector("[data-tid='neuron-id']").getText();
This can also be `return this.getText("neuron-id");`

2024-10-16 08:25 UTC, dskloetd approved these changes

2024-10-16 08:25 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +  async getUncontrolledNeuronDetailsText(): Promise<string> {
Please remove `async`.

2024-10-16 08:25 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +  async isPublic(): Promise<boolean> {
Please remove `async`.

2024-10-16 08:25 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +  async getNeuronId(): Promise<string> {
Please remove `async`.

2024-10-16 09:14 UTC, coskucinkilic commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +  async isPublic(): Promise<boolean> {
@dskloetd I cannot remove async because internal call returns a promise.

2024-10-16 09:14 UTC, coskucinkilic commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +  async getNeuronId(): Promise<string> {
the same

2024-10-16 09:44 UTC, dskloetd requested changes

2024-10-16 09:44 UTC, dskloetd commented on frontend/src/tests/page-objects/NeuronVisibilityRow.page-object.ts
> +  async isPublic(): Promise<boolean> {
That is not what `async` means. Have you tried?
How is it different from [this](https://github.com/dfinity/nns-dapp/blob/7e3b2aa0e39631162587b38ddf34112beb0bff72/frontend/src/tests/page-objects/ProjectCard.page-object.ts#L34)?

2024-10-16 11:16 UTC, coskucinkilic commented
Sorry i read your message wrong, i don't know why i thought you want me to delete the promise. Updating it now.

2024-10-16 11:17 UTC, coskucinkilic commented
Also after this is merged, i will create another pr to make the last pr easier by adding checkbox into the row. I thought it would be easier to review as a separate pr than on top of this one.

2024-10-16 11:24 UTC, dskloetd approved these changes

2024-10-16 11:32 UTC, coskucinkilic commented
You can find the pr that i mentioned related to moving the checkbox into row [here](https://github.com/dfinity/nns-dapp/pull/5631/files)

2024-10-16 11:45 UTC, merged