L2 270 expandable
dfinity/nns-dapp pull request #586
Opened 2022-03-17 15:57 UTC by mstrasinskis

# Motivation

**Not a blocker. Can easily wait till the next week** 
Collapsible component.
[](https://dfinity.atlassian.net/browse/L2-270)

# Changes

- added Collapsible component
- added Collapsible support in CardBlock component
- added <Spinner `inline` />
- added `--animation-time-normal: 0.2s;`

# Tests

- Collapsible.spec
- updated CardBlock.spec (collapsible support)

# Screens

https://user-images.githubusercontent.com/98811342/158840485-0d27da00-c2bb-4f88-9c39-13e99903104f.mov

2022-03-18 06:32 UTC, lmuntanerDfinity requested changes
It looks amazing!!

A few questions and maybe changes in the API of the Collapsible.

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      initiallyExpanded
why not just pass `{expanded}` instead of `initiallyExpanded`?

Don't we have two duplicated states like this? The `expanded` here and inside `Collapsible`

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      headerAlign="center"
Why not let the child decide this, instead of the Collapsible?

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +    transition: all var(--animation-time-normal);
is this the animation of the Collapsible? Will we need this everytime we use the Collapsible?

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  afterUpdate(() => updateMaxHeight());
```
afterUpdate(updateMaxHeight);
```

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +    <IconExpandMore />
We agreed with Mischa to put the toggle in white. Feel free to do the small improvement.

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  let content: HTMLDivElement | undefined;
maybe `contentElement`, so that we understand better what it is.

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  let userUpdated: boolean = false;
`hasToggled`? I was expecting some data to be updated when I first read this variable.

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  export let maxContentHeigh: number | undefined = undefined;
Is this a typo? `maxContentHeight`?

2022-03-18 06:32 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +    transition: all var(--animation-time-normal);
Do we also need this in the parent using the Collapsible?

2022-03-18 08:24 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      headerAlign="center"
Not sure then what to do with the "expand" button.

2022-03-18 08:27 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +    <IconExpandMore />
Thanks. It's looks much better 👍

2022-03-18 08:28 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  export let maxContentHeigh: number | undefined = undefined;
Yes it is. Thanks!

2022-03-18 08:32 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      initiallyExpanded
With `initiallyExpanded` I tried to avoid having 2 source of the state. `expanded` looks like the parent could control the open state. But probably we need it.

2022-03-18 08:36 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +    transition: all var(--animation-time-normal);
This is animation for the collapsible. It's about the bottom part of the card. In the closed state there should be some bottom gap between the text end the end of the card:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/98811342/158965290-d70e95a6-75b4-4ca6-a5d5-149cd141ccee.png">

In the opened stated there should be none:

2022-03-18 08:43 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +    transition: all var(--animation-time-normal);
No. The CardBlock is an exception because of the different bottom padding.

2022-03-18 09:52 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      initiallyExpanded
I'll create a story for it (combined w/ update of the Followers Modal)

2022-03-18 09:53 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      headerAlign="center"
Moved to another story.

2022-03-18 10:05 UTC, lmuntanerDfinity approved these changes

2022-03-21 05:54 UTC, peterpeterparker requested changes
Any particular reason when the toggle icon color is `black` and not `white` - i.e. does not inherit current color?

Looks cool. Just a couple of questions.

2022-03-21 05:54 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +    bind:this={contentElement}
Can't `bind:clientHeight={h}` simplify this?

https://svelte.dev/tutorial/dimensions

2022-03-21 05:54 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      <div class="content">
Can this be refactored to avoid duplicate code?

2022-03-21 05:54 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +      &.alignCenter {
NTH: some styles are camel case, some are hyphen-separated case

2022-03-21 05:54 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  button {
if the header text is long, does the button appear over the text?

2022-03-21 05:54 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +            <div />
can't it be solved with css rather than with an empty dom element that has styling purpose?

2022-03-21 09:48 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +    bind:this={contentElement}
Thanks for the hint. Looks better 👍

2022-03-21 09:54 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  button {
Nope 
<img width="359" alt="image" src="https://user-images.githubusercontent.com/98811342/159238512-05833d20-e273-4516-b71d-f64da64a9db7.png">

2022-03-21 09:57 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +      &.alignCenter {
I didn't know that this syntax works `class:align-center={...` Updated. Thx!

2022-03-21 09:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Collapsible.svelte
> +  button {
Cool 👍

2022-03-21 10:15 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/CardBlock.svelte
> +      <div class="content">
As discussed, we let it as it is to avoid extra complexity notably.

2022-03-21 10:42 UTC, mstrasinskis commented on frontend/svelte/src/lib/modals/Modal.svelte
> +            <div />
🤦‍♂️ I didn't notice `grid-column-start: 2;` The fix-of-nothing was removed

2022-03-21 10:43 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/Modal.svelte
> +            <div />
Thanks

2022-03-21 10:45 UTC, peterpeterparker approved these changes
LGTM

2022-03-21 11:17 UTC, merged