L2-331: Check balances discard neurons
dfinity/nns-dapp pull request #610
Opened 2022-03-24 07:35 UTC by lmuntanerDfinity

# Motivation

Check neuron balances in the background and refresh them if needed.

# Changes

* After update call to get the neurons finishes, we check the balances of them.
* If a neurons has unmatched balance and stake, we claim and refresh it.
* Then we get the neurons again with an update call.
* Do not store neurons whose stake is less than the transaction fee.

# Tests

* Test that listNeurons checks balances and claims neurons when needed.
* Other tests on additional helpers added.

2022-03-24 07:35 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

No UI changes

2022-03-24 16:27 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/utils.ts
> + * Returns an array of arrays of size `chunkSize`
of size <= `chunkSize` ;)

2022-03-24 16:27 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/neurons.services.ts
> +    .map(({ fullNeuron }) => fullNeuron.id)
```
    .map(({ fullNeuron }) => fullNeuron.id as NeuronId)

```
could spare a map

2022-03-24 20:15 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/neurons.services.ts
> +    .map(({ fullNeuron }) => fullNeuron.id)
Will be available tomorrow:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/98811342/160002259-618b7a4f-0cb3-4972-b68f-6d0048f7900f.png">

2022-03-25 08:58 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +    .map(({ fullNeuron }) => fullNeuron.id)
oh, Let me try!

2022-03-25 09:00 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/utils.ts
> + * Returns an array of arrays of size `chunkSize`
true!

2022-03-25 09:06 UTC, lmuntanerDfinity commented
@mstrasinskis ready for another review

2022-03-25 11:00 UTC, mstrasinskis approved these changes
LGTM

2022-03-25 11:11 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      if (certified) {
nth: for code readability reason I think returning rather than nesting ifs is more readable

```
if (certified) {
    ...
    if (anyRefreshed) {
       ...
```

vs 

```
if (!certified) {
    return;
}

if (!anyRefreshed) {
   return;
}
```

2022-03-25 11:24 UTC, peterpeterparker requested changes
Thx. Two questions effectively, rest of the comments are just nice to have observations.

2022-03-25 11:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/ledger.api.ts
> +  // NOTE: We fetch the balance in an uncertified way as it's more efficient,
- Is this already the case in the Flutter app?

- Has it been acknowledged with the team?

2022-03-25 11:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +          const identity = await getIdentity();
nth: extract the logic in a dedicated function like `refreshNeuron`

2022-03-25 11:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +  if (balance.toE8s() !== fullNeuron.cachedNeuronStake) {
nth: suprised the eslint does not complain about two ifs in a row. probably something we can check when we discuss rules

2022-03-25 11:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
the functon name is `check...` but it does `createChunks`? it really does only checks or it does indeed update something?

2022-03-25 11:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +        const anyRefreshed = await checkNeuronBalances(neurons);
isn't a `try catch` here missing?

2022-03-25 11:39 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/api/ledger.api.ts
> +  // NOTE: We fetch the balance in an uncertified way as it's more efficient,
This comment was copied from the `dart` directory.

We can discuss with the rest of the team. I can bring up the subject on Monday.

2022-03-25 11:39 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +          const identity = await getIdentity();
makes sense

2022-03-25 11:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      if (certified) {
true, one of the patterns I added to our list of conventions.

2022-03-25 11:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +        const anyRefreshed = await checkNeuronBalances(neurons);
Yes, good point. I will add it with a TODO to manage errors.

We agreed with @mstrasinskis to discuss what to do in case of errors, and even what an error looks like here.

2022-03-25 11:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +  if (balance.toE8s() !== fullNeuron.cachedNeuronStake) {
they return different thimgs and one does a console.log as well.

I kept the same logic, even the log, as in the Flutter app.

2022-03-25 11:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
createChunks is just to parallize the request to get the balances. In case there were 1000 neurons, we don't want to do 1000 requests in parallel. Nor we want to wait for each request to move to the next one.

2022-03-25 11:51 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +        const anyRefreshed = await checkNeuronBalances(neurons);
added try/catch with TODO linking to the issue

2022-03-25 11:52 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review

2022-03-25 11:52 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review

2022-03-25 11:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/ledger.api.ts
> +  // NOTE: We fetch the balance in an uncertified way as it's more efficient,
Good to hear it was already like this in Flutter but yes, I think it is worth double checking it. Particularly "query and update" calls are a big topic these days. Thanks in advance!

2022-03-25 11:56 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +  if (balance.toE8s() !== fullNeuron.cachedNeuronStake) {
> as in the Flutter app.

gotcha. like I said it's a nice to have, fine with it, at least for now 😉

2022-03-25 12:01 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
So you get the balance of all neurons but the function name is `checkNeuronBalances` and it returns `true` or `false`? Why the function does not result the balance? What's true, what's false then?

Sorry I'm just a bit confuse to get it. Maybe can you add a comment in the code that describe what the function does?

2022-03-25 12:13 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
Let me refactor to make it more readable. I already refactored from the dart logic, but it's clearly not enough.

2022-03-25 12:20 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
@peterpeterparker I refactored and even removed the `refreshNeurons` helper.

Please, take a look at the new `checkNeuronBalances` function: https://github.com/dfinity/nns-dapp/pull/610/files#diff-67bec32ebb938d5a61f264be2987b10a94618d06b3b459d1b9e786789afb5c24R151

2022-03-25 12:38 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
Thanks way more clear 👍

Can you please transform the `console.log("Found neurons needing to be refreshed. Resyncing neurons...");` into a comment and we are  good to go I think.

2022-03-25 12:39 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      console.log(
Speaking of `console.log`, this should be a silent info, that's correct? Do we need the log?

2022-03-25 12:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +const checkNeuronBalances = async (neurons: NeuronInfo[]): Promise<boolean> => {
Sure, makes more sense to me as well.

2022-03-25 12:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      console.log(
not really

2022-03-25 12:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      console.log(
then I would say let's turn it into a comment or remove it

2022-03-25 12:52 UTC, peterpeterparker approved these changes
LGTM!

As discussed, thanks in advance for asking about the "query+update" topic question next week.

2022-03-25 13:03 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      console.log(
I even had a bug here that I caught while refactoring.

Check again `findNeuronsStakeNotBalance` again: https://github.com/dfinity/nns-dapp/pull/610/files#diff-67bec32ebb938d5a61f264be2987b10a94618d06b3b459d1b9e786789afb5c24R114

2022-03-25 13:22 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +    .filter((params) => !balanceMatchesStake(params))
if performance matter you can combine both `.filter`

```
.filter((...) => !balanceMatchesStake... && balanceIsMoreThanOne...
```

can probably even add `isDefined` 

again if performance is matter, don't know how much data there is, I understand multiple filter is easier - cleaner to read.

2022-03-25 13:23 UTC, peterpeterparker commented on frontend/svelte/src/lib/services/neurons.services.ts
> +      console.log(
Cool 👍

2022-03-25 14:19 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +    .filter((params) => !balanceMatchesStake(params))
I was aiming for readability, yes. Something to discuss in general I'd say.

2022-03-28 09:30 UTC, merged