Redirect sometimes
dfinity/nns-dapp pull request #627
Opened 2022-03-29 12:08 UTC by bitdivine

# Motivation

When testing Svelte it is useful to be able to compare with flutter.  At the moment there are several deployments, including prod and staging.  However it is not enough.  Sometimes there is a strange state and it is useful to be able to examine that state on the same canister, so there need to be redirects from neither svelte nor flutter.

Note: The names are also getting a bit confusing, so in addition to adding the new option, I deleted some old cruft.

References:
- https://dfinity.atlassian.net/browse/L2-440

# Changes

# Tests

2022-03-29 14:25 UTC, bitdivine commented on deploy.sh
> +DEPLOY_ENV=$NETWORK dfx deploy --no-wallet --network "$NETWORK" nns-dapp
The ii canister is not part of this repo, so should not be deployed by default.  It can always be deployed explicitly if wanted.

2022-03-29 14:31 UTC, bitdivine commented on frontend/svelte/env.config.mjs
I have removed values with confusing values, such as "1".  Once that is done, this rewriting code does nothing and can be deleted.

2022-03-29 16:13 UTC, lmuntanerDfinity requested changes
Not sure where we want this, but we also need to take care of the `npm run dev` during local development.

Either we add `REDIRECT_TO_LEGACY=svelte` to the package.json `dev` script.

Or you add a ternary in `env.config.mjs`:

```
const REDIRECT_TO_LEGACY = ENVIRONMENT === "local"
  ? "svelte "
  : process.env.REDIRECT_TO_LEGACY || "prod";
```

2022-03-29 16:13 UTC, lmuntanerDfinity commented on deploy.sh
> +DEPLOY_ENV=$NETWORK dfx deploy --no-wallet --network "$NETWORK" nns-dapp
Maybe add a comment that we have other dapps in `dfx.json` and that's why we need to specify this.

2022-03-29 16:13 UTC, lmuntanerDfinity commented on deploy.sh
>  echo "Deploying to $NETWORK..."
`echo "Deploying NNS Dapp to $NETWORK..."`?

2022-03-30 05:23 UTC, peterpeterparker requested changes

2022-03-30 05:23 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +  const showThisRoute = ["svelte", "both", "staging"].includes(
1. why `["svelte", "both", "staging"]` and sometimes only `["svelte", "both"]`?

2. can you move the duplicate code declaration to the constants?

something like

```
// constant
export const SHOW_ROUTE = ["svelte", "both", "staging"].includes(    process.env.REDIRECT_TO_LEGACY as string
  );
  );

// Components - routes
onMount(() => {
    if (!SHOW_ROUTE) {
      window.location.replace(`/${window.location.hash}`);
    }
  });
```

2022-03-30 10:13 UTC, bitdivine commented on deploy.sh
> +DEPLOY_ENV=$NETWORK dfx deploy --no-wallet --network "$NETWORK" nns-dapp
Regarding your comment about local deployment, a similar consideration may apply here.  We could check `DEV_ENV` and deploy all canisters for `local`.  What would make life easiest for those people who mostly work locally?

2022-03-30 10:25 UTC, peterpeterparker commented on frontend/svelte/src/routes/ProposalDetail.svelte
> +  const showThisRoute = ["svelte", "both", "staging"].includes(
Thanks for the feedback, works for me.

Maybe add a comment about the `staging` value in that particular piece of code, pretty sure I'll forget about it 😉

2022-03-30 10:27 UTC, peterpeterparker approved these changes

2022-03-31 08:36 UTC, bitdivine commented on deploy.sh
> +DEPLOY_ENV=$NETWORK dfx deploy --no-wallet --network "$NETWORK" nns-dapp
Per discussion, such logic is not required.  A comment is enough.

2022-03-31 08:42 UTC, bitdivine commented on deploy.sh
>  echo "Deploying to $NETWORK..."
Done.

2022-03-31 08:42 UTC, bitdivine commented on deploy.sh
> +DEPLOY_ENV=$NETWORK dfx deploy --no-wallet --network "$NETWORK" nns-dapp
Done: Comment added.

2022-03-31 10:06 UTC, lmuntanerDfinity approved these changes
💯

2022-03-31 12:09 UTC, merged