L2 449 hide open proposals issue
dfinity/nns-dapp pull request #643
Opened 2022-03-31 20:35 UTC by mstrasinskis

# Motivation

https://dfinity.atlassian.net/browse/L2-449
Fix a couple of bugs:
- excludeVotedProposals filter logic
- do not fetch on excludeVotedProposals (with mocking)
- fix no data-tid support of FiltersButton

# Changes

- added lastAppliedFilter to proposalsFilterStore

# Tests

- excludeVotedProposals tests were updated

2022-04-01 05:37 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/FiltersButton.svelte
> +<button data-tid={testId} on:click={filter} class="dark small"
is `testId` or `data-tid`?

2022-04-01 05:40 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/FiltersButton.svelte
> +  export let testId: string | undefined;
to be honest with you, not a big fan of adding props for test purpose only. 

wouldn't it work out too if we add the `data-id` to the `<div class="filters">`  container and then target `data-id="" > button` for the test or you rather like not too?

2022-04-01 05:42 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +    ballots.find(({ vote }) => vote === Vote.UNSPECIFIED) === undefined
when there never was any vote, isn't `ballots` empty?

2022-04-01 05:46 UTC, peterpeterparker commented on frontend/svelte/src/routes/Proposals.svelte
> +        <div class:hidden>
this is already a container `div` within `ProposalCard`, can we apply the style there instead of adding another additionital div in the dom?

2022-04-01 05:48 UTC, peterpeterparker commented on frontend/svelte/src/routes/Proposals.svelte
> +    position: absolute;
does position absolute comply with the intersection observer of the infinite scroll component?

2022-04-01 05:48 UTC, peterpeterparker requested changes
A couple of questions

2022-04-01 07:08 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/ui/FiltersButton.svelte
> +  export let testId: string | undefined;
I'm also not a fan of test props only. But from my perspective it's also a dev props. So as developer I can faster find the right place in the DOM without guessing by structure or styling or clicking inspect. So personally I would prefer to have `data-id` for all the components but I also understand that it's quite brutal (not a compromise 😄)

Regarding this particular case if I got you right the suggestion is to use `nth-child`. It will work but to be honest I would prefer to use same approach as often as possible to also not confuse people during e2e tests writing.

Another advantage is a reusability. So most e2e test could be applied to the redesigned version w/o rewriting the selectors.

2022-04-01 07:20 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +    ballots.find(({ vote }) => vote === Vote.UNSPECIFIED) === undefined
Hmm... Looks like all of them are in ballots but in state `UNSPECIFIED`
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/98811342/161214850-8af81382-d35c-471b-bc34-f457c9982ee9.png">

2022-04-01 07:53 UTC, mstrasinskis commented on frontend/svelte/src/routes/Proposals.svelte
> +        <div class:hidden>
I guess we can but then we can't reuse the Spinner 😄
What in your opinion is a better approach?
1. remove displaying the spinner (apply visibility style to ProposalCard entries)
2. remove the fetching mock (instantly apply the filter)
3. do real fetch on checkbox change

2022-04-01 07:58 UTC, mstrasinskis commented on frontend/svelte/src/routes/Proposals.svelte
> +    position: absolute;
Currently it doesn't trigger the intersection event but agree It's smells a bit.

2022-04-01 08:26 UTC, lmuntanerDfinity reviewed
A question.

2022-04-01 08:26 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/FiltersButton.svelte
> +  export let testId: string | undefined;
Not a big fan of test props, but I think that in some cases it might make sense. I would like to avoid relying in the DOM too much for e2e testing and having to redo all the e2e testing.

If we follow this approach, we might even be able to reuse a lot of the e2e testing for the new design.

2022-04-01 08:26 UTC, lmuntanerDfinity commented on frontend/svelte/src/routes/Proposals.svelte
> +        // mock fetching
wow, is this the best way? Isn't this filter applied locally? Why don't we just change the list immediately?

Sorry, I am not very familiar with Proposals.

2022-04-04 05:42 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/proposals.utils.ts
> +    ballots.find(({ vote }) => vote === Vote.UNSPECIFIED) === undefined
I had a look again at the Dart code and it was checking for `UNSPECIFIED` there well I guess we will be good indeed.

```
.filter((proposal) =>
                          !excludeVotedProposals ||
                          proposal.status != ProposalStatus.Open ||
                          proposal.ballots.values
                              .any((ballot) => ballot.vote == Vote.UNSPECIFIED))
                              ```

2022-04-04 05:44 UTC, peterpeterparker commented on frontend/svelte/src/routes/Proposals.svelte
> +    position: absolute;
It has to trigger the intersection. The observer does not start when the end of the page is reached but after 20%. I fear we will have some weird side effect and issue if not exactly all children of the observer trigger the intersection observer.

2022-04-04 05:47 UTC, peterpeterparker commented on frontend/svelte/src/routes/Proposals.svelte
> +        <div class:hidden>
Let's discuss this today. To be honest I don't get the motivation of the PR, missing the scope.

2022-04-05 10:09 UTC, mstrasinskis commented on frontend/svelte/src/routes/Proposals.svelte
> +        // mock fetching
Most of the time after clicking on the "votable proposals" user will see the same proposals. This is UX improvement to give a visual feedback that the list was updated.

2022-04-05 10:13 UTC, peterpeterparker commented on frontend/svelte/src/routes/Proposals.svelte
> +        <div class:hidden>
It has been improved by setting `hidden` within the card

2022-04-05 10:13 UTC, peterpeterparker commented on frontend/svelte/src/routes/Proposals.svelte
> +    position: absolute;
`position: absolute` won't be used

2022-04-05 10:48 UTC, peterpeterparker approved these changes
LGTM, thanks!

2022-04-05 11:11 UTC, merged