L2-365: Neuron Detail follow functionality
dfinity/nns-dapp pull request #646
Opened 2022-04-01 13:06 UTC by lmuntanerDfinity

# Motivation

User can edit followees from neuron details page.

# Changes

* New modal FollowNeuronsModal used in Neuron Details.
* Read followees and use them in EditFollowNeurons screen.

# Tests

* Test FollowNeuronsModal.

2022-04-01 13:07 UTC, lmuntanerDfinity commented
UI to show followees is not hardcoded nor the badges number:

![Screenshot 2022-04-01 at 10 52 28](https://user-images.githubusercontent.com/98735375/161269537-ceff008c-9e2f-48d1-b6ff-f560025dbbb7.png)

2022-04-01 13:07 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-04-04 04:46 UTC, peterpeterparker requested changes

2022-04-04 04:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neuron-detail/NeuronFollowingCard.svelte
> +  console.log(neuron);
to be removed

2022-04-04 04:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
> +  $: $accountsStore, (isControllable = isNeuronControllable(neuron));
- since this sync mechanism happens on a global scale it would make sense to move next to where it is set rather than in a sub-sub-sub-...-component in which the neuron is a local state

- is there test(s) for this?

2022-04-04 04:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
> +    if (followesPerTopic !== undefined) {
- can you extract the logic to a function to make it more obvious what's happening

- nth: es6

2022-04-04 04:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/FollowNeuronsModal.svelte
> +    height: min(500px, calc(100vh - 156px - (2 * var(--padding))));
mixin?

2022-04-04 04:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
>        return;
`loading = true` stays for ever  if `followeeAddress === undefined`?

2022-04-04 04:46 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neuron-detail/actions/FollowNeuronsButton.svelte
> +<button class="primary small" on:click={openModal}
is there a test?

2022-04-04 06:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
> +  $: $accountsStore, (isControllable = isNeuronControllable(neuron));
Do you mean to move it to the `accountStore` as I mention above? Initially I considered this as a neuron util, like `isCurrentUserController` or `hasValidStake` for example. Then I realized that it needed to be refreshed. This might happen other times. Therefore, we need a pattern that we can use for this "utils" that are not pure functions. What exactly do you propose?

Yes, there are tests for `isNeuronControllable` in `neurons.services.spec.ts`.

2022-04-04 06:40 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neuron-detail/NeuronFollowingCard.svelte
> +  console.log(neuron);
yes, thanks!

2022-04-04 06:44 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
> +    if (followesPerTopic !== undefined) {
sure

2022-04-04 06:47 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/FollowNeuronsModal.svelte
> +    height: min(500px, calc(100vh - 156px - (2 * var(--padding))));
sure

2022-04-04 06:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/NewFolloweeModal.svelte
>        return;
oh, good catch! The button is disabled, so this should never happen. But better be safe!

2022-04-04 06:51 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neuron-detail/actions/FollowNeuronsButton.svelte
> +<button class="primary small" on:click={openModal}
There is a test in the Neuron Details page that the button is there, and there is a test for the modal functionality.

Shall I add a test that this button opens the modal?

2022-04-04 07:58 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neuron-detail/NeuronMetaInfoCard.svelte
> +  $: $accountsStore, (isControllable = isNeuronControllable(neuron));
Sorry forget this comment, I misleaded the usage of the state.

2022-04-04 07:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neuron-detail/actions/FollowNeuronsButton.svelte
> +<button class="primary small" on:click={openModal}
That works, thanks

2022-04-04 08:01 UTC, lmuntanerDfinity commented
@peterpeterparker ready for next review

2022-04-04 08:18 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
> +  $: {
Should we go a step further and extract this to a `utils` and add a test.  What do you think?

2022-04-04 08:20 UTC, peterpeterparker requested changes

2022-04-04 08:20 UTC, peterpeterparker commented on frontend/svelte/src/lib/themes/mixins/_modal.scss
> +@mixin wrapper {
I would use something else than "wrapper" because the section contains already an element that is a ".wrapper" if I am not wrong

2022-04-04 08:22 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
> +  $: {
It accesses a store, where we need to subscribe in case there are changes. We could not just extract all of this to a util.

This pattern of utils that access stores and we want to have the updated data always is a common patter.

We might want to find a nice pattern to use everywhere. Similar to the topic of `$: $accountsStore, isControllable = isNeuronControllable(neuron)`.

I am not very happy with the hack. But maybe we can refactor all this together when we find a pattern we like.

2022-04-04 08:24 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/themes/mixins/_modal.scss
> +@mixin wrapper {
not in the mixing. This is a new mixing. But I can rename it.

2022-04-04 09:01 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/FollowTopicSection.svelte
> +  $: {
```
$ something = function($knownNeuronsStore)
```

2022-04-04 14:29 UTC, peterpeterparker approved these changes
Cool, thanks!

2022-04-04 14:57 UTC, merged