L2 329 lm manage errors stake neuron
dfinity/nns-dapp pull request #649
Opened 2022-04-04 09:17 UTC by lmuntanerDfinity

# Motivation

Stake Neuron flow: manage edge cases, show errors gracefully and give a better UX on errors.

# Changes

* Add "invalidStates" array in the CreateNeuronModal. Error should be shown and modal closed on unexpected edge cases.
* Show busy screen when updating delay and staking neuron.
* Manage errors in services instead of component during the flow.
* Components ConfirmDissolveDelay, SetDissolveDelay and EditFollowNeurons are not rendered without a neuron.

# Tests

PENDING

2022-04-04 10:02 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-04-05 05:08 UTC, peterpeterparker requested changes

2022-04-05 05:08 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  {#if currentStepName === "StakeNeuron" && selectedAccount !== undefined}
I made these changes on purpose - i.e. in my opinion the condition on the step of the wizard should only test the wizard name and not additional logic such as `&& selectedAccount !== undefined` or `newNeuron !== undefined`

In case of edge case, assuming the `currentStepName` is set and the additional clause is not set, the UI can become quirky and the user can be lost because no step and no feedback are displayed on screen.

In other words, for a smooth UI, a step should always be displayed.

That's why I deferred such logic as `selectedAccount !== undefined` or `newNeuron !== undefined` within their respective component and displayed for example spinner while data are loading.

How to you prevent these issues - i.e. how do you prevent no step to be rendered?

2022-04-05 06:22 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  {#if currentStepName === "StakeNeuron" && selectedAccount !== undefined}
I guess that it depends on what we want to do and the nature of the error.

At the moment, if we have the dissolve delay step and no neuron, it's not because we are fetching it, it's because something went wrong. Therefore, showing the spinner, will not be very helpful, because it will stay there forevever. We need to tell the user about it.

Another way is to also change the logic of when to move steps. Move steps earlier, before the previous step has finished. In this case, the spinner would make sense because in the end, the previous step would finish and we would have the neuron there. But we could show the spinner outside of the component, we show either the component or the spinner. But not the spinner inside the component.

I try to reduce the amount of complexity in components and adding the possiblity of `undefined` adds a case to be handled in the component that we could avoid. I guess this is a guideline we should agree on.

Also about when to move step. At the moment, we don't move until the step has finished totally. Therefore, the next step without neuron is an edge case where a Spinner is not information enough for the user.

Maybe a call with @mstrasinskis as well?

2022-04-05 06:28 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  {#if currentStepName === "StakeNeuron" && selectedAccount !== undefined}
- Spinner was only a placeholder, a skeleton or any other information can be used. 
- In my opinion and this particular case the complexity of testing if data are undefined or not should not be deferred to the parent because the parent is the wizard binder - i.e. beside nav within the wizard it should be kind of dumb

2022-04-05 12:24 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +  {#if currentStepName === "StakeNeuron" && selectedAccount !== undefined}
Discussed on Slack

2022-04-05 12:25 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-04-05 12:48 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +        ((neuron === null && newNeuron === undefined) ||
it's not "invalid" if neuron is null and newNeuron is not undefined and the contrary? likewise for account?

in short: it should not be`or`?

2022-04-05 14:05 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +        ((neuron === null && newNeuron === undefined) ||
Maybe I should not deconstruct here. This is when the `invalidState.neuron === null && newNeuron === undefined`.

This is an invalid state:
```
  type InvalidState = {
    stepName: string;
    neuron?: null;
    account?: null;
  };
```

I could set the `newNeuron` initial value to `null` as well to make it comparable to the InvalidState.

2022-04-05 14:21 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +        ((neuron === null && newNeuron === undefined) ||
Not a problem with destructing, I probably just don't get it 🤪

```
const invalidStates: InvalidState[] = [
    { stepName: "StakeNeuron", account: null },
    ...
    ```
    
What does `account: null` here mean? Is that "the state is invalid if the stepName is StakeNeuron and if the selected account is null"?

If so, what about renaming `account` to something maybe more obvious like `invalidCondition`? Or maybe even a function?

```
type InvalidState = { stepName: string; isInvalid: <T>(obj: T) => boolean };
```

2022-04-05 15:01 UTC, mstrasinskis reviewed
Looks good! Just a couple of comments.

2022-04-05 15:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
> +  $: neuronICP = neuron.fullNeuron?.cachedNeuronStake ?? BigInt(0);
good point!

2022-04-05 15:04 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
> +    dispatcher("nnsNext");
good point, I thought the same, not sure the idea of throwing only in the services it matches always.

2022-04-05 15:07 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/ConfirmDissolveDelay.svelte
> +      {votingPower({
yep!

2022-04-05 15:08 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +      <SetDissolveDelay
yes, thanks, it got back in after rebasing and solving conflicts.

2022-04-05 15:37 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +      <SetDissolveDelay
done

2022-04-05 15:45 UTC, mstrasinskis approved these changes
Thanks 👍

2022-04-05 15:49 UTC, merged