L2 361 lm neuron detail dissolve delay
dfinity/nns-dapp pull request #656
Opened 2022-04-05 09:51 UTC by lmuntanerDfinity

# Motivation

Modal in neuron details to increase the dissolve delay.

# Changes

* New modal IncreaseDissolveDelayModal that uses SetDissolveDelay and ConfirmDissolveDelay screens.
* Minor changes in SetDissolveDelay and ConfirmDissolveDelay to adapt for different use cases.
* IncreaseDissolveDelayButton opens IncreaseDissolveDelayModal.

# Tests

* Test flow for IncreaseDissolveDelayModal.

2022-04-05 09:51 UTC, lmuntanerDfinity commented
User flow:


https://user-images.githubusercontent.com/98735375/161728078-10ec14ef-b4f6-4156-ba77-2c15eccc97bc.mov

2022-04-05 09:51 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis please review

2022-04-06 05:16 UTC, peterpeterparker commented on frontend/svelte/src/tests/mocks/modal.mock.ts
> +export const waitModalIntroEnd = async ({
can't you use the existing `renderModal` utility function?

2022-04-06 05:17 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
>          min={0}
minimum should not be the effective delay minimum and not `0` in this case?

2022-04-06 05:24 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
>        data-tid="skip-neuron-delay"
should the `data-tid` be renamed, it isn't `skip-neuron-delay` anymore only

2022-04-06 05:25 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +        secondaryButtonText={$i18n.neurons.skip}
I was just thinking maybe `cancelButtonText` would work better since it is linked with even `nnsCancel`?

2022-04-06 05:28 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte
> +      on:back={goBack}
It's me on there isn't any `on:back` and `on:nnsUpdated` in `ConfirmDissolveDelay`?

2022-04-06 06:01 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/mocks/modal.mock.ts
> +export const waitModalIntroEnd = async ({
it was not yet generic, when I wrote it. After rebasing I shuold be able to use it.

2022-04-06 06:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
>        data-tid="skip-neuron-delay"
yes, true.

2022-04-06 06:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/CreateNeuronModal.svelte
> +        secondaryButtonText={$i18n.neurons.skip}
ok, makes sense

2022-04-06 06:05 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/IncreaseDissolveDelayModal.svelte
> +      on:back={goBack}
oh, good catch, this got messed up with resolving conflicts after rebasing

2022-04-06 06:39 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review

2022-04-06 08:06 UTC, mstrasinskis requested changes
Looks good, I only have a feeling that `increaseDissolveDelay` should be called with `(dissolveDelayInSeconds - neuron.dissolveDelaySeconds)` plz see the movie
https://user-images.githubusercontent.com/98811342/161926257-278d0514-03e7-4710-9a0d-7d1328d6822b.mov

2022-04-06 08:07 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SetDissolveDelay.svelte
> +    delayInSeconds === minDelayInSeconds;
I don't allow that, but yes, why not, better be prepared

2022-04-06 08:08 UTC, lmuntanerDfinity commented
Oh wow, thanks @mstrasinskis I would have never thought about it. I will change it now. I didn't even realize it, good catch!

2022-04-06 08:13 UTC, lmuntanerDfinity commented
@mstrasinskis fixed!

2022-04-06 08:50 UTC, mstrasinskis approved these changes
LGTM, thank you 👍

2022-04-06 09:04 UTC, peterpeterparker approved these changes

2022-04-06 09:19 UTC, merged