feat: new transaction store, context and init amount step
dfinity/nns-dapp pull request #657
Opened 2022-04-05 14:01 UTC by peterpeterparker

# Motivation

To create new transaction, user have to select and enter several data such as selecting the source account, selecting the destination address or account and the amount of ICP.

This PR add a store that contains these information and scope contextually its usage to the wizard (to avoid props going up and down and to scope logic withing components - i.e. steps).

In addition, to display the result of the selection, this PR also initialize the third step of the "New transaction" wizard. 

# Changes

- new `transaction.store`
- new `NewTransactionAmount` step - component
- extract common function that return the constant transaction fee as string
- insert `NewTransactionAmount` into wizard
- use new store in a wizard `context`
- use context in `NewTransactionDestination` (renamed) and `NewTransactionSource` (renamed) to select source and destination information
- bind input and selection of the account in `NewTransactionDestination`

# Screenshot

<img width="1513" alt="Capture d’écran 2022-04-05 à 16 01 14" src="https://user-images.githubusercontent.com/16886711/161771277-f13d2c27-bfd7-426d-b7d2-cb178a3657d3.png">

2022-04-05 14:17 UTC, lmuntanerDfinity requested changes
One proposal and questions

2022-04-05 14:17 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/accounts/Address.svelte
> +  const submitAddress = () => dispatcher("nnsAddress", { address });
Why do we need to pass the address if the parent already has the address?

I think that you can forward `on:submit`. If below you leave: `on:submit|preventDefault`. And when you use `<Address on:submit={...} bind:address />`.

2022-04-05 14:17 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
> +  const context: TransactionContext = getContext<TransactionContext>(
If we rely on the context here, doesn't that mean that we won't be able to reuse this component?

Isn't it use anywhere else?

2022-04-05 14:17 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/accounts/NewTransactionDestination.svelte
> +  <Address bind:address on:nnsAddress={chooseAddress} />
I think what I mentioned before: `<Address bind:address on:submit={chooseAddress}`.

Or, if we rely on the event, no need to `bind:address`. I also like the idea of not binding and getting it from the event.

2022-04-05 14:27 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/accounts/NewTransactionAmount.svelte
> +  const context: TransactionContext = getContext<TransactionContext>(
> Isn't it use anywhere else?

As far as I now it's only there but it won't be difficult to extend, features are well scoped to the component.

> If we rely on the context here, doesn't that mean that we won't be able to reuse this component?

Yes and no. Yes in that form you can only use the component where the context has been set but no, you can also use the component if you defined the context, just need to extend it to support different key. We can also extend the context to be more generic, like having a generic context for wizard.

```
export interface WizardContext<T> {
   store: T;
   next: () => void;
}

export interface NewTransactionContext extends WizardContext...

export interface CreateNeuronContext extends WizardContext...
```

A spontaneous idea, not a thing we should or we shall do. Just want to highlight the fact that it can I think be enhanced quite easily.

2022-04-05 15:20 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/accounts/Address.svelte
> +  const submitAddress = () => dispatcher("nnsAddress", { address });
Done

2022-04-06 08:22 UTC, lmuntanerDfinity approved these changes

2022-04-06 08:49 UTC, mstrasinskis approved these changes
LGTM. Just a couple of questions.

2022-04-06 08:49 UTC, mstrasinskis commented on frontend/svelte/src/lib/stores/transaction.store.ts
> +export const NEW_TRANSACTION_CONTEXT_KEY = "new-transaction";
😎 
```suggestion
export const NEW_TRANSACTION_CONTEXT_KEY = Symbol("new-transaction");
```

2022-04-06 08:49 UTC, mstrasinskis commented on frontend/svelte/src/lib/components/accounts/NewTransactionDestination.svelte
> +      disableSelection={!emptyAddress(address)}
This **!** emptyAddress looks wrong. But please ignore if it suppose to be like this 👍

2022-04-06 09:08 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/accounts/NewTransactionDestination.svelte
> +      disableSelection={!emptyAddress(address)}
Yeah it's correct, added a comment in the code

> <!-- note about disableSelection: if user is entering an address with the input field, the address is not empty and therefore no account shall be selected -->

2022-04-06 09:58 UTC, merged