Feat: Merge neurons functionality
dfinity/nns-dapp pull request #715
Opened 2022-04-14 14:32 UTC by lmuntanerDfinity

# Motivation

User can merge neurons.

There are two types of checks. Individual and in pairs.

* Neurons might not be mergeable for their attributes (ex: joined community fund).
* Pairs of neurons might not be mergeable by the combination of their attributes (ex: both have different controller).

# Changes

* Add Functionality to the MergeNeuronsModal to check if neurons are mergeable or not and perform action.
* Add util "canBeMerged" to check if neurons can be merged
* Add governance api "mergeNeurons"
* Add prop "disabled" to NeuronCard and Card.
* Add util "mapMergeableNeurons" to wrap NeuronInfo with information about mergeability.
* Add neuron service "mergeNeurons".

# Tests

* Test new functionality in the MergeNeuronsModal.
* New tests for "mergeNeurons" governance api.
* New tests for "mergeNeurons" service.
* New tests for new utils.

2022-04-14 14:53 UTC, lmuntanerDfinity commented
@peterpeterparker @mstrasinskis pending updating nns-js but it has been tested locally and it's ready for review

2022-04-14 16:58 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
> +    dispatcher("nnsClose");
have you already discussed with Mischa if we should keep the modal open or not?

I did not, spontaneously feels like they should remain open so but if you already defined they should be closed, then I should improve something in the "new transaction wizard". Not blocking this PR, stricly question.

2022-04-14 17:03 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +        {#if isMaxSelection(selectedNeuronIds) && isNeuronSelected(selectedNeuronIds, neuron.neuronId)}
since it's a loop, might be worth to improve perf a bit by querying `isMaxSelection` and `isNeuronSelected` only once per data instead of possibly twice?

2022-04-14 17:05 UTC, peterpeterparker commented on frontend/svelte/src/lib/themes/mixins/_interaction.scss
> +  touch-action: none;
`pointer-events: none`?

2022-04-14 17:12 UTC, peterpeterparker reviewed
Nice PR, lots of cool stuffs. Will have to review it once more when you include nns-js because it isn't a trivial one 👍

Did you had some try with lots of neurons, like 20+? Feels like there is lots of maps and finds and ifs, just want to be sure it is performance wise good also with few neurons.

2022-04-19 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
> +    dispatcher("nnsClose");
I didn't check this with Mischa. I guess this is a general question for all the Modals that we open for the functionality.

I will speak with him and implement the same behaviour every where.

2022-04-19 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +        neurons: neuronsData.map(({ neuron }) => neuron),
map data is of type `MergeableNeuron`. It seems that if I pass this type to `mapNeuronIds` it will make it much more specific and harder to reuse.

If the params are an array of `NeuronId` and `NeuronInfo`, then we might be able to reuse this in other places

2022-04-19 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
>      if (selectedNeuronIds.length < MAX_NEURONS_MERGED) {
I could, I can refactor to be `>=` and use it here as `!isMaxSelection`, sounds good.

2022-04-19 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +        {#if isMaxSelection(selectedNeuronIds) && isNeuronSelected(selectedNeuronIds, neuron.neuronId)}
ok

2022-04-19 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/themes/mixins/_interaction.scss
> +  touch-action: none;
👍

2022-04-19 17:30 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +      mergeable: !mergeable
The `messageKey` is different.

I can refactor to use helpers and do it on the same place though.

2022-04-19 18:10 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review.

I tested with more than 20 neurons, check the video below.

https://user-images.githubusercontent.com/98735375/164068479-8054d2a2-4219-4bc5-86e2-631dc1dcb9a2.mov

2022-04-20 09:44 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
> +    dispatcher("nnsClose");
Cool thanks! Please keep me posted about the decision.

2022-04-20 09:45 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +        neurons: neuronsData.map(({ neuron }) => neuron),
alright

2022-04-20 09:49 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
> +      sourceNeuronId: neurons[1].neuronId,
I guess `neurons[1]` cannot be `undefined`, maybe worth adding a comment about how / why because I asked my self the question again

2022-04-20 09:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +    {#each neuronsData as { neuron, mergeable, messageKey }}
as we rerender on selection this for each, maybe worth adding a key to help svelte preserve the order?

```
{#each neuronsData as { neuron, mergeable, messageKey } (neuron.id)}
```

2022-04-20 09:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +      {@const isSelected = isNeuronSelected(selectedNeuronIds, neuron.neuronId)}
coolio

2022-04-20 10:10 UTC, peterpeterparker commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +  for (let i = 0; i < firstList.length; i++) {
can / should we extract this in a specific function to test it explicitly? 
code feels funky, not sure exactly what it does by reading it

2022-04-20 10:11 UTC, peterpeterparker reviewed
Minor questions.

PR is quite a PR, I would be happy if @mstrasinskis also reviews it before going futher

2022-04-20 10:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
> +      sourceNeuronId: neurons[1].neuronId,
sounds good

2022-04-20 10:50 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/SelectNeurons.svelte
> +    {#each neuronsData as { neuron, mergeable, messageKey }}
I didn't know about this, makes sense to me! But I thought that the order would come from the neuronsData array.

2022-04-20 10:53 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +  for (let i = 0; i < firstList.length; i++) {
sure

2022-04-20 11:35 UTC, lmuntanerDfinity commented
@peterpeterparker changes done, ready for next round

2022-04-20 13:47 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/neurons/ConfirmNeuronsMerge.svelte
> +    dispatcher("nnsClose");
After talking with Mischa, the preferred way is to catch errors during the Wizard, while the user makes decisions.

Yet, if the error comes from the call to the canister, we consider that an edge case and we close the modal and show an error toast that should not disappear until closed by the user.

2022-04-21 21:59 UTC, mstrasinskis requested changes
Looks really nice, mostly nitpicks that can be ignored. Could you please only recheck the sorting that we didn't miss anything?

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/neurons.services.ts
> +
nitpick/suggestion:
to not loose the success feedback even when `listNeurons` fails
```ts
    let success = false;
    ...
    await mergeNeuronsApi({ sourceNeuronId, targetNeuronId, identity });
    success = true;
    ...
    // remove - return undefined;
  }
  return success ? targetNeuronId : undefined;
}
```

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/neurons.services.ts
> +  try {
We could discuss using `logWithTimestamp` tomorrow

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/i18n/en.json
> +    "merge_neurons_same_id": "Two neurons with same id can't be merged. Check the article for more: ",
Would it be nice to have the article link also in the i18n file? Not in this PR.

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +export const canBeMerged = (
Is it planed to merge more then 2 neurons in the future?

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +    .sort();
No sure, but shouldn't the subarrays be sorted?

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +    .sort();
not sure, but shouldn't the subarrays be sorted?

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +  const lengths = sortedFolloweesLists.map(({ length }) => length);
if the lists are sorted in theory we could do something like `new Set(sortedFolloweesLists.join()).length === 1'

2022-04-21 21:59 UTC, mstrasinskis commented on frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
> +  describe("mapMergeableNeurons", () => {
It's not related only to this specific test, because the function supports more then 2 neurons, should length=3 also be tested?

2022-04-22 04:45 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/api/governance.api.ts
> +  const { canister } = await governanceCanister({ identity });
sure, my PR was realier than this functionality, hence that I didn't add it 😉

2022-04-22 04:48 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/error.utils.ts
> +export const mapNeuronErrorToToastMessage = (error: Error): ToastMsg => {
I think that the message will be different for a NotFound if it's related to a neuron or a proposal for example.

That's why I think that we can keep the name.

Another way would be to pass the resource as well, but I think that another similar function for proposals would be more flexible than trying to fit one function everywhere.

2022-04-22 04:49 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +
good point!

2022-04-22 04:51 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +  try {
also in the services?

2022-04-22 04:52 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/i18n/en.json
> +    "merge_neurons_same_id": "Two neurons with same id can't be merged. Check the article for more: ",
Yes, it would be better if we could put HTML in the messages.

2022-04-22 04:53 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +export const canBeMerged = (
I don't see why it wouldn't be possible.

I see it more as a current implementation. That's why I kept it generic specially in the utils.

2022-04-22 04:56 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +    .sort();
yes, good catch! The test was passing because the order was the same.

When I put the sort in the subarray the test was fixed. I left the test with unordered followees.

2022-04-22 04:59 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +  const lengths = sortedFolloweesLists.map(({ length }) => length);
not exactly, but I see where you're going and yes!

2022-04-22 05:02 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
> +  describe("mapMergeableNeurons", () => {
I can, sure

2022-04-22 05:09 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/api/governance.api.ts
> +  const { canister } = await governanceCanister({ identity });
done

2022-04-22 05:10 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/services/neurons.services.ts
> +
done

2022-04-22 05:10 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +  const lengths = sortedFolloweesLists.map(({ length }) => length);
done

2022-04-22 05:10 UTC, lmuntanerDfinity commented on frontend/svelte/src/tests/lib/utils/neuron.utils.spec.ts
> +  describe("mapMergeableNeurons", () => {
done

2022-04-22 05:10 UTC, lmuntanerDfinity commented
@mstrasinskis please review

2022-04-22 05:19 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/neuron.utils.ts
> +export const canBeMerged = (
Got it, thanks.

2022-04-22 05:19 UTC, mstrasinskis commented on frontend/svelte/src/lib/utils/error.utils.ts
> +export const mapNeuronErrorToToastMessage = (error: Error): ToastMsg => {
Thank you for explanation.

2022-04-22 05:27 UTC, mstrasinskis approved these changes
LGTM. Thank you 👍

2022-04-22 05:27 UTC, mstrasinskis commented on frontend/svelte/src/lib/services/neurons.services.ts
> +  try {
Depends on what makes sense. There is currently no strict rules for that.

2022-04-22 11:06 UTC, merged