L2-476: Improve Form Input Validation Error
dfinity/nns-dapp pull request #769
Opened 2022-04-29 11:49 UTC by lmuntanerDfinity

# Motivation

User receives immediate feedback when entering a wrong hotkey.

# Changes

* Extend Input element to show an error message.
* Extend Input element to listen for blur event.
* Validate address entered on blur in AddHotkeyModal.

# Tests

* Extend Input tests with new functionality.
* Extend AddHotkeyModal tests with validation scenarios.

2022-04-29 11:51 UTC, lmuntanerDfinity commented
UX video:

https://user-images.githubusercontent.com/98735375/165939001-ce4f4a23-fa07-4b28-855f-6ba7ed18e8cd.mov

Screenshots:

![Screenshot 2022-04-29 at 13 44 23](https://user-images.githubusercontent.com/98735375/165939033-274fd0d0-ef3c-4b83-8e03-924e8ca30899.png)
![Screenshot 2022-04-29 at 13 49 23](https://user-images.githubusercontent.com/98735375/165939039-ab4f46ca-3cd4-4710-bac8-25e4659396ee.png)

2022-04-29 11:52 UTC, lmuntanerDfinity commented
@mstrasinskis @peterpeterparker please review

2022-05-02 05:09 UTC, peterpeterparker commented
as discussed this first version leads to layout shift but the input itsel should not move in my opinion. with layout shift personally I understood the display of the error moves whats below. can you please improve this?

<img width="1513" alt="Capture d’écran 2022-05-02 à 07 07 56" src="https://user-images.githubusercontent.com/16886711/166186916-d393d555-2c79-4cdc-a620-78eedfc618a1.png">

2022-05-02 05:11 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +<div
- do we really need that `div`? if we had it then all inputs will be rendered with an extra div in the DOM

- if we really need it, then should we create rather create a new component `InputWithError` or whatever because it isn't just an input anymore?

2022-05-02 05:12 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  let validPrincipal: Principal | undefined;
shouldn't this be a utility function rather than being implemented within the component?

2022-05-02 05:16 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  // Hide error when user is changing the value.
from the comment I excepted

```
$: showError = false;
```

can you rephrase the comment?

2022-05-02 05:17 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  let prevValidatedAddress: string | undefined;
do we really want to not hide the error when user type?

to some extension we hide the error but then on blur the error can popup again, so is it really useful?

should we validate the adress on input with a debounce aswell?

2022-05-02 05:18 UTC, peterpeterparker requested changes
Couple of comments + layout shift

2022-05-02 05:52 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +<div
ok

2022-05-02 05:53 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  let validPrincipal: Principal | undefined;
Sure

2022-05-02 05:53 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  // Hide error when user is changing the value.
ok

2022-05-02 05:55 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  let prevValidatedAddress: string | undefined;
I followed what Mischa [wrote](https://www.notion.so/Form-validation-messages-on-dark-background-43afe1a80b0b402c945855b5cdd9eb16#c0ffa14328fb4579a9ef26ac0bf3faec):

> - Validate on blur (add validation message/error on blur)
> - Remove validation message/error on change

2022-05-02 06:55 UTC, lmuntanerDfinity commented
@peterpeterparker ready for another review

I could have used the same `Input`, but I liked better your idea of a new Input. If we don't want layout shift, we need to make sure the space is there even if we don't show the error. Which I did using a margin-bottom.

Yet, since not all inputs want or need this space, it made more sense to have the `InputWithError` component for those place where we can assume this extra bottom space.

2022-05-02 09:08 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +<div class={`input-block ${theme}`} class:disabled class:error>
this should move to `InputWithError` no?

2022-05-02 09:10 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/InputWithError.svelte
> +  <Input
`{...$$props}` or that does not work here?

2022-05-02 09:12 UTC, peterpeterparker reviewed
two comments

2022-05-02 09:14 UTC, peterpeterparker commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  let prevValidatedAddress: string | undefined;
Would just `$: value, showError = false` work then?

2022-05-02 09:38 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/InputWithError.svelte
> +  <Input
I'd rather be explicit.

2022-05-02 09:39 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +<div class={`input-block ${theme}`} class:disabled class:error>
The border of the input is set in this component. I guess I could do it without a prop, but I think a prop is the most readable option.

2022-05-02 10:00 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/InputWithError.svelte
> +  <Input
oki doki

2022-05-02 10:01 UTC, peterpeterparker commented on frontend/svelte/src/lib/components/ui/Input.svelte
> +<div class={`input-block ${theme}`} class:disabled class:error>
forget my question, thanks for the answer

2022-05-02 11:32 UTC, lmuntanerDfinity commented
@peterpeterparker, I forgot to push a new video with the UX:

https://user-images.githubusercontent.com/98735375/166227161-d6d7b3e7-4b4a-45c1-9937-7f7788f32276.mov

2022-05-02 11:35 UTC, lmuntanerDfinity commented on frontend/svelte/src/lib/modals/neurons/AddHotkeyModal.svelte
> +  let prevValidatedAddress: string | undefined;
It does! I love these Svelte tricks, nice one!

2022-05-02 12:29 UTC, peterpeterparker approved these changes
thanks

2022-05-02 12:47 UTC, merged