Placeholder changelog entry
dfinity/nns-dapp pull request #808
Opened 2022-05-09 08:04 UTC by bitdivine

# Motivation

# Changes

# Tests

2022-05-09 10:50 UTC, lmuntanerDfinity approved these changes
LGTM

2022-05-09 10:50 UTC, lmuntanerDfinity commented on release/PROPOSAL.md
> +* Hide "remove hotkeys" if the user is not the controller
This is for Svelte, I would not add it here. The user won't see this change.

2022-05-09 10:51 UTC, lmuntanerDfinity requested changes
Sorry, one change requested

2022-05-09 11:50 UTC, bitdivine commented on release/PROPOSAL.md
> +* Hide "remove hotkeys" if the user is not the controller
Ok, removing.  Thank you for the review!

2022-05-10 12:24 UTC, lmuntanerDfinity approved these changes

2022-05-10 16:04 UTC, merged