L2-585: Setup Cycles Minting and IC Management Canisters
dfinity/nns-dapp pull request #885
Opened 2022-05-20 12:20 UTC by lmuntaner

# Motivation

Setup Cycles Minting and IC Management Canisters for client requests.

# Changes

* New canister folders "ic-management" and "cmc". Each with the files needes to setup the canister class.
* New canister apis "createCanister", "topUpCanister" and "queryCanisterDetails".

# Tests

* Test for ic-manangement canister
* Test for cycles management canister.
* Test for new canister apis.

2022-05-20 12:24 UTC, lmuntaner commented
@mstrasinskis @peterpeterparker please review

There are many files. Most of them are related to the candid interface. The important files in this PR are:

* frontend/svelte/src/lib/canisters/cmc/cmc.canister.ts
* frontend/svelte/src/lib/api/canisters.api.ts
* frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts

2022-05-23 09:31 UTC, lmuntaner commented
@bitdivine it makes sense that you take a look also if you have time.

2022-05-23 12:55 UTC, peterpeterparker requested changes
Few questions and some feedback

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  const response = await canister.getCanisterDetails(canisterId.toText());
the function declaration should accept `principal` as parameter since it is revered back with `Principal.fromText` within `getCanisterDetails`

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +export const queryCanisterDetails = async ({
should we called this function `query...`?

other `query...` have a `certified` option but here this is always an update call I think

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  const ledger = LedgerCanister.create({
there is a function `ledgerCanister` in `ledger.api.ts` that can be exposed to avoid code duplication

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  const toSubAccount = principalToSubAccount(principal);
can you add a comment here? don't know why we convert the user's auth principal to a subaccount

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  await cmc.notifyTopUp({
if this fails, user looses his/her ICP that were transferred above? or these cycles are only debited if `notifyTopUp` succeed? if not, do we prevent this?

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +// TODO: Remove before merging
Forgot to remove it?

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +export const cmcCanister = async (
just an idea: you often rename the canister when you destruct the answer. you could have make a single function that return both

```
const canisters = async (
  identity: Identity
): Promise<{
  agent: HttpAgent;
  cmc: CMCCanister;
  icMgmt: ICManagementCanister
}> => {
  const agent = await createAgent({
    identity,
    host: HOST,
  });

  const cmc = CMCCanister.create({
    agent,
    canisterId: CYCLES_MINTING_CANISTER_ID,
  });

  const icMgmt = ICManagementCanister.create({
    agent,
    canisterId: IC_MANAGEMENT_CANISTER_ID,
  });

  return { cmc, icMgmt, agent };
};
```

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/cmc/cmc.canister.ts
> +    // TODO validate the certificate in the response
there is a jira task?

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/cmc/utils.ts
> +export const principalToSubAccount = (principal: Principal): Uint8Array => {
no tests?

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/converters.ts
> +  response,
nth: if you deconstruct the `response` you can spare some `response.`

2022-05-23 12:55 UTC, peterpeterparker commented on frontend/svelte/src/routes/Canisters.svelte
> +        <p>
just a placeholder or we should effectively display no canister id if a name is given?

2022-05-24 05:06 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  // but it can be an empty string
Thanks for the feedback. Can you add a comment/link to the backend task that also attaches the canister?
Can be someday useful.

2022-05-24 05:09 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/converters.ts
> +export const toCanisterDetails = ({
not against. then we should maybe also extract the mapping of the accounts to the converter (not in this pr) so that it follows same pattern.

2022-05-24 05:14 UTC, peterpeterparker commented on frontend/svelte/src/routes/Canisters.svelte
> +        <p>
In that case, I think even if a name is provided both canister ID and name should be displayed - not one or the other.

As a user, I am super duper looking forward to add name support in nns-dapp but also still need the canister id too.

2022-05-24 05:16 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
> +  let effectiveCanisterId = Principal.fromText("aaaaa-aa");
You can use the constant everywhere. `aaaaa-aa` is the IC management canister address.

https://smartcontracts.org/docs/current/references/ic-interface-spec#http-effective-canister-id

2022-05-24 08:04 UTC, mstrasinskis reviewed
LGTM. Just a couple of suggestions.

2022-05-24 10:31 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  // but it can be an empty string
sure

2022-05-24 10:34 UTC, lmuntaner commented on frontend/svelte/src/routes/Canisters.svelte
> +        <p>
This is a discussion for the CanisterCard I guess. We can put both there, I agree. This was just while development and to be aware myself that the name can be defined, but empty string and that was why it wasn't show here.

But the next task already changes this code.

2022-05-24 10:34 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  logWithTimestamp(`Topping up canister ${canisterPrincipal.toText()} call...`);
maybe better the canister id

2022-05-24 10:35 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/cmc/cmc.canister.ts
> +      `Unsupported response type in notifyTopUp ${JSON.stringify(response)}`
good to know, we can do all of those in one single PR

2022-05-24 10:35 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  logWithTimestamp(`Topping up canister ${canisterPrincipal.toText()} call...`);
I realized, this is the CanisterId, I will rename the variable. It's the same that is shown in the UI.

2022-05-24 10:36 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/cmc/cmc.idl.js
> +export const idlFactory = ({ IDL }) => {
yes

2022-05-24 10:40 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  const ledger = LedgerCanister.create({
done

2022-05-24 10:43 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  // nns dapp backend polls the transactions
done

2022-05-24 10:43 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
> +  let effectiveCanisterId = Principal.fromText("aaaaa-aa");
We get the service from agent-js, which removes this code from nns-dapp.

Islam suggested it.

2022-05-24 10:44 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/cmc/cmc.idl.js
> +export const idlFactory = ({ IDL }) => {
done, here and in the candid file

2022-05-24 10:44 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  const toSubAccount = principalToSubAccount(principal);
done

2022-05-24 10:45 UTC, lmuntaner commented
@mstrasinskis @peterpeterparker ready for another review

2022-05-25 05:11 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
> +    let rawResponse: CanisterStatusResponse;
nth: move `let rawResponse` into `try {...`, transform it in a `const` and move `toCanisterDetails({...` in try too doing so error in `toCanisterDetails` would also be catched

2022-05-25 05:13 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +export const queryCanisterDetails = async ({
not only for `query` but spontaneously just thought it's a bit misleading to have a function name `queryCanisterDetails` that cannot perform `query` - i.e. always do `update calls`. e.g. `getCanisterDetails` would not imply the notion of type of request. Can live with it though.

2022-05-25 05:21 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  // The same background tasks that notifies the CMC also attaches the canister.
can you also add the `// TODO` with the related jira number here?

2022-05-25 05:26 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
> +  let effectiveCanisterId = Principal.fromText("aaaaa-aa");
agent-js uses `Principal.fromHex('')` ([source](https://github.com/dfinity/agent-js/blob/2fe3dd99cddfcf45c6d9d5b7a199a86285ce9740/packages/agent/src/canisters/management.ts#L53)) and not `Principal.fromText("aaaaa-aa")`....does that still work?

2022-05-25 05:27 UTC, lmuntaner commented on frontend/svelte/src/lib/api/canisters.api.ts
> +  // The same background tasks that notifies the CMC also attaches the canister.
sure

2022-05-25 05:28 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/cmc/utils.ts
> +export const principalToSubAccount = (principal: Principal): Uint8Array => {
done

2022-05-25 05:29 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/converters.ts
> +export const toCanisterDetails = ({
ok

2022-05-25 05:30 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
> +    let rawResponse: CanisterStatusResponse;
yep, good point

2022-05-25 05:31 UTC, peterpeterparker commented on frontend/svelte/src/routes/Canisters.svelte
> +        <p>
CanistedId is like the account identifier ID, you need it elsewhere. e.g. you need to use it in your own project to be able to deploy on the IC (`./canister_ids.json`) or use it to open it or the the candid ui in your browser or to transfer cycles manually etc.

2022-05-25 05:34 UTC, lmuntaner commented
@peterpeterparker ready for another review.

IMO the last comments didn't deserver a "Request changes", they were to add one comment and to move three lines of code. You can trust me to do that well.

2022-05-25 05:34 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.canister.ts
> +  let effectiveCanisterId = Principal.fromText("aaaaa-aa");
yes, it works. I tested it.

2022-05-25 05:35 UTC, lmuntaner commented on frontend/svelte/src/routes/Canisters.svelte
> +        <p>
There is a PR already for this: https://github.com/dfinity/nns-dapp/pull/899

2022-05-25 05:36 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/cmc/cmc.canister.ts
> +    const response = await this.service.get_icp_xdr_conversion_rate();
nth: `const {data}` can be deconstructed

2022-05-25 05:39 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.types.ts
> +import type { definite_canister_settings } from "@dfinity/agent/lib/cjs/canisters/management_service";
that import doen't seem correct. `cjs` is for nodejs runtime.

2022-05-25 05:41 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
> +    // TODO: Throw proper errors
jira task or you've got this under radar?

2022-05-25 05:42 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.types.ts
> +import type { definite_canister_settings } from "@dfinity/agent/lib/cjs/canisters/management_service";
Let me use `esm`

2022-05-25 05:42 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.types.ts
> +import type { definite_canister_settings } from "@dfinity/agent/lib/cjs/canisters/management_service";
We can also make a PR in agent-js to expose those types directly.

2022-05-25 05:43 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
> +    // TODO: Throw proper errors
let me create it

2022-05-25 05:44 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/nns-dapp/nns-dapp.canister.ts
> +    // TODO: Throw proper errors
done

2022-05-25 05:44 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.types.ts
> +import type { definite_canister_settings } from "@dfinity/agent/lib/cjs/canisters/management_service";
done

2022-05-25 05:45 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/cmc/cmc.canister.ts
> +    const response = await this.service.get_icp_xdr_conversion_rate();
done

2022-05-25 05:45 UTC, lmuntaner commented
@peterpeterparker ready for another review

2022-05-25 05:51 UTC, peterpeterparker commented on frontend/svelte/src/lib/api/ledger.api.ts
> +  memo?: bigint;
can you add a test for `memo` in `ledger.api.spec`? same test as for `fromSubAccountId`

2022-05-25 05:51 UTC, lmuntaner commented on frontend/svelte/src/lib/api/ledger.api.ts
> +  memo?: bigint;
sure

2022-05-25 05:53 UTC, lmuntaner commented on frontend/svelte/src/lib/api/ledger.api.ts
> +  memo?: bigint;
done

2022-05-25 05:54 UTC, lmuntaner commented
@peterpeterparker ready for another review

2022-05-25 05:55 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.errors.ts
> +export type HttpError = {
I guess it was coded like this in `ts` but we don't use type for errors. Shouldn't we use a `class` because otherwise we cannot test its type `instanceof` as we do for the all our other errors. What do you think?

2022-05-25 05:56 UTC, peterpeterparker approved these changes
LGTM, thanks.

Just added a comment regarding the error before approve, if you can have a look before merging.

2022-05-25 05:56 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.errors.ts
> +export type HttpError = {
We do use custom errors here: `throw new UserNotTheControllerError();`

This is a type used in the helper, but then we extract the information from there.

I can throw the error directly here and skip this type though.

2022-05-25 05:59 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.errors.ts
> +export type HttpError = {
Yes it is what I meant. We do use custom errors like `new UserNotTheControllerError` that are `class` not `type`.

Throwing it directly sounds good.

2022-05-25 06:09 UTC, lmuntaner commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.errors.ts
> +export type HttpError = {
I refactored to make it nicer. The helper now returns an Error or a UserNotTheControllerError type. Which makes more sense.

2022-05-25 06:20 UTC, peterpeterparker commented on frontend/svelte/src/lib/canisters/ic-management/ic-management.errors.ts
> +export type HttpError = {
Thanks

2022-05-25 06:22 UTC, merged